### ISSUE TITLE
Debug apk always crash with LinkageError

### ISSUE THREAD

**Issue by longht89** [google/dagger#1011]
Hi, i have a problem when i built debug apk. It's always crash.

And this is log:

    Process: com.farmivn.farmi.staging.dev, PID: 13130
    java.lang.LinkageError: com.farmivn.presentation.activity.product.detail.ProductDetailActivity
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
        at dalvik.system.DexPathList.findClass(DexPathList.java:338)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.farmivn.presentation.DaggerFarmiApplicationComponent.getMapOfClassOfAndProviderOfFactoryOf(DaggerFarmiApplicationComponent.java:813)
        at com.farmivn.presentation.DaggerFarmiApplicationComponent.getDispatchingAndroidInjectorOfActivity(DaggerFarmiApplicationComponent.java:838)
        at com.farmivn.presentation.DaggerFarmiApplicationComponent.injectFarmiApplication(DaggerFarmiApplicationComponent.java:1322)
        at com.farmivn.presentation.DaggerFarmiApplicationComponent.inject(DaggerFarmiApplicationComponent.java:1313)
        at com.farmivn.presentation.DaggerFarmiApplicationComponent.inject(DaggerFarmiApplicationComponent.java:501)
        at com.farmivn.presentation.FarmiApplication.onCreate(FarmiApplication.kt:130)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

But it run normal with release build.
In my gradle files:
```
implementation 'com.google.dagger:dagger-android:2.14.1'
implementation 'com.google.dagger:dagger-android-support:2.14.1'
compileOnly 'org.glassfish:javax.annotation:10.0-b28'
kapt 'com.google.dagger:dagger-compiler:2.14'
```

Could you please help me check it?
Thank you

**Comment by ronshapiro** [comment]
This is more likely to be an issue with the OEM or your build system.

FWIW, you should use:

```diff
-kapt 'com.google.dagger:dagger-compiler:2.14'
+kapt 'com.google.dagger:dagger-compiler:2.14.1'
```

There was a bug in the 2.14 compiler artifact.
