### ISSUE TITLE
Dagger doesn't handle missing module types properly in eclipse JDT

### ISSUE THREAD

**Issue by facboy** [google/dagger#1114]
Dagger does not correctly detect missing module types when running in the eclipse JDT compiler. The correct behaviour is to throw a `TypeNotPresentException` and retry on the next round, but because eclipse's behaviour is slightly different to javac, Dagger fails with a `NoSuchElementException` and bombs the whole compile.

**Comment by ronshapiro** [comment]
Can you provide a stack trace, and a sample project as well?

**Comment by facboy** [comment]
https://github.com/facboy/dagger-1114

```
java.lang.Exception: java.util.NoSuchElementException: No value present
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:933)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:443)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:187)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at dagger.internal.codegen.SubcomponentDeclaration$Factory.forModule(SubcomponentDeclaration.java:68)
	at dagger.internal.codegen.ModuleDescriptor$Factory.create(ModuleDescriptor.java:196)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at dagger.internal.codegen.ModuleDescriptor$Factory.collectIncludedModules(ModuleDescriptor.java:219)
	at dagger.internal.codegen.ModuleDescriptor$Factory.create(ModuleDescriptor.java:193)
	at dagger.internal.codegen.ComponentDescriptor$Factory.create(ComponentDescriptor.java:496)
	at dagger.internal.codegen.ComponentDescriptor$Factory.forComponent(ComponentDescriptor.java:465)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:142)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:53)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	... 24 more
```

**Comment by ronshapiro** [comment]
We now do much more aggressive checking for missing types, and defer to later rounds accordingly. I'm going to mark this closed, and we can reopen it if it persists.

**Comment by mr-gil** [comment]
This is happening again when you add some incompatible project with androidx
