### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by akingyin1987** [google/dagger#1187]
aused by: java.lang.NullPointerException
        at dagger.internal.codegen.ComponentProcessor.getSupportedOptions(ComponentProcessor.java:94)
        at org.gradle.api.internal.tasks.compile.IncrementalAnnotationProcessingCompileTask.getProcessorType(IncrementalAnnotationProcessingCompileTask.java:102)
        at org.gradle.api.internal.tasks.compile.IncrementalAnnotationProcessingCompileTask.setupProcessors(IncrementalAnnotationProcessingCompileTask.java:91)
        ... 61 more

**Comment by ronshapiro** [comment]
This isn't enough information to diagnose what you're seeing. Can you add more context please?

**Comment by oehme** [comment]
Yep, that's a bug in 4.8 RC1. I'll fix it for RC2.

**Comment by akingyin1987** [comment]
How should we solve this problem now

**Comment by ronshapiro** [comment]
I'd recommend not using the release candidate versions of Gradle if they
aren't compatible yet.
