### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property dispatchingAndroidInjector has not been initialized

### ISSUE THREAD

**Issue by lby1992** [google/dagger#1237]
Hi

I'm using the `Dagger-android` in my project. 
When I run my app, then the splash activity try to inject itself by calling `AndroidInjection.inject(activity)`, an error occurs, below is the exception message:
```
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property dispatchingAndroidInjector has not been initialized
        at com.dennis.baseprojectandroid.application.AndroidApplication.activityInjector(AndroidApplication.kt:30)
        at dagger.android.AndroidInjection.inject(AndroidInjection.java:56)
        at com.dennis.baseprojectandroid.core.injection.app.AppInjector.handleActivityCreated(AppInjector.kt:48)
        at com.dennis.baseprojectandroid.core.injection.app.AppInjector.access$handleActivityCreated(AppInjector.kt:14)
        at com.dennis.baseprojectandroid.core.injection.app.AppInjector$init$1.onActivityCreated(AppInjector.kt:41)
        at android.app.Application.dispatchActivityCreated(Application.java:197)
        at android.app.Activity.onCreate(Activity.java:1015)
        at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:321)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
        at com.dennis.baseprojectandroid.ui.splash.SplashActivity.onCreate(SplashActivity.kt:20)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

The application code:
```
class AndroidApplication : Application(), HasActivityInjector {
    @Inject
    lateinit var dispatchingAndroidInjector: DispatchingAndroidInjector<Activity>

    override fun onCreate() {
        super.onCreate()

        //Do something while initialing application.
        AppInjector.init(this)
    }

    override fun activityInjector(): AndroidInjector<Activity> = dispatchingAndroidInjector
}
```
The `AppInjector.kt`:
```
object AppInjector {
    fun init(application: AndroidApplication) {
        DaggerAppComponent.builder()
            .application(application)
            .build()
            .inject(application)

        application.registerActivityLifecycleCallbacks(object : Application.ActivityLifecycleCallbacks {
            //other methods

            override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {
                handleActivityCreated(activity)
            }
        })
    }

    private fun handleActivityCreated(activity: Activity) {
        if (activity is HasSupportFragmentInjector || activity is Injectable) {
            AndroidInjection.inject(activity)
        }
        if (activity is FragmentActivity) {
            activity.supportFragmentManager
                .registerFragmentLifecycleCallbacks(
                    object : FragmentManager.FragmentLifecycleCallbacks() {
                        override fun onFragmentCreated(
                            fm: FragmentManager,
                            f: Fragment,
                            savedInstanceState: Bundle?
                        ) {
                            if (f is Injectable) {
                                AndroidSupportInjection.inject(f)
                            }
                        }
                    }, true
                )
        }
    }
}
```

This error occurs with `Dagger 2.16`.

Can someone help me?

**Comment by lby1992** [comment]
Finally I got the reason....

I inject the `Context` type in `AppComponent` , so the `AndroidApplication.dispatchingAndroidInjector` didn't be injected.

```
@Component(modules = [
    AndroidInjectionModule::class,
    SplashActivityModule::class
])
interface AppComponent {
    fun inject(context: Context)

    @Component.Builder
    interface Builder {
        @BindsInstance
        fun application(application: Application): Builder

        fun build(): AppComponent
    }
}
```
