### ISSUE TITLE
StackOverflow at runtime in generated code due to undetected dependency cycle

### ISSUE THREAD

**Issue by pyricau** [google/dagger#1250]
I introduced a dependency cycle by mistake, and instead of getting a compile error I got a runtime stackoverflow.

Version of Dagger: 2.16

Here's the stacktrace:

```
     at com.squareup.ui.main.CommonRedirectPipelineDecorator_Factory.provideInstance(CommonRedirectPipelineDecorator_Factory.java:62)
     at com.squareup.ui.main.CommonRedirectPipelineDecorator_Factory.get(CommonRedirectPipelineDecorator_Factory.java:44)
     at com.squareup.ui.main.CommonRedirectPipelineDecorator_Factory.get(CommonRedirectPipelineDecorator_Factory.java:13)
     at com.squareup.ui.main.MainActivityContainer_Factory.provideInstance(MainActivityContainer_Factory.java:536)
     at com.squareup.ui.main.MainActivityContainer_Factory.get(MainActivityContainer_Factory.java:337)
     at com.squareup.ui.main.MainActivityContainer_Factory.get(MainActivityContainer_Factory.java:65)
     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
     at com.squareup.ui.main.CommonMainActivityModule_ProvidePosContainerRunnerFactory.provideInstance(CommonMainActivityModule_ProvidePosContainerRunnerFactory.java:27)
     at com.squareup.ui.main.CommonMainActivityModule_ProvidePosContainerRunnerFactory.get(CommonMainActivityModule_ProvidePosContainerRunnerFactory.java:23)
     at com.squareup.ui.main.CommonMainActivityModule_ProvidePosContainerRunnerFactory.get(CommonMainActivityModule_ProvidePosContainerRunnerFactory.java:8)
     at dagger.internal.DelegateFactory.get(DelegateFactory.java:34)
     at com.squareup.applet.AppletsDrawerPresenter_Factory.provideInstance(AppletsDrawerPresenter_Factory.java:64)
     at com.squareup.applet.AppletsDrawerPresenter_Factory.get(AppletsDrawerPresenter_Factory.java:45)
     at com.squareup.applet.AppletsDrawerPresenter_Factory.get(AppletsDrawerPresenter_Factory.java:11)
     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
     at com.squareup.register.tutorial.TutorialPresenter_Factory.provideInstance(TutorialPresenter_Factory.java:60)
     at com.squareup.register.tutorial.TutorialPresenter_Factory.get(TutorialPresenter_Factory.java:43)
     at com.squareup.register.tutorial.TutorialPresenter_Factory.get(TutorialPresenter_Factory.java:13)
     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
     at com.squareup.ui.tour.WhatsNewUi_Factory.provideInstance(WhatsNewUi_Factory.java:67)
     at com.squareup.ui.tour.WhatsNewUi_Factory.get(WhatsNewUi_Factory.java:47)
     at com.squareup.ui.tour.WhatsNewUi_Factory.get(WhatsNewUi_Factory.java:12)
     at com.squareup.ui.main.CommonRedirectPipelineDecorator_Factory.provideInstance(CommonRedirectPipelineDecorator_Factory.java:62)
     at com.squareup.ui.main.CommonRedirectPipelineDecorator_Factory.get(CommonRedirectPipelineDecorator_Factory.java:44)
     at com.squareup.ui.main.CommonRedirectPipelineDecorator_Factory.get(CommonRedirectPipelineDecorator_Factory.java:13)
     at com.squareup.ui.main.MainActivityContainer_Factory.get(MainActivityContainer_Factory.java:65)
```

Working from bottom to top:

* MainActivityContainer: Inject constructor injects a RedirectPipelineDecorator
* A module binds RedirectPipelineDecorator to CommonRedirectPipelineDecorator
* CommonRedirectPipelineDecorator: Inject constructor injects a WhatsNewUi
* WhatsNewUi: Inject constructor injects a TutorialPresenter
* TutorialPresenter: Inject constructor injects a AppletsDrawerPresenter
* AppletsDrawerPresenter: Inject constructor injects a PosContainer
* CommonMainActivityModule has a provides method that takes a MainActivityContainer and returns a PosContainer 
* => cycle, not detected at compile time.

These bindings belong to a subcomponent.

**Comment by netdpb** [comment]
Are any of these dependencies requested as a `Provider`?
Are all the modules installed into the same subcomponent?

**Comment by pyricau** [comment]
@netdpb No providers. The bottom part of the ticket should help recreate an example.

**Comment by pyricau** [comment]
The chain of dependencies is essentially: 

@Inject => @Binds => @Inject => @Inject => @Inject => @Inject => @Provides  => back to initial @Inject

**Comment by ronshapiro** [comment]
And no lazies? I do see a DoubleCheck in there

**Comment by pyricau** [comment]
A bunch of those singletons, but no lazy no. In fact, we added a lazy to solve this :)

**Comment by ronshapiro** [comment]
Is the cycle detected in 2.15? Or in 2.17?

**Comment by pyricau** [comment]
Trying to repro with 2.17, which is proving hard because updating throws a lot of errors at me.

**Comment by pyricau** [comment]
Can confirm I can't repro this with 2.17
