### ISSUE TITLE
Dagger not finding an Autofactory generated class after updating to 2.18

### ISSUE THREAD

**Issue by benkay** [google/dagger#1311]
I’m running into a strange thing trying to update from Dagger 2.16 to 2.17/18
Dagger fails, complaining an AutoFactory generated class isn’t present.

If I copy the AutoFactory generated implementation into my code and remove the `@AutoFactory` annotation, then everything compiles fine. I haven't found anything that's obviously different about this class, and I haven't been able to reproduce it yet. There are three other AutoFactory classes in the same package which work fine once this one is removed.
The Factory class does seem to be generated too, just Dagger doesn’t see it.

The relevant bit of the stack trace when building with 2.18 is
```
Caused by: java.lang.TypeNotPresentException: Type MyClassFactory not present
    at dagger.internal.codegen.DaggerTypes$1.visitError(DaggerTypes.java:181)§
    at dagger.internal.codegen.DaggerTypes$1.visitError(DaggerTypes.java:167)
    at com.sun.tools.javac.code.Type$ErrorType.accept(Type.java:1855)
    at dagger.internal.codegen.DaggerTypes.checkTypePresent(DaggerTypes.java:164)
    at dagger.internal.codegen.RequestKinds.getRequestKind(RequestKinds.java:105)
    at dagger.internal.codegen.DependencyRequestValidator.validateDependencyRequest(DependencyRequestValidator.java:59)
    at dagger.internal.codegen.ComponentValidator.lambda$validate$1(ComponentValidator.java:214)
    at dagger.internal.codegen.ComponentValidator.validate(ComponentValidator.java:167)
    at dagger.internal.codegen.ComponentProcessingStep.processSubcomponents(ComponentProcessingStep.java:210)
    at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:121)
    at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:45)
    at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
    at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
    at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
    at org.gradle.api.internal.tasks.compile.processing.DynamicProcessor.process(DynamicProcessor.java:51)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1039)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1180)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
    at com.sun.tools.javac.main.Main.compile(Main.java:523)
    ... 63 more
```

**Comment by winstonvk** [comment]
Bump
I have the same problem

**Comment by ronshapiro** [comment]
I think the change that broke this was da2e1f0255d3b9c9c9fde51f5eaf01cb6e7687bb.

I think we need to catch that error more broadly and defer. I'll try to add a fix.

**Comment by bio007** [comment]
I have different callstack but same problem. Using Dagger 2.16 with autofactory 1.0.beta-6. The factory is generated (I can see the file sitting there) but Dagger is complaining abut nonexistent class:

`error.NonExistentClass is injected at ... is injected at ...`

If I comment out `Autofactory` annotation and copy that file to my source dir everything works.

**Comment by BoD** [comment]
I believe I have the same issue but not 100% sure - is there an easy way to test future releases?  Any beta releases out there?

**Comment by Zhuinden** [comment]
Try this in build.gradle:

```
kapt {
    correctErrorTypes = true // https://github.com/google/dagger/issues/435#issuecomment-441723285
}
```
