### ISSUE TITLE
NoClassDefFoundError: dagger/internal/Factory

### ISSUE THREAD

**Issue by felipecsl** [google/dagger#142]
Just started seeing this today with 2.0-SNAPSHOT. Can't build the project

```
Caused by: java.lang.NoClassDefFoundError: dagger/internal/Factory
	at dagger.internal.codegen.FactoryGenerator.write(FactoryGenerator.java:150)
	at dagger.internal.codegen.FactoryGenerator.write(FactoryGenerator.java:72)
	at dagger.internal.codegen.SourceFileGenerator.generate(SourceFileGenerator.java:53)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:124)
	at com.google.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:228)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)
	... 74 more
Caused by: java.lang.ClassNotFoundException: dagger.internal.Factory
	... 87 more
```

**Comment by artem-zinnatullin** [comment]
@felipecsl may be you are using downloaded .jars?

**Comment by felipecsl** [comment]
Never mind, gradle dependencies got inconsistent for some reason. Another `-refresh-dependencies` worked. Thanks!

**Comment by cgruber** [comment]
Yep - Factory got moved to dagger.internal.

**Comment by cpednekar** [comment]
I'm still getting this error. 

Exception in thread "main" java.lang.NoClassDefFoundError: dagger/internal/Factory
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at DaggerCommandRouterFactory$CommandRouterFactoryImpl.helloWorldCommand(DaggerCommandRouterFactory.java:43)
        at DaggerCommandRouterFactory$CommandRouterFactoryImpl.router(DaggerCommandRouterFactory.java:48)
        at CommandLineAtm.main(CommandLineAtm.java:7)
Caused by: java.lang.ClassNotFoundException: dagger.internal.Factory
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 15 more

I already tried -refresh-dependencies and though it refreshed the dependencies, I still get the error. 
Using following in build.gradle 

implementation 'com.google.dagger:dagger:2.44.2'
annotationProcessor 'com.google.dagger:dagger-compiler:2.44.2'
