### ISSUE TITLE
Recompilation with the maven-compiler-plugin v3.2 results in a compiler exception

### ISSUE THREAD

**Issue by johnbcoughlin** [google/dagger#147]
The exception looks like:

```
An exception has occurred in the compiler (1.8.0_25). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.IllegalStateException: endPosTable already set
    at com.sun.tools.javac.util.DiagnosticSource.setEndPosTable(DiagnosticSource.java:136)
    at com.sun.tools.javac.util.Log.setEndPosTable(Log.java:350)
    at com.sun.tools.javac.main.JavaCompiler.parse(JavaCompiler.java:667)
    at com.sun.tools.javac.main.JavaCompiler.parseFiles(JavaCompiler.java:950)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:892)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:921)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1187)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
```

To reproduce, bump the project `maven-compiler-plugin` version to 3.2, and run 

```
mvn compile -pl examples/simple
!!
```

In practice, this means that the 3.2 plugin version isn't really usable since having to do a clean before every recompilation is unacceptable.

**Comment by johnbcoughlin** [comment]
Looks like this is known: 
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8062800
https://bugs.openjdk.java.net/browse/JDK-8029145
I didn't realize that which build of `javac` you're using can be relevant, but FWIW, I'm using `build 1.8.0_25-b17`.

**Comment by johnbcoughlin** [comment]
Looks like this was due to a version conflict in the compiler plugin target level.

**Comment by johnbcoughlin** [comment]
Reopening this because it's still happening on the `2.1-SNAPSHOT` release, as well as my main project with `2.0`, which I don't believe has any problem with the compiler plugin.

**Comment by johnbcoughlin** [comment]
All right, it's definitely due to version 3.2 of the compiler plugin. I've updated the initial comment and issue name.

**Comment by tbroyer** [comment]
Might be related to https://jira.codehaus.org/browse/MCOMPILER-235 (which triggers a bug in javac)

**Comment by cgruber** [comment]
Not something we can fix.
