### ISSUE TITLE
IncompatibleClassChangError thrown after upgrade from 2.21 to 2.22. 

### ISSUE THREAD

**Issue by cgruber** [google/dagger#1491]
Platform: Mac OSX 10.14.3
Compiler: Kotlinc-1.3.21 / Kapt
JVM: jdk1.8.0_162 (yeah yeah)
Builder: Bazel 0.22 (with a back-ported aar_import fix)

After upgrading a bazel-based build from 2.21 to dagger 2.22, the following started occurring.  Dagger upstream deps are automatically handled by the maven integration, though the system uses version-pinning, so it's possible this is merely a dependency versioning problem.  I'm auditing that now, but it seems odd that it would be so, insofar as it's throwing this issue around one class in dagger-2.22.jar artifact (`@Component` and `@Component.Factory`)

Error doesn't seem to happen with gradle, which lends a bit of support to it being a deps issue, as a few of these ICCE throws have been in the past. 

```
Caused by: java.lang.IncompatibleClassChangeError: dagger.Component and dagger.Component$Factory disagree on InnerClasses attribute
	at java.base/java.lang.Class.getDeclaringClass0(Native Method)
	at java.base/java.lang.Class.isTopLevelClass(Unknown Source)
	at java.base/java.lang.Class.getSimpleBinaryName(Unknown Source)
	at java.base/java.lang.Class.getSimpleName(Unknown Source)
	at dagger.internal.codegen.ComponentCreatorAnnotation.<init>(ComponentCreatorAnnotation.java:53)
	at dagger.internal.codegen.ComponentCreatorAnnotation.<clinit>(ComponentCreatorAnnotation.java:38)
	at dagger.internal.codegen.ComponentProcessingStep.annotations(ComponentProcessingStep.java:93)
	at dagger.internal.codegen.DaggerStatisticsCollectingProcessingStep.annotations(DaggerStatisticsCollectingProcessingStep.java:44)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.getSupportedAnnotationClasses(BasicAnnotationProcessor.java:146)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.getSupportedAnnotationTypes(BasicAnnotationProcessor.java:158)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.getSupportedAnnotationTypes(BasicAnnotationProcessor.java:103)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.getSupportedAnnotationTypes(annotationProcessing.kt:132)
```

> Note: This may well not be dagger's problem, but I'm posting it here since the one variable I change is dagger version number, and in case others run into this.

**Comment by ronshapiro** [comment]
What if you use Dagger as a Bazel workspace dependency?

**Comment by menny** [comment]
I see the same issue. Dagger 2.22.1 also fails with the same error.

**Comment by menny** [comment]
With Bazel 0.25.2 on macOS

**Comment by cgruber** [comment]
2.23 has the same issue.

What did you mean by "as a bazel workspace dependency" @ronshapiro ?

**Comment by ronshapiro** [comment]
@cgruber as:

```
http_archive(
  name = "com_google_dagger",
  urls = ['https://github.com/google/dagger/archive/...'])
)

...

deps = ["@com_google_dagger//:dagger_with_compiler"],
````

Could it be that because `@Component.Factory` didn't exist in 2.21, that somewhere on your runtime classpath you are getting a version 2.21 jar even though you're compiling against 2.22+?

**Comment by cgruber** [comment]
Oh.  Maybe. Not sure where from. Maybe from the kotlin rules, in some weird slip. :/

**Comment by cgruber** [comment]
Yeah - there's definitely a version in here poisoning something.  It looks like the kotlin rules.  I'll need to dig in deeper, but it's not dagger's issue, so I'll close this.

**Comment by cgruber** [comment]
Just to close the loop, this is fixed in my fork of the bazel kotlin rules cgruber/rules_kotlin#4 and released in version legacy-modded-0_26_1-01
