### ISSUE TITLE
ClassNotFoundException with Dagger 2.23.2

### ISSUE THREAD

**Issue by tasomaniac** [google/dagger#1546]
I am getting this crash while codegen and could not figure out why this happens. This happened after updating to `2.23.2`

It works as expected with `2.22.1`

We have a pretty standard setup using `ContributesAndroidInjector`

```
Caused by: java.lang.NoClassDefFoundError: dagger/internal/codegen/serialization/BindingRequestProto
        at dagger.internal.codegen.BindingRequest.toProto(BindingRequest.java:116)
        at dagger.internal.codegen.ComponentImplementation.withModifiableBindingMetadata(ComponentImplementation.java:609)
        at dagger.internal.codegen.ComponentImplementation.addModifiableMethod(ComponentImplementation.java:590)
        at dagger.internal.codegen.ComponentImplementation.addModifiableBindingMethod(ComponentImplementation.java:562)
        at dagger.internal.codegen.ModifiableAbstractMethodBindingExpression.addUnimplementedMethod(ModifiableAbstractMethodBindingExpression.java:97)
        at dagger.internal.codegen.ModifiableAbstractMethodBindingExpression.getDependencyExpression(ModifiableAbstractMethodBindingExpression.java:84)
        at dagger.internal.codegen.ComponentBindingExpressions.getDependencyExpression(ComponentBindingExpressions.java:127)
        at dagger.internal.codegen.ComponentBindingExpressions.getDependencyArgumentExpression(ComponentBindingExpressions.java:186)
        at dagger.internal.codegen.SimpleMethodBindingExpression.dependencyArgument(SimpleMethodBindingExpression.java:154)
        at dagger.internal.codegen.SimpleMethodBindingExpression.lambda$getDependencyExpression$0(SimpleMethodBindingExpression.java:90)
        at com.google.common.collect.Maps$3.transform(Maps.java:960)
        at com.google.common.collect.Maps$3.transform(Maps.java:957)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at com.google.common.collect.Iterables.toArray(Iterables.java:285)
        at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:451)
        at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:436)
        at dagger.internal.codegen.SimpleMethodBindingExpression.getDependencyExpression(SimpleMethodBindingExpression.java:87)
        at dagger.internal.codegen.MethodBindingExpression.methodBody(MethodBindingExpression.java:138)
        at dagger.internal.codegen.ModifiableConcreteMethodBindingExpression.addMethod(ModifiableConcreteMethodBindingExpression.java:84)
        at dagger.internal.codegen.MethodBindingExpression.getDependencyExpression(MethodBindingExpression.java:82)
        at dagger.internal.codegen.ComponentBindingExpressions.getDependencyExpression(ComponentBindingExpressions.java:127)
        at dagger.internal.codegen.ComponentBindingExpressions.getDependencyArgumentExpression(ComponentBindingExpressions.java:186)
        at dagger.internal.codegen.MembersInjectionMethods.lambda$membersInjectionMethod$0(MembersInjectionMethods.java:108)
        at dagger.internal.codegen.InjectionMethods$InjectionSiteMethod.invoke(InjectionMethods.java:332)
        at dagger.internal.codegen.InjectionMethods$InjectionSiteMethod.lambda$invokeAll$0(InjectionMethods.java:304)
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$forEachRemaining$1(CollectSpliterators.java:64)
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:64)
        at dagger.internal.codegen.InjectionMethods$InjectionSiteMethod.invokeAll(InjectionMethods.java:311)
        at dagger.internal.codegen.MembersInjectionMethods.membersInjectionMethod(MembersInjectionMethods.java:100)
        at dagger.internal.codegen.Util.reentrantComputeIfAbsent(Util.java:93)
        at dagger.internal.codegen.MembersInjectionMethods.getOrCreate(MembersInjectionMethods.java:70)
        at dagger.internal.codegen.MembersInjectionBindingExpression.membersInjectionInvocation(MembersInjectionBindingExpression.java:69)
        at dagger.internal.codegen.MembersInjectionBindingExpression.getComponentMethodImplementation(MembersInjectionBindingExpression.java:63)
        at dagger.internal.codegen.ComponentBindingExpressions.getComponentMethod(ComponentBindingExpressions.java:226)
        at dagger.internal.codegen.ComponentImplementationBuilder.addInterfaceMethods(ComponentImplementationBuilder.java:196)
        at dagger.internal.codegen.ComponentImplementationBuilder$SubcomponentImplementationBuilder.addInterfaceMethods(ComponentImplementationBuilder.java:787)
        at dagger.internal.codegen.ComponentImplementationBuilder.build(ComponentImplementationBuilder.java:143)
        at dagger.internal.codegen.ComponentImplementationFactory.createComponentImplementationUncached(ComponentImplementationFactory.java:106)
        at dagger.internal.codegen.ComponentImplementationFactory.lambda$createComponentImplementation$0(ComponentImplementationFactory.java:76)
        at dagger.internal.codegen.Util.reentrantComputeIfAbsent(Util.java:93)
        at dagger.internal.codegen.ComponentImplementationFactory.createComponentImplementation(ComponentImplementationFactory.java:73)
        at dagger.internal.codegen.ComponentGenerator.write(ComponentGenerator.java:67)
        at dagger.internal.codegen.ComponentGenerator.write(ComponentGenerator.java:36)
        at dagger.internal.codegen.SourceFileGenerator.generate(SourceFileGenerator.java:78)
        at dagger.internal.codegen.SourceFileGenerator.generate(SourceFileGenerator.java:69)
        at dagger.internal.codegen.ComponentProcessingStep.generateComponent(ComponentProcessingStep.java:170)
        at dagger.internal.codegen.ComponentProcessingStep.processSubcomponent(ComponentProcessingStep.java:164)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:125)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:50)
        at dagger.internal.codegen.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:51)
        at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
        at dagger.internal.codegen.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:48)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:115)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:50)
        at dagger.internal.codegen.DaggerStatisticsCollectingProcessingStep.process(DaggerStatisticsCollectingProcessingStep.java:52)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:132)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
        at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:80)
        ... 24 more
Caused by: java.lang.ClassNotFoundException: dagger.internal.codegen.serialization.BindingRequestProto
```

**Comment by ronshapiro** [comment]
I'm not sure why that wasn't packaged correctly, but either way, that usage
seems to imply that you're using experimentalAheadOfTimeSubcomponents,
which we removed as it didn't improve build times as much as predicted. I
recommend removing that flag and you should sidestep this issue. That class
isn't used in the regular codepath

בתאריך יום ב׳, 8 ביולי 2019, 2:39, מאת Said Tahsin Dane ‏<
notifications@github.com>:

**Comment by tasomaniac** [comment]
Thanks for the reply. We actually had that flag.

I can confirm that the issue is gone when the flag is removed.
