### ISSUE TITLE
Kapt with Worker API throws NPE

### ISSUE THREAD

**Issue by benjaminRomano** [google/dagger#1568]
Dagger version: 2.2.2
Gradle: 5.5
Kotlin: 1.3.40

We recently added the following kotlin flags to our `gradle.properties` file:
```
kapt.include.compile.classpath=false
kapt.use.worker.api=true
```

and now we see the following error message intermittently:
```
Caused by: java.lang.reflect.InvocationTargetException
	at org.jetbrains.kotlin.gradle.internal.KaptExecution.run(KaptWithoutKotlincTask.kt:146)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:58)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:51)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:107)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:101)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	... 3 more
Caused by: org.jetbrains.kotlin.kapt3.base.util.KaptBaseError: Exception while annotation processing
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:85)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:36)
	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)
	... 22 more
Caused by: java.lang.NullPointerException
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:241)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:230)
	at dagger.internal.codegen.SpiModule.lambda$externalPlugins$0(SpiModule.java:46)
	at dagger.internal.codegen.SpiModule.externalPlugins(SpiModule.java:44)
	at dagger.internal.codegen.SpiModule_ExternalPluginsFactory.get(SpiModule_ExternalPluginsFactory.java:27)
	at dagger.internal.codegen.SpiModule_ExternalPluginsFactory.get(SpiModule_ExternalPluginsFactory.java:11)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at dagger.internal.codegen.BindingGraphValidator_Factory.get(BindingGraphValidator_Factory.java:34)
	at dagger.internal.codegen.BindingGraphValidator_Factory.get(BindingGraphValidator_Factory.java:10)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at dagger.internal.codegen.ModuleValidator_Factory.get(ModuleValidator_Factory.java:61)
	at dagger.internal.codegen.ModuleValidator_Factory.get(ModuleValidator_Factory.java:7)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at dagger.internal.codegen.DaggerComponentProcessor_ProcessorComponent.getModuleProcessingStep(DaggerComponentProcessor_ProcessorComponent.java:384)
	at dagger.internal.codegen.DaggerComponentProcessor_ProcessorComponent.getImmutableListOfProcessingStep(DaggerComponentProcessor_ProcessorComponent.java:505)
	at dagger.internal.codegen.DaggerComponentProcessor_ProcessorComponent.injectComponentProcessor(DaggerComponentProcessor_ProcessorComponent.java:810)
	at dagger.internal.codegen.DaggerComponentProcessor_ProcessorComponent.inject(DaggerComponentProcessor_ProcessorComponent.java:798)
	at dagger.internal.codegen.ComponentProcessor.initSteps(ComponentProcessor.java:109)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.init(BasicAnnotationProcessor.java:118)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.init(incrementalProcessors.kt:33)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.init(annotationProcessing.kt:141)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:80)
	... 24 more
```

**Comment by Chang-Eric** [comment]
Apologies for missing this this whole time. I'm going to close this out since it has been so long and I don't imagine you still have a repro of this, but if you do please do respond back and we can reopen.

FWIW, the stack trace seems like we're trying to load an external SPI plugin but getting null back. This seems pretty strange since from a quick glance at the ServiceLoader code I don't think that can return null, so we would need to have a repro to dig in deeper.
