### ISSUE TITLE
StackOverflowError at runtime when using a subcomponent builder incorrectly

### ISSUE THREAD

**Issue by eiden** [google/dagger#1653]
Been experimenting a bit with dagger `2.25.2`, and ran into a minor issue when using subcomponents incorrectly. If possible, it would be better to catch this error at compile time.

```
package io.github.eiden.dagger2;

import io.github.eiden.dagger2.DaggerApp_SomeMainComponent;
import dagger.Component;
import dagger.Module;
import dagger.Provides;
import dagger.Subcomponent;

import javax.inject.Inject;

public class App {

    @Component(modules = MainModule.class)
    interface SomeMainComponent {
        SomeClass someClass();
    }

    @Subcomponent
    interface SomeSubComponent {
        SomeDependency someDependency();

        @Subcomponent.Builder
        interface Builder {
            SomeSubComponent build();
        }
    }

    @Module(subcomponents = SomeSubComponent.class)
    static class MainModule {

        @Provides SomeDependency someDependency(SomeSubComponent.Builder builder){
            return builder.build().someDependency();
        }
    }

    static class SomeDependency {}

    static class SomeClass {
        @Inject SomeClass(SomeDependency dependency) {}
    }

    public static void main(String[] args) {
        DaggerApp_SomeMainComponent.builder()
                    .build()
                .someClass();

    }
}
```

Running the code above results in:
```
Exception in thread "main" java.lang.StackOverflowError
	at io.github.eiden.dagger2.DaggerApp_SomeMainComponent$SomeSubComponentImpl.someDependency(DaggerApp_SomeMainComponent.java:69)
	at io.github.eiden.dagger2.App$MainModule.someDependency(App.java:32)
	at io.github.eiden.dagger2.App_MainModule_SomeDependencyFactory.someDependency(App_MainModule_SomeDependencyFactory.java:38)
	at io.github.eiden.dagger2.DaggerApp_SomeMainComponent.getSomeDependency(DaggerApp_SomeMainComponent.java:30)
	at io.github.eiden.dagger2.DaggerApp_SomeMainComponent$SomeSubComponentImpl.someDependency(DaggerApp_SomeMainComponent.java:69)
	at io.github.eiden.dagger2.App$MainModule.someDependency(App.java:32)
[...]
```

**Comment by trevjonez** [comment]
Dagger can only see the graph of the type system and check for cycles there. 

https://jakewharton.com/mechanisms-of-metaprogramming/ explains some of the limitation of source generation via annotation processor. 

Discovering this issue would likely need to be done via a separate static analysis tool.

A custom lint check would probably be one way to accomplish compile time discovery of the issue. https://developer.android.com/studio/write/lint

**Comment by Chang-Eric** [comment]
Agreed with above that this is likely not something we can detect in our validation. Closing this as not possible.
