### ISSUE TITLE
ConcurrentModificationException after updating from 2.24 to 2.25.x

### ISSUE THREAD

**Issue by Bencodes** [google/dagger#1662]
We are currently building using buck.

```
+-------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                           |
| The annotation processor dagger.internal.codegen.ComponentProcessor has crashed.                                                          |
|                                                                                                                                           |
| This is likely a bug in the annotation processor itself, though there may be changes you can make to your code to work around it.         |
| Examine the exception stack trace below and consult the annotation processor's troubleshooting guide.                                     |
|                                                                                                                                           |
| java.util.ConcurrentModificationException                                                                                                 |
|  at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)                                                                        |
|  at dagger.internal.codegen.base.RequestKinds.getRequestKind(RequestKinds.java:114)                                                       |
|  at dagger.internal.codegen.validation.DependencyRequestValidator.validateDependencyRequest(DependencyRequestValidator.java:65)           |
|  at dagger.internal.codegen.validation.BindingMethodValidator$MethodValidator.checkParameter(BindingMethodValidator.java:222)             |
|  at dagger.internal.codegen.validation.ProvidesMethodValidator$Validator.checkParameter(ProvidesMethodValidator.java:77)                  |
|  at dagger.internal.codegen.validation.BindingMethodValidator$MethodValidator.checkParameters(BindingMethodValidator.java:213)            |
|  at dagger.internal.codegen.validation.BindingMethodValidator$MethodValidator.checkAdditionalProperties(BindingMethodValidator.java:148)  |
|  at dagger.internal.codegen.validation.BindingElementValidator$ElementValidator.validate(BindingElementValidator.java:152)                |
|  at dagger.internal.codegen.validation.BindingElementValidator$ElementValidator.access$000(BindingElementValidator.java:136)              |
|  at dagger.internal.codegen.validation.BindingElementValidator.validateUncached(BindingElementValidator.java:85)                          |
|  at dagger.internal.codegen.base.Util.reentrantComputeIfAbsent(Util.java:33)                                                              |
|  at dagger.internal.codegen.validation.BindingElementValidator.validate(BindingElementValidator.java:81)                                  |
|  at dagger.internal.codegen.validation.AnyBindingMethodValidator.validateUncached(AnyBindingMethodValidator.java:99)                      |
|  at dagger.internal.codegen.base.Util.reentrantComputeIfAbsent(Util.java:33)                                                              |
|  at dagger.internal.codegen.validation.AnyBindingMethodValidator.validate(AnyBindingMethodValidator.java:74)                              |
|  at dagger.internal.codegen.validation.ModuleValidator.validateUncached(ModuleValidator.java:196)                                         |
|  at dagger.internal.codegen.validation.ModuleValidator.lambda$validate$0(ModuleValidator.java:176)                                        |
|  at dagger.internal.codegen.base.Util.reentrantComputeIfAbsent(Util.java:33)                                                              |
|  at dagger.internal.codegen.validation.ModuleValidator.validate(ModuleValidator.java:176)                                                 |
|  at dagger.internal.codegen.validation.ModuleValidator.validate(ModuleValidator.java:170)                                                 |
|  at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:109)                                                   |
|  at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:58)                                                    |
|  at dagger.internal.codegen.validation.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:51)                    |
|  at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)                                                   |
|  at dagger.internal.codegen.validation.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:48)                             |
|  at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:100)                                                   |
|  at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:58)                                                    |
|  at dagger.internal.codegen.statistics.DaggerStatisticsCollectingProcessingStep.process(DaggerStatisticsCollectingProcessingStep.java:52) |
|  at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)                                         |
|  at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)                                         |
|                                                                                                                                           |
+-------------------------------------------------------------------------------------------------------------------------------------------+
```

cc: @artem-zinnatullin

**Comment by artem-zinnatullin** [comment]
Yeah, my suspicion is that this commit "Improvements to Dagger build time." https://github.com/google/dagger/commit/5c34d6d7059072289c1f816c605eeb657aa9338b#diff-03c011e80c342dbec7d0ed54d6213d92R55 causes `static` state to be shared between different compilation units in shared classloader environments

I'll need to verify if Buck classloads Dagger once in our setup, if so — Dagger prob shouldn't store state `static`ally but rather find a way to keep state for given compilation environment

cc @tagakov if you have bandwidth to debug Dagger to check if we're reusing same instance between different compilation units

**Comment by Tagakov** [comment]
Looks like you are right. Minimal code to reproduce behavior:
```kotlin
private val cached = AtomicBoolean()

class P : AbstractProcessor() {
    override fun getSupportedAnnotationTypes() = setOf("java.lang.Override")
    override fun getSupportedSourceVersion() = SourceVersion.latestSupported()
    override fun process(annotations: Set<TypeElement>, roundEnv: RoundEnvironment): Boolean {
        if (!cached.compareAndSet(false, true)) throw RuntimeException("Already set!")
        return true
    }
}
```

**Comment by artem-zinnatullin** [comment]
Welp

As @Tagakov noted offline:

>It's unclear why Dagger decided to use `static` if they use Dagger in Dagger internally and it has scopes and stuff

In other words: You Were The Chosen One!
![image](https://user-images.githubusercontent.com/967132/68260787-df989c80-fff2-11e9-97cc-a96459577598.png)

**Comment by Tagakov** [comment]
lol :D

I didn't know that it is a utility class, I think it is ok to have a static cache for calculations like this. The first ad-hoc solution which comes in mind is to replace `HashMap` by something supporting concurrency.
