### ISSUE TITLE
Kapt build fails with NoSuchElementException: No value present after updating 2.24 to 2.25.2

### ISSUE THREAD

**Issue by Nimrodda** [google/dagger#1666]
We're getting the following error:

```
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)
```
Stacktrace:

```
Caused by: java.util.NoSuchElementException: No value present
        at dagger.internal.codegen.bindinggraphvalidation.IncompatiblyScopedBindingsValidator.lambda$visitGraph$1(IncompatiblyScopedBindingsValidator.java:74)
        at dagger.internal.codegen.bindinggraphvalidation.IncompatiblyScopedBindingsValidator.visitGraph(IncompatiblyScopedBindingsValidator.java:71)
        at dagger.internal.codegen.validation.BindingGraphValidator.runPlugins(BindingGraphValidator.java:101)
        at dagger.internal.codegen.validation.BindingGraphValidator.validate(BindingGraphValidator.java:78)
        at dagger.internal.codegen.validation.BindingGraphValidator.isValid(BindingGraphValidator.java:65)
        at dagger.internal.codegen.ComponentProcessingStep.isValid(ComponentProcessingStep.java:254)
        at dagger.internal.codegen.ComponentProcessingStep.processRootComponent(ComponentProcessingStep.java:151)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:131)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:62)
        at dagger.internal.codegen.validation.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:51)
        at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
        at dagger.internal.codegen.validation.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:48)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:124)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:62)
        at dagger.internal.codegen.statistics.DaggerStatisticsCollectingProcessingStep.process(DaggerStatisticsCollectingProcessingStep.java:52)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
```

Is it related to scopes? If yes, how can I see the actual error?

**Comment by danysantiago** [comment]
`IncompatiblyScopedBindingsValidator` missing scope annotation in a component when the component also has a binding (like a `@Provides) that has a scope. But it shouldn't be crashing like that of course. Can please share us a minimal example to reproduce?

**Comment by Nimrodda** [comment]
We have hundreds of Dagger modules in the project. It will be really hard to find such component. Is there a way to get Dagger to print which component has the error?

About example to reproduce, I honestly have no idea what is the problem right now so I can't provide an repro steps nor example at this stage.

**Comment by tolstovdmit** [comment]
Hi, there. I had the same error. But I managed to get rid of it.

To reproduce my case:

```
@Singleton
@Component(modules = [
    AndroidInjectionModule::class
    , AppProvidersModule::class
    , ActivityModule::class
    , FragmentModule::class // $1
])
interface AppComponent : AndroidInjector<MyApp> {
    @Component.Factory
    interface Factory {
        fun create(@BindsInstance context: Context): AppComponent
    }
}
```

```
@Module
abstract class ActivityModule {
    @ActivityScope
    @ContributesAndroidInjector(modules = [FragmentModule::class])
    abstract fun contributeMainActivityInjector(): MainActivity
}
```

```
@Module
abstract class FragmentModule {
    @FragmentScope
    @ContributesAndroidInjector(modules = [FragmentProviderModule::class])
    abstract fun contributeFeedFragmentInjector(): FeedFragment
}
```

```
@Module
object FragmentProviderModule {
    @FragmentScope // $2
    @Provides
    fun provideImageLoader(): ImageLoader { //Class that used in adapter injected in fragment
        return GlideImageLoader()
    }
}
```

So, in my case I included FragmentModule in @ContributesAndroidInjector of ActivityModule and in AppComponent.
If you erase $2 it should compile but two Subcomponents will be generated.
If you erase $1 it should work fine.

Not sure if it's a bug.
Hope it can help.
