### ISSUE TITLE
IllegalArgumentException: @kotlin.Metadata does not define an element pn()

### ISSUE THREAD

**Issue by NickFirmani** [google/dagger#1693]
When running with what appears to be Kotlin 1.1 (accidentally) and Dagger 2.25.2, I encountered a strange exception during one of our builds - it looks like the `packageName`, `extraInt` and `extraString` fields of the Metadata header were missing, causing an exception.

Here's the full stack trace
```
Caused by: java.lang.IllegalArgumentException: @kotlin.Metadata does not define an element pn()
	at dagger.shaded.auto.common.AnnotationMirrors.getAnnotationElementAndValue(AnnotationMirrors.java:134)
	at dagger.shaded.auto.common.AnnotationMirrors.getAnnotationValue(AnnotationMirrors.java:114)
	at dagger.internal.codegen.kotlin.KotlinMetadataFactory.getStringValue(KotlinMetadataFactory.java:98)
	at dagger.internal.codegen.kotlin.KotlinMetadataFactory.kmClassOf(KotlinMetadataFactory.java:77)
	at dagger.internal.codegen.kotlin.KotlinMetadataFactory.lambda$create$1(KotlinMetadataFactory.java:61)
	at dagger.internal.codegen.kotlin.KotlinMetadataFactory.create(KotlinMetadataFactory.java:58)
	at dagger.internal.codegen.kotlin.KotlinMetadataUtil.isObjectClass(KotlinMetadataUtil.java:67)
	at dagger.internal.codegen.binding.BindingFactory.setMethodBindingProperties(BindingFactory.java:221)
	at dagger.internal.codegen.binding.BindingFactory.providesMethodBinding(BindingFactory.java:167)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:114)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:58)
	at dagger.internal.codegen.validation.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:51)
	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:65)
	at dagger.internal.codegen.validation.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:48)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:100)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:58)
	at dagger.internal.codegen.statistics.DaggerStatisticsCollectingProcessingStep.process(DaggerStatisticsCollectingProcessingStep.java:52)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:132)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:80)
```

The module that caused this to fail was pretty trivial as well
```
@Module
class FooModule {
  @Singleton
  @Provides
  fun provideFoo(impl: FooImpl): Foo= impl
}
```

Adding an explicit dependency on our actual version of kotlin (1.3.41) in the problematic module resolved this. 

I couldn't reproduce this in a clean sample project/don't think this is a big issue, but I figured I'd file the issue here in case this is a high priority or others have run into it.

**Comment by danysantiago** [comment]
Thanks for reporting this, Dagger doesn't support Kotlin versions below 1.0, but we should handle 1.1 and be more graceful about later added optional data fields.
