### ISSUE TITLE
Weird ConcurrentModificationException issue while starting activity

### ISSUE THREAD

**Issue by Sdghasemi** [google/dagger#1957]
We've been facing a weird `ConcurrentModificationException` for a while now. Currently using v2.28 but it was also present in v2.27. It's not related to Android version since it's happening on every single version from 4 to 10. I don't know if it's a bad implementation issue or related to the library itself but it appeared right after we used dagger for dependency injection.

The stacktrace printed in Firebase Crashlytics is as follows:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mnhaami.pasaj/com.mnhaami.pasaj.component.activity.main.MainActivity}: java.util.ConcurrentModificationException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2789)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2872)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4727)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6543)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
Caused by java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
       at java.util.HashMap$ValueIterator.next(HashMap.java:1470)
       at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2470)
       at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:274)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1173)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1502)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2563)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
       at dagger.android.support.DaggerAppCompatActivity.onCreate(DaggerAppCompatActivity.java:53)
       at com.mnhaami.pasaj.component.activity.BaseActivity.onCreate(BaseActivity.java:113)
       at com.mnhaami.pasaj.component.activity.main.MainActivity.onCreate(MainActivity.java:549)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2742)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2872)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4727)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6543)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```
I could not pinpoint the root cause of the problem but I can say it does not happen in a specific activity or fragment for sure. More like a circumstantial issue as the nature of the exception is.
Also it might help noting that we're using dagger-android with multibinding.
Let me know if more info is needed to track down the issue. Thanks in advance.

**Comment by Chang-Eric** [comment]
Given where the exception is coming from (FragmentManager.restoreSaveState), this doesn't look like a Dagger issue. Sorry, maybe ask StackOverflow?
