### ISSUE TITLE
Error about not adding HiltAndroidRule even though I added HiltAndroidRule

### ISSUE THREAD

**Issue by takahirom** [google/dagger#1964]
* What went wrong

The following error is displayed even though HiltAndroidRule is added to the rule.

```
java.lang.IllegalStateException: The component was not created. Check that you have added the HiltAndroidRule.

	at dagger.hilt.internal.Preconditions.checkState(Preconditions.java:83)
	at dagger.hilt.android.internal.testing.TestApplicationComponentManager.generatedComponent(TestApplicationComponentManager.java:79)
	at com.github.takahirom.hilt_robolectric_custom_application.HiltTestApplication_Application.generatedComponent(HiltTestApplication_Application.java:28)
	at dagger.hilt.EntryPoints.get(EntryPoints.java:46)
	at dagger.hilt.android.EntryPointAccessors.fromApplication(EntryPointAccessors.java:36)
	at com.github.takahirom.hilt_robolectric_custom_application.BaseApp.onCreate(App.kt:33)
	at org.robolectric.android.internal.AndroidEnvironment.lambda$installAndCreateApplication$0(AndroidEnvironment.java:253)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidEnvironment.installAndCreateApplication(AndroidEnvironment.java:253)
	at org.robolectric.android.internal.AndroidEnvironment.setUpApplicationState(AndroidEnvironment.java:149)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:298)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:247)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Sample code
https://github.com/takahirom/hilt-robolectric-custom-application

code snippets

```

hilt {
    enableTransformForLocalTests = true
}

dependencies {
...

    implementation('com.google.dagger:hilt-android:2.28-alpha')
    kapt 'com.google.dagger:hilt-android-compiler:2.28-alpha'

    implementation('androidx.hilt:hilt-common:1.0.0-alpha01')
    implementation('androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha01') 
    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha01'

    testImplementation 'com.google.dagger:hilt-android-testing:2.28-alpha'
    kaptTest 'com.google.dagger:hilt-android-compiler:2.28-alpha'
    kaptAndroidTest 'com.google.dagger:hilt-android-compiler:2.28-alpha'

    testImplementation "org.robolectric:robolectric:4.2.1"
}
```

```kotlin
@CustomTestApplication(BaseApp::class)
interface HiltTestApplication

@HiltAndroidTest
@RunWith(RobolectricTestRunner::class)
@Config(
    application = HiltTestApplication_Application::class,
    manifest = "src/main/AndroidManifest.xml"
)
class ExampleUnitTest {
    @get:Rule
    val hiltAndroidRule = HiltAndroidRule(this)

    @Test
    fun addition_isCorrect() {
        assertEquals(4, 2 + 2)
    }
}
```

```kotlin
@Subcomponent
interface MySubcomponent {
    @Subcomponent.Factory
    interface DaggerFactory {
        fun create(): MySubcomponent
    }
}

@HiltAndroidApp
class App : BaseApp()

open class BaseApp : Application() {
    @InstallIn(ApplicationComponent::class)
    @EntryPoint
    interface AppEntryPoint {
        fun appComponentFactory(): MySubcomponent.DaggerFactory
    }
    lateinit var mySubcomponent :MySubcomponent

    override fun onCreate() {
        super.onCreate()
        val entryPoint = EntryPointAccessors.fromApplication(applicationContext,
            AppEntryPoint::class.java)
        mySubcomponent = entryPoint.appComponentFactory().create()
    }
}

```

**Comment by bcorso** [comment]
Hi Takahiro,

The issue is that the `BaseApp` is trying to access an entry point in `onCreate()`, which for tests happens before the test instance is created, and thus before any of the test rules have been instantiated.

We touch a bit about this in the docs, [here](https://dagger.dev/hilt/testing#best-practices) (see the last paragraph).

One idea is to make the entry point lazy. Sorry, my Kotlin skills aren't great but something like this might work:

```kotlin
open class BaseApp : Application() {
    @InstallIn(ApplicationComponent::class)
    @EntryPoint
    interface AppEntryPoint {
        fun appComponentFactory(): MySubcomponent.DaggerFactory
    }

    val mySubcomponent :MySubcomponent by lazy {
        val entryPoint = EntryPointAccessors.fromApplication(applicationContext,
            AppEntryPoint::class.java)
        entryPoint.appComponentFactory().create()
    }
}
```

**Comment by takahirom** [comment]
Hi Brad,
Thank you.  I didn't see that part.  I'll try something different.
