### ISSUE TITLE
error: [Hilt]   null value in entry: dagger.hilt.android.components.ServiceComponent=null: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Computr0n** [google/dagger#2037]
```
> Task :app:otc:kaptDebugKotlin
error: [Hilt]
  null value in entry: dagger.hilt.android.components.ServiceComponent=null: java.lang.NullPointerException: null value in entry: dagger.hilt.android.components.ServiceComponent=null
  	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
  	at com.google.common.collect.ImmutableMultimap$Builder.put(ImmutableMultimap.java:161)
  	at com.google.common.collect.ImmutableSetMultimap$Builder.put(ImmutableSetMultimap.java:262)
  	at dagger.hilt.processor.internal.aggregateddeps.ComponentDependencies$Dependencies$Builder.addDep(ComponentDependencies.java:87)
  	at dagger.hilt.processor.internal.aggregateddeps.ComponentDependencies.from(ComponentDependencies.java:209)
  	at dagger.hilt.processor.internal.root.RootProcessor.postRoundProcess(RootProcessor.java:137)
  	at dagger.hilt.processor.internal.BaseProcessor.process(BaseProcessor.java:190)
  	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
  	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:161)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
  	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:78)
[Hilt]

  	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:34)
  	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)
  	at sun.reflect.GeneratedMethodAccessor1181.invoke(Unknown Source)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.jetbrains.kotlin.gradle.internal.KaptExecution.run(KaptWithoutKotlincTask.kt:158)
  	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
  	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
  	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
  	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
  	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
  	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
  	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
  	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
  	at java.lang.Thread.run(Thread.java:748)
  
  [Hilt] Processing did not complete. See error above for details.
> Task :app:otc:kaptDebugKotlin FAILED
```

**Comment by Computr0n** [comment]
I'm not sure what to do to investigate this or what more to add.

My dagger dependencies gradle configs:

```
apply plugin: "kotlin-kapt"
apply plugin: "dagger.hilt.android.plugin"

dependencies {
    kapt "com.google.dagger:hilt-android-compiler:2.28-alpha"
    implementation "com.google.dagger:hilt-android:2.28-alpha"
}

dependencies {
    kapt "androidx.hilt:hilt-compiler:1.0.0-alpha02"
    implementation "androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02"
    implementation "androidx.hilt:hilt-work:1.0.0-alpha02"
}

dependencies {
    // For Robolectric tests.
    testImplementation 'com.google.dagger:hilt-android-testing:2.28-alpha'
    kaptTest 'com.google.dagger:hilt-android-compiler:2.28-alpha'

    // For instrumented tests.
    androidTestImplementation 'com.google.dagger:hilt-android-testing:2.28-alpha'
    kaptAndroidTest 'com.google.dagger:hilt-android-compiler:2.28-alpha'
}

kapt {
    correctErrorTypes true
}

hilt {
    enableTransformForLocalTests = true
}
```

**Comment by bcorso** [comment]
Looks like the error is happening around [ComponentDependencies.java#L203](https://github.com/google/dagger/blob/master/java/dagger/hilt/processor/internal/aggregateddeps/ComponentDependencies.java#L203), probably due to `elements.getTypeElement(dep)` returning null.

In this case `dep` is a class name corresponding to a `@InstallIn(ServiceComponent.class)`-annotated class (either an entry point or a module). The fact that `elements.getTypeElement` returns null means that the class is no longer in the class path. My guess is that this may be an issue of `api` vs `implementation` where you may need to use `api` so that Dagger has access to the given class at compile time.

Have you added any `@InstallIn(ServiceComponent.class)`-annotated classes in your codebase?

**Comment by Computr0n** [comment]
Thanks for the help @bcorso -- I had a big changeset and I undid any part of it that had DI code and the issue went away, but after adding it back piece-by-piece i'm not sure what part caused the change since it wont repro now... if I find out what it was I will reopen this...
