### ISSUE TITLE
Compiler errors on java 11

### ISSUE THREAD

**Issue by auras** [google/dagger#2144]
On Android Studio 4.2, which comes bundled with java 11, the project I'm working on doesn't build anymore.

```
C:\...\app\build\tmp\kapt3\stubs\...\MainApplication.java:60: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public class MainApplication extends com...BaseApplication implements dagger.android.HasAndroidInjector {
       ^C:\...\app\src\main\java\com\...\dependency_injection\ApplicationModule.java:26: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public class ApplicationModule {
       ^C:\Users\...\app\src\main\java\com\...\dependency_injection\AppComponent.java:162: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public interface AppComponent {
       ^
> Task :app:kaptDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)
```

The same project builds successfully with java 8.

Are there projects where dagger 2 works with java 11 already? If so, how can I debug and see why build fails on this project?

**Comment by bcorso** [comment]
This error is from [BasicAnnotationProcessor](https://github.com/google/auto/blob/master/common/src/main/java/com/google/auto/common/BasicAnnotationProcessor.java#L252). It basically means that Dagger couldn't process some class because a symbol referenced in that class could not be resolved. 

The reason why the error message doesn't tell you which symbol could not be resolved is because it currently uses [SuperficialValidation#validateElement(Element)](https://github.com/google/auto/blob/master/common/src/main/java/com/google/auto/common/SuperficialValidation.java#L103), which unfortunately just returns a boolean and doesn't give any information about the symbol that couldn't be resolved. However, usually there is another error message in the build log that should give you a hint about what failed.

For example, suppose you have the code below where `@Blah` does not exist (or was not imported).

```java
@Blah
public class SomeThing {
    @Inject SomeThing() {}
}
```

When you compile the code above you will see the following error:


```
Foo.java:5: error: cannot find symbol
@Blah
 ^
  symbol: class Blah


SomeThing.java:6: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public class SomeThing {
       ^
```

The first error tells you that `@Blah` symbol could not be found, which is the real source of the problem.

The second error is similar to the error you got, which just says that Dagger could not process `SomeThing` because a symbol in `SomeThing.java` couldn't be resolved. In this case, that symbol is `@Blah`.

Hopefully that helps you narrow it down. Worse case, you can add some break points in `SuperficialValidation` to try to get more information about which symbol is not valid (note: using breakpoints in compiler code requires a bit of [setup](https://blog.xmartlabs.com/2016/03/28/Debugging-an-Annotator-Processor-in-your-project/)).

**Comment by auras** [comment]
I'm trying to debug, but it can only go so far without sources. And I can't import sources because they have a different package name inside dagger-compiler

**Comment by auras** [comment]
And there isn't any other **error** message in the build log besides what I initially posted.

**Comment by bcorso** [comment]
> I'm trying to debug, but it can only go so far without sources. And I can't import sources because they have a different package name inside dagger-compiler

Hmm, I tried with `SuperficialValidation.java` and the decompiled class seems okay, or do you mean something else?

**Comment by trevjonez** [comment]
if you add the compiler jar to your buildSrc api configuration you should be able to jump to all that in studio pretty easy.

then running the build telling it to run the kotlin compiler in process and pass --debug to gradle. from there it should wait for you to connect the IDE and you should then be able to debug the dagger code when kapt runs.

**Comment by auras** [comment]
I managed to get in debug mode. I copied the sources from google auto and changed the package name to dagger.shadow.auto.common to trick android studio into believing that these are the original sources, otherwise it wouldn't load them.

But when debugging most evaluations don't work. Like if I try to evaluate the expression with the code from validate element then Android Studio would throw NullPointerException.

Also if I go deeper into the methods called it seemed to me that the expression should have validated as true but instead it seems to have returned false. And I cannot test it when the IDE won't run the expression

**Comment by auras** [comment]
I've managed to isolate it to a particular `@Provides` annotation which you can only find in Android.

I created a sample project where you can reproduce this:
[MyApplication.zip](https://github.com/google/dagger/files/5404621/MyApplication.zip)

This project compiles fine on java 8 but in java 11 it throws an error:

```
C:\Users\Auras\AndroidStudioProjects\MyApplication\app\src\main\java\com\example\myapplication\ApplicationModule.java:25: error: @Provides methods must return a primitive, an array, a type variable, or a declared type
    DataBindingComponent providesDataBindingComponent(final Context context) {
                         ^C:\Users\Auras\AndroidStudioProjects\MyApplication\app\src\main\java\com\example\myapplication\AppComponent.java:6: error: com.example.myapplication.ApplicationModule has errors
        ApplicationModule.class
                         ^C:\Users\Auras\AndroidStudioProjects\MyApplication\app\src\main\java\com\example\myapplication\ApplicationModule.java:25: error: @Provides methods must return a primitive, an array, a type variable, or a declared type
    DataBindingComponent providesDataBindingComponent(final Context context) {
```

I think Dagger/kapt cannot find the `DataBindingComponent` class for some reason?

**Comment by kozaxinan** [comment]
Hi, @bcorso I managed to debug `SuperficialValidation` but I couldnt find any relevant information. Do you have suggestion about which method or parameter to look at. 
With Java11 dagger cannot create `DataBindingComponent`. How can I provide more detail about this?

**Comment by bcorso** [comment]
Sorry for the delay, I was able to reproduce this but I still haven't had time to debug yet -- I'll try to look into it this week.

However, from the new error message you posted in https://github.com/google/dagger/issues/2144#issuecomment-712436284, I don't think that error is related to the `SuperficialValidation`. It seems to be something up with `kapt`.

For now, one workaround you can try is to create a concrete type of `DataBindingComponent`, e.g.

```java
class MyDataBindingComponent implements DataBindingComponent {
  private final RandomBindingAdapter imagesBindingAdapter;

  @Inject
  MyDataBindingComponent(Context context) {
    this.imagesBindingAdapter = new RandomBindingAdapter(context);
  }

  @Override
  public RandomBindingAdapter getRandomBindingAdapter() {
    return imagesBindingAdapter;
  }
}
```

Then you can have users inject `MyDataBindingComponent`.

**Comment by bcorso** [comment]
# Update

So, in a successful build we would have:

* **Processing round 1**
    * [`ModuleProcessingStep`](https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/ModuleProcessingStep.java): Defers processing `ApplicationModule` (It references `DataBindingComponent`, which is not yet valid).
*  **Processing round 2**
    * [`ModuleProcessingStep`](https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/ModuleProcessingStep.java): Processes `ApplicationModule` (`DataBindingComponent` is now valid -- generated in round 1)

However, in Java 11 with `kapt` something is going wrong. 

In processing round 2, `DataBindingComponent` is not a valid type (even though `DataBindingComponent` appears to be generated at some point). This means that calling `TypeMirror#getKind()` on the type returns an [`ERROR`](https://docs.oracle.com/javase/8/docs/api/index.html?javax/lang/model/type/TypeKind.html) kind rather than a [`DECLARED`](https://docs.oracle.com/javase/8/docs/api/index.html?javax/lang/model/type/TypeKind.html) kind. Weirdly though, `SuperficialValidation` thinks the `DataBindingComponent` type is valid because rather than checking its `TypeMirror#getKind()`, it uses a [`TypeVisitor`](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/type/TypeVisitor.html), which is incorrectly visiting `#visitDeclared()` even though the corresponding type is an [`ErrorType`](https://docs.oracle.com/javase/8/docs/api/index.html?javax/lang/model/type/ErrorType.html). I can't find specific documentation, but this definitely seems like another related bug, since I would expect it to visit `#visitError()` in this case.

# So what does this mean for Dagger?

From Dagger's perspective, we initially think `DataBindingComponent` is valid in round 2 because of the bug in the visitor, so we go ahead and process `ApplicationModule`. Then, we realize the provides method is actually returning an `ErrorType` and we fail with the error message in https://github.com/google/dagger/issues/2144#issuecomment-712436284.

Again, I don't think there's much Dagger can really do in this case. We're relying on the underlying type system, so if the type is invalid we can't really make it valid. This appears to be a deeper issue between `kapt` and java 11. 

You can try filing a bug with `kapt`, although I'm not sure if the project is still actively fixing issues.

You might also want to file a bug with the `androidx.databinding` library. For example, this doesn't seem to be a in issue with other generated types like `AutoValue`. For example:

```java
@Module
class ApplicationModule {
  @AutoValue static abstract class Foo {}

  // This type is valid with kapt and java 11
  @Provides
  AutoValue_ApplicationModule_Foo provideFooAutoValue() {
      return new AutoValue_ApplicationModule_Foo();
  }

  // This type is invalid with kapt and java 11
  @Provides
  DataBindingComponent provideDataBindingComponent() {
      return new DataBindingComponent() {...};
  }
}
```

# Possible Workarounds

1. Avoid binding `DataBindingComponent` directly, and either extend or wrap it Instead (see https://github.com/google/dagger/issues/2144#issuecomment-731908754). However, note that this is really just a hack that relies on the fact that Dagger currently doesn't inspect the super types directly, but the underlying bug is still there and may cause issues later if Dagger starts relying on it.
2. Avoid using `kapt` in this situation -- it works with `annotationProcessor`
3. Avoid using java 11 in this situation -- it works with java 8.

**Comment by drewhannay** [comment]
I'm seeing what looks like the same issue with `DataBindingComponent` in my project that does not use `kapt` at all, so the connection with `kapt` might be a red herring. I tried the [suggested workaround](https://github.com/google/dagger/issues/2144#issuecomment-731908754) (along with as many variations of it as I could think of, but was unsuccessful...when I managed to hide the `DataBindingComponent` type from Dagger, it ended up crashing `javac` with a very cryptic error:

```compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.8, {1}, {2}, {3}, {4}, {5}, {6}, {7}
java.lang.NullPointerException
    at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitApply(Flow.java:1235)
    at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1634)
    at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)```

I will try to make a reproducible project today, as well as report this to the Data Binding team.

**Comment by drewhannay** [comment]
I simplified the repro project that was posted earlier in the thread:
https://github.com/drewhannay/data-binding-dagger-jdk11-crash

I stripped out `kapt` and Kotlin entirely. I also removed `dagger-android` as it was not relevant.

It seems the minimum necessary to reproduce this bug is to use a data binding `@BindingAdapter` AND to run the `dagger-compiler` annotation processor. If I remove dagger from the project entirely, the crash does not reproduce. Likewise, if I remove the data binding `@BindingAdapter`, the crash does not reproduce. So there is some combination of the two that is producing this compiler crash.

Since the upcoming AGP 7 release will require JDK 11, this seems pretty urgent to address.

**Comment by chao2zhang** [comment]
With the same project, I can reproduce the same crash even on JDK 11.
Buildscan: https://scans.gradle.com/s/se52n6hq77hzk

**Comment by drewhannay** [comment]
As another data point, it looks like this passes with JDK 11.0.10, but fails with 11.0.8. Unfortunately 11.0.8 is the version that Android Studio embeds

**Comment by danysantiago** [comment]
@drewhannay I've filled a request to the Android Studio team on your behalf to update the built-in JDK used.  https://issuetracker.google.com/183989366

**Comment by drewhannay** [comment]
Ooo, I forgot to post back here. I had also opened https://issuetracker.google.com/issues/183634719, so i assume one of them can be closed as a duplicate.

**Comment by danysantiago** [comment]
Ah, no worries, I'll just dupe the one I filled, thanks.
