### ISSUE TITLE
Error message does not give enough information for resolving the issue

### ISSUE THREAD

**Issue by OleksandrKucherenko** [google/dagger#2155]
The exception does not provide any hint on which member of class it fails or any other hint that will allow identifying the real cause of the compilation problem.

```
Caused by: java.lang.IllegalArgumentException: no expression found for BindingRequest{key=***.NowPlayingViewNavigator, requestKind=Optional[INSTANCE], frameworkType=Optional.empty}
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
        at dagger.internal.codegen.writing.ComponentBindingExpressions.getBindingExpression(ComponentBindingExpressions.java:241)
        at dagger.internal.codegen.writing.ComponentBindingExpressions.getBindingExpression(ComponentBindingExpressions.java:242)
        at dagger.internal.codegen.writing.ComponentBindingExpressions.getBindingExpression(ComponentBindingExpressions.java:242)
        at dagger.internal.codegen.writing.ComponentBindingExpressions.getDependencyExpression(ComponentBindingExpressions.java:130)
        at dagger.internal.codegen.writing.ComponentBindingExpressions.getDependencyArgumentExpression(ComponentBindingExpressions.java:198)
        at dagger.internal.codegen.writing.MembersInjectionMethods.lambda$membersInjectionMethod$0(MembersInjectionMethods.java:117)
        at dagger.internal.codegen.writing.InjectionMethods$InjectionSiteMethod.invoke(InjectionMethods.java:356)
        at dagger.internal.codegen.writing.InjectionMethods$InjectionSiteMethod.lambda$invokeAll$0(InjectionMethods.java:326)
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$forEachRemaining$1(CollectSpliterators.java:64)
        at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:64)
        at dagger.internal.codegen.writing.InjectionMethods$InjectionSiteMethod.invokeAll(InjectionMethods.java:334)
        at dagger.internal.codegen.writing.MembersInjectionMethods.membersInjectionMethod(MembersInjectionMethods.java:109)
        at dagger.internal.codegen.base.Util.reentrantComputeIfAbsent(Util.java:33)
        at dagger.internal.codegen.writing.MembersInjectionMethods.getOrCreate(MembersInjectionMethods.java:79)
        at dagger.internal.codegen.writing.MembersInjectionBindingExpression.membersInjectionInvocation(MembersInjectionBindingExpression.java:70)
        at dagger.internal.codegen.writing.MembersInjectionBindingExpression.getComponentMethodImplementation(MembersInjectionBindingExpression.java:64)
        at dagger.internal.codegen.writing.ComponentBindingExpressions.getComponentMethod(ComponentBindingExpressions.java:223)
        at dagger.internal.codegen.ComponentImplementationBuilder.addInterfaceMethods(ComponentImplementationBuilder.java:171)
        at dagger.internal.codegen.ComponentImplementationBuilder.build(ComponentImplementationBuilder.java:136)
        at dagger.internal.codegen.ComponentImplementationBuilder.buildChildImplementation(ComponentImplementationBuilder.java:271)
        at dagger.internal.codegen.ComponentImplementationBuilder.addChildComponents(ComponentImplementationBuilder.java:257)
        at dagger.internal.codegen.ComponentImplementationBuilder.build(ComponentImplementationBuilder.java:137)
        at dagger.internal.codegen.ComponentImplementationBuilder.buildChildImplementation(ComponentImplementationBuilder.java:271)
        at dagger.internal.codegen.ComponentImplementationBuilder.addChildComponents(ComponentImplementationBuilder.java:257)
        at dagger.internal.codegen.ComponentImplementationBuilder.build(ComponentImplementationBuilder.java:137)
        at dagger.internal.codegen.ComponentImplementationFactory.createComponentImplementationUncached(ComponentImplementationFactory.java:84)
        at dagger.internal.codegen.ComponentImplementationFactory.lambda$createComponentImplementation$0(ComponentImplementationFactory.java:60)
        at dagger.internal.codegen.base.Util.reentrantComputeIfAbsent(Util.java:33)
        at dagger.internal.codegen.ComponentImplementationFactory.createComponentImplementation(ComponentImplementationFactory.java:57)
        at dagger.internal.codegen.ComponentGenerator.write(ComponentGenerator.java:70)
        at dagger.internal.codegen.ComponentGenerator.write(ComponentGenerator.java:39)
        at dagger.internal.codegen.base.SourceFileGenerator.generate(SourceFileGenerator.java:77)
        at dagger.internal.codegen.base.SourceFileGenerator.generate(SourceFileGenerator.java:69)
        at dagger.internal.codegen.ComponentProcessingStep.generateComponent(ComponentProcessingStep.java:170)
        at dagger.internal.codegen.ComponentProcessingStep.processRootComponent(ComponentProcessingStep.java:152)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:131)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:62)
        at dagger.internal.codegen.validation.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:51)
        at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
        at dagger.internal.codegen.validation.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:48)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:124)
        at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:62)
        at dagger.internal.codegen.statistics.DaggerStatisticsCollectingProcessingStep.process(DaggerStatisticsCollectingProcessingStep.java:52)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.IsolatingProcessor.process(IsolatingProcessor.java:50)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.access$401(TimeTrackingProcessor.java:37)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:99)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:96)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.track(TimeTrackingProcessor.java:117)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.process(TimeTrackingProcessor.java:96)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 135 more
```

**Comment by OleksandrKucherenko** [comment]
with the latest version 2.29.1

```
> java.lang.IllegalArgumentException: Multiple entries with same key: class dagger.internal.codegen.ComponentProcessingStep=PT0.054973187S and class dagger.internal.codegen.ComponentProcessingStep=PT0.075867881S
```

**Comment by bcorso** [comment]
Hi @OleksandrKucherenko, thanks for reporting this. 

Unfortunately, these types of errors are difficult for us to reproduce just from the stack trace. If you could provide a project that reproduces this that would be really helpful (I know that's sometimes difficult/impossible to do). Otherwise, If you end up narrowing down to a particular part of your code that could help too.

**Comment by bcorso** [comment]
If you can't share the project, you can also try debugging this yourself, but it requires attaching the debugger during compilation (e.g. something like [this](https://blog.xmartlabs.com/2016/03/28/Debugging-an-Annotator-Processor-in-your-project/))

**Comment by OleksandrKucherenko** [comment]
> these types of errors are difficult for us to reproduce just from the stack trace.

My idea is not about fixing the code, it more about providing additional information during the exception raising. 

> ComponentBindingExpressions.getBindingExpression

On this level information is very fragmented, and it itself is not enough for understanding the context of the error.

But if we catch the exception on level of (or even higher):

> dagger.internal.codegen.writing.ComponentBindingExpressions.getComponentMethod

Then we can re-throw the exception with cause (original exception from low level) and some extra information...

Error description should contain:
- which class/method/member dagger processing in the moment of crash?
- Is it possible to publish the graph from root down to class that crashed?

**Comment by Chang-Eric** [comment]
For the IAE with Dagger 2.29.1, do you have the rest of the stacktrace?

This is also a shot in the dark, but I think I saw errors like the one you're seeing when I was working on https://github.com/google/dagger/issues/2085. Can you see if turning on the flag `-Adagger.strictMultibindingValidation=enabled` gets you a better error message? The problem is that we are getting past our own validation so we're just kind of check failing in a place that we don't really expect is possible to reach, which is why the errors become inscrutable.
