### ISSUE TITLE
[Hilt]- Hilt and Roboletric ViewModel not injected correctly .

### ISSUE THREAD

**Issue by hamed8080** [google/dagger#2170]
When i try to invoke a method on viewModel getting this error. but in real app doesn't have any problem.
i create a Test App in [this repository ](https://github.com/hamed8080/Hilt-With-Roboletric-Sample) you can download and inspect the code and help me.

```
java.lang.RuntimeException: Cannot create an instance of class ir.mobitrain.hiltRoboletricSample.MyViewModel

	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
	at ir.mobitrain.hiltRoboletricSample.MainActivity.getViewModel(MainActivity.kt)
	at ir.mobitrain.hiltRoboletricSample.MainActivityTest$test View Model Call Listener$1.perform(MainActivityTest.kt:34)
	at ir.mobitrain.hiltRoboletricSample.MainActivityTest$test View Model Call Listener$1.perform(MainActivityTest.kt:21)
	at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:660)
	at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
	at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:670)
	at ir.mobitrain.hiltRoboletricSample.MainActivityTest.test View Model Call Listener(MainActivityTest.kt:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at dagger.hilt.android.internal.testing.MarkThatRulesRanRule$1.evaluate(MarkThatRulesRanRule.java:92)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InstantiationException: ir.mobitrain.hiltRoboletricSample.MyViewModel
	at java.lang.Class.newInstance(Class.java:427)
	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
	... 32 more
Caused by: java.lang.NoSuchMethodException: ir.mobitrain.hiltRoboletricSample.MyViewModel.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 33 more
```

**Comment by bcorso** [comment]
Hi @hamed8080,

Are you running this with AndroidStudio? 

There's a known issue (https://issuetracker.google.com/37076369) where the byte-code transformed classes aren't used when running Robolectric tests from AndroidStudio. This causes issues with Hilt when you're using the [Hilt Gradle plugin](https://dagger.dev/hilt/gradle-setup.html#hilt-gradle-plugin) since that relies on byte-code transformation.

We've documented some workarounds [here](https://dagger.dev/hilt/gradle-setup.html#running-with-android-studio).

**Comment by hamed8080** [comment]
thanks @bcorso  i forgot that . 
test it through command line library and worked fine but i hope dagger team fix this issue as soon as possible. even me i read document before forgot that!
i created a [smaple app repository](https://github.com/hamed8080/Hilt-With-Roboletric-Sample).
hope that would be help someone to learn hilt and roboletric configuration faster and reduce headache of configurations.

**Comment by bcorso** [comment]
FWIW, the issue isn't something we can fix on the Dagger/Hilt side. We're working with the AGP team to address the issue in a future release of AGP.
