### ISSUE TITLE
Dagger/Hilt ViewModel injection IllegalArgumentException

### ISSUE THREAD

**Issue by imprakharshukla** [google/dagger#2238]
Hey! I am trying to work my way through rewriting my app to use MVVM and DI. Using hilt was a breeze but there's seems to be an issue with what I thing to be related to dagger/hilt for the most part.

Here is the exception that I get (this occur randomly, some times things just work and other time it's the following exception).

```
 java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
        at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.java:111)
        at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.java:50)
        at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:70)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at studio.com.techriz.andronix.ui.fragments.premium.FragmentPremium.getViewModel(Unknown Source:2)
        at studio.com.techriz.andronix.ui.fragments.premium.FragmentPremium.initBilling(FragmentPremium.kt:94)
        at studio.com.techriz.andronix.ui.fragments.premium.FragmentPremium$onViewCreated$1.invokeSuspend(FragmentPremium.kt:52)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

        
```
        
       
### **Code** - 
**Fragment** - 
```
   @ExperimentalCoroutinesApi
    @InternalCoroutinesApi
    @AndroidEntryPoint
    class FragmentPremium : Fragment(R.layout.fragment_premium) {

    @Inject
    lateinit var billingRepository: BillingRepository

    @Inject
    lateinit var loader: Loader
    val viewModel: FragmentPremiumViewModel by viewModels()

    private val binding by viewBinding(FragmentPremiumBinding::bind)
    // lateinit var binding: FragmentPremiumBinding

    lateinit var stateJob: Job


    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)


        stateJob = viewLifecycleOwner.lifecycleScope.launch(Dispatchers.IO) { initBilling() }

        binding.buyButtonText.text = resources.getString(R.string.just_a_sec)
        binding.buyPremButton.isClickable = false

        if (viewModel.isPremiumPurchased()) {
            binding.premiumPricingLayout.makeGone()
            binding.premiumAlreadyOwn.makeVisible()
            binding.buyPremButton.makeGone()
        }

        binding.buyPremButton.setOnClickListener {
            if (viewModel.isLoggedIn()) {
                if (viewModel.isSkuDetailInit()) {
                    viewModel.getFlowDetails().apply {
                        if (isAllowed && skuDetails != null) {
                            loader.startLoader()
                            billingRepository.launchBillingFlow(requireActivity(), skuDetails!!, uid, email)
                        } else
                            Toast.makeText(requireContext(), "Billing library error!", Toast.LENGTH_SHORT).show()
                    }
                } else {
                    Toast.makeText(requireContext(), "Billing library error!", Toast.LENGTH_SHORT).show()
                }
            } else {
                showLoginDialog()
            }
        }


    }

    override fun onDestroyView() {
        super.onDestroyView()
        if (this::stateJob.isInitialized) {
            "cancelled the job".log()
            stateJob.cancel()
        }
    }


    private suspend fun initBilling() {
        viewModel.initBilling().collect {
            when (it) {
                is PurchaseStateClass.Ready -> {
                    println("ready")
                    "Billing client ready".billingLog()
                    billingRepository.getSkuDetails()
                }
                is PurchaseStateClass.SkuDetails -> {
                    val details = billingRepository.getSingleSkuDetails(it.skuDetailsList, ProductInfo.PREMIUM().sku_id)
                    if (details != null) {
                        withContext(Dispatchers.Main) {
                            viewModel.skuDetails = details
                            binding.buyButtonText.text = resources.getString(R.string.buy)
                            binding.buyPremButton.isClickable = true
                            binding.priceText.text = details.price
                        }
                    } else {
                        "Details are null".billingLog()
                    }
                }
                is PurchaseStateClass.Consumed -> {
                    "Purchase consumed".billingLog()
                }
                is PurchaseStateClass.Completed -> {
                    println("completed")
                    "Purchase completed".billingLog()
                    loader.stopLoading()
                    lifecycleScope.launch(Dispatchers.Main) {
                        Toast.makeText(requireContext(), "Purchase done!", Toast.LENGTH_SHORT).show()
                    }
                }
                is PurchaseStateClass.Disconnected -> {
                    "Billing client disconnected".billingLog()
                }
                is PurchaseStateClass.Error -> {
                    loader.stopLoading()
                    "Billing error ${it.message}".billingLog(true)
                    lifecycleScope.launch(Dispatchers.Main) {
                        Toast.makeText(requireContext(), "Billing error ${it.message}", Toast.LENGTH_SHORT).show()
                    }
                }
                else -> Unit
            }
        }
    }

    private fun showLoginDialog() {
        val binding = LoginFirstSheetBinding.inflate(layoutInflater)
        val dialog = RoundedBottomSheetDialog(requireContext())
        dialog.setContentView(binding.root)
        binding.login.setOnClickListener {
            dialog.dismiss()
            findNavController().navigate(R.id.action_premiumFragment_to_loginFragment, bundleOf("return" to 
    R.id.action_to_premiumFragment), NavigationAnimations.getAlphaAnimation())
        }
        binding.closeLoginFirst.setOnClickListener { dialog.dismiss() }
        dialog.show()
    }


    }
```

**ViewModel** - 

```
    @ExperimentalCoroutinesApi
    class FragmentPremiumViewModel
    @ViewModelInject constructor(
        private val billingRepository: BillingRepository,
        private val userRepository: UserRepository,
    ) : ViewModel() {

    lateinit var skuDetails: SkuDetails
    private var _purchaseState = MutableStateFlow<PurchaseStateClass>(PurchaseStateClass.Empty)
    var purchaseState: StateFlow<PurchaseStateClass> = _purchaseState

    @InternalCoroutinesApi
    @ExperimentalCoroutinesApi
    fun initBilling(): StateFlow<PurchaseStateClass> {
        billingRepository.startConnection()
        return billingRepository.purchaseState
    }

    @ExperimentalCoroutinesApi
    fun getFlowDetails(): ModdedOsOnboardingViewModel.FlowDetails {
        val uid = userRepository.getUid()
        val email = userRepository.getEmail()
        "UID $uid".log()
        "Email $email".log()
        return if (!uid.isNullOrEmpty() && !email.isNullOrEmpty()) {
            //todo check for skudetails null
            println("SKU details $skuDetails")
            println("Email $email")
            println("Uid details $uid")
            ModdedOsOnboardingViewModel.FlowDetails(true, uid, email, skuDetails)
        } else {
            "User not logged in".log()
            ModdedOsOnboardingViewModel.FlowDetails(false, "", "", null)
        }
    }

    fun isSkuDetailInit(): Boolean {
        return this::skuDetails.isInitialized
    }

    fun isPremiumPurchased(): Boolean {
        return userRepository.isProductPurchased(ProductInfo.PREMIUM().id)
    }

    fun isLoggedIn() = userRepository.isLoggedIn()
    }
```

> The repositories and everything is just working fine everywhere else. In fact all the repositories being injected in this viewModel do work with another fragment and viewModel.

Here are my lifecycle and hilt dependencies- 

```
     //Android Lifecycle
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"
    implementation "androidx.lifecycle:lifecycle-common-java8:2.2.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
    implementation "androidx.fragment:fragment-ktx:1.2.5"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.2.0"

    //Hilt
    implementation "com.google.dagger:hilt-android:2.28-alpha"
    kapt "com.google.dagger:hilt-android-compiler:2.28-alpha"
    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha02'
    implementation 'androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02'

    // Navigation Component
    implementation 'androidx.navigation:navigation-fragment-ktx:2.3.2'
    implementation 'androidx.navigation:navigation-ui-ktx:2.3.2'

```

**Comment by imprakharshukla** [comment]
Just to add that the error switches to this at times, an IndexOutOfBound exception.

```
    2020-12-29 10:57:00.025 9609-9609/studio.com.techriz.andronix E/AndroidRuntime: FATAL EXCEPTION: main
    Process: studio.com.techriz.andronix, PID: 9609
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at androidx.lifecycle.LifecycleRegistry.calculateTargetState(LifecycleRegistry.java:162)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:183)
        at androidx.lifecycle.SavedStateHandleController.tryToAddRecreator(SavedStateHandleController.java:111)
        at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:71)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at studio.com.techriz.andronix.ui.fragments.premium.PremiumFragment.getViewModel(Unknown Source:2)
        at studio.com.techriz.andronix.ui.fragments.premium.PremiumFragment.onViewCreated(PremiumFragment.kt:56)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2236)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2009)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1965)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7657)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by Zhuinden** [comment]
Do

        val viewModel = viewModel

        stateJob = viewLifecycleOwner.lifecycleScope.launch(Dispatchers.IO) { initBilling() }

**Comment by YorekLiu** [comment]
I'm facing the same problem. You can initiate the lazy viewModel in UI Thread before using it in worker thread, to avoid IllegalArgumentException. Just like @Zhuinden .

**Comment by danysantiago** [comment]
@imprakharshukla where you able to solve this?

As Zhuinden suggested, try to force-initialize the view model in the UI Thread so that is retrievable by the `initBilling` coroutine. The [`by viewModels()` is a function that should be called in the main thread.](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment-ktx/src/main/java/androidx/fragment/app/FragmentViewModelLazy.kt;l=54)
