### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by sharyuke** [google/dagger#225]
follow is  my appcompent

package com.huixianxia.business.dagger;

import com.huixianxia.business.HyApplication;
import com.huixianxia.business.dagger.module.ModuleActivity;
import com.huixianxia.business.ui.LoginActivity;
import com.huixianxia.business.ui.MoreActivity;
import com.huixianxia.business.ui.MoreFeedbackActivity;
import com.huixianxia.business.ui.fragment.HomeMoreFragment;
import com.huixianxia.business.ui.fragment.HomeProductManagerFragment;
import com.huixianxia.business.ui.freeshop.news.view.activity.FreeShopCheckSuccess2;
import com.huixianxia.business.ui.shop.ShopRelease;

import javax.inject.Singleton;

import dagger.Component;

/**
 * AppComponent
 * Created by sharyuke on 15-7-22.
 */
@Singleton
@Component(modules = ModuleActivity.class)
public interface AppComponent {

    void inject(HyApplication application);

    void inject(LoginActivity loginActivity);

    void inject(ShopRelease shopRelease);

    void inject(FreeShopCheckSuccess2 freeShopCheckSuccess2);

    void inject(HomeProductManagerFragment homeProductManagerFragment);

    void inject(HomeMoreFragment homeMoreFragment);

    void inject(MoreFeedbackActivity moreFeedbackActivity);

    void inject(MoreActivity moreActivity);
}

there is 8 methods in it , but I just can invoke 6 method of it, when I invoke 7th mothod ,I got this.

08-18 14:49:58.758  10098-10098/? I/dalvikvm﹕ Could not find method com.huixianxia.business.dagger.module.ModuleActivity_GetAppFactory.create, referenced from method com.huixianxia.business.dagger.DaggerAppComponent.initialize
08-18 14:49:58.783  10098-10098/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.huixianxia.business.dagger.module.ModuleActivity_GetAppFactory
            at com.huixianxia.business.dagger.DaggerAppComponent.initialize(DaggerAppComponent.java:70)
            at com.huixianxia.business.dagger.DaggerAppComponent.<init>(DaggerAppComponent.java:62)
            at com.huixianxia.business.dagger.DaggerAppComponent.<init>(DaggerAppComponent.java:42)
            at com.huixianxia.business.dagger.DaggerAppComponent$Builder.build(DaggerAppComponent.java:138)
            at com.huixianxia.business.HyApplication.init(HyApplication.java:154)
            at com.huixianxia.business.HyApplication.onCreate(HyApplication.java:63)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4525)
            at android.app.ActivityThread.access$1300(ActivityThread.java:163)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5228)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:589)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by sharyuke** [comment]
if I do compile 'javax.annotation:javax.annotation-api:1.2' ,it will got the same error.

**Comment by sharyuke** [comment]
I found there many causes to cross this issue...

**Comment by sharyuke** [comment]
Observable.from(models)
                    .filter(imageViewerModel1 -> imageViewerModel1.status == ImageViewerModel.STATUS_WAIT_UPLOAD)
                    .map(imageViewerModel -> TextUtils.isEmpty(imageViewerModel.nativePath) ? imageViewerModel.netPath : imageViewerModel.nativePath)
                    .flatMap(s -> {
                        try {
                            return APIAction.getApiClient().postFileUpload(
                                    C.dataSP.getLValue(D.ACCOUNTID, 0L) + "",
                                    C.dataSP.getSValue(D.TOKEN, "") + "", "",
                                    new TypedByteArray("image/jpg",
                                            FileHelper.getBitmapBytes(Utils.getThumbUploadImage(s, GConstant.MAX_IMAGE_WIDTH))));
                        } catch (Exception e) {
                            e.printStackTrace();
                            return Observable.empty();
                        }
                    })
                    .filter(uploadCallBack1 -> uploadCallBack1 != null)
                    .filter(uploadCallBack2 -> uploadCallBack2.getData() != null)
// when I add follow line code ,, it will cross this issue too....
                    .flatMap(uploadCallBack -> Observable.from(uploadCallBack.getData()))
//                    .take(1)
//                    .doOnNext(FreeShopStepModelMapper.getInstance().netModel.shopImagesUriNet::add)
                    .subscribe();

**Comment by sharyuke** [comment]
there many kinds of change can cause this issue ... even some thing which have no relationship with dagger...
but this issue just cross on xiaomi system or some of samsum , it will not appear on nexus device.

**Comment by sharyuke** [comment]
I use MultiDexApplication to solve this issue ,I  guess this issue may cause by methods more than 65535 in one dex file
