### ISSUE TITLE
[Hilt]java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by TxcA** [google/dagger#2254]
I encountered an error using hilt.

When I use @AndroidEntryPoint to annotate Fragment, it will cause a reflection error in my BaseFragment. When I don't use @AndroidEntryPoint, the app can work normally. I tried many methods, but failed to fix this error.

---

### Class

LoginActivity.kt

```kotlin
@AndroidEntryPoint
class LoginRegisterActivity : BaseActivity<ActivityLoginBinding, LoginRegisterViewModel>() {
    override var hasAutoAddBaseLayout: Boolean = false
}
```

LoginFragment.kt

```kotlin
@AndroidEntryPoint
class LoginFragment : BaseFragment<FragmentLoginBinding, LoginRegisterViewModel>() {
        ......
}
```

BaseFragment.class and BaseActivity.kt

```kotlin
abstract class BaseFragment<out VB : ViewBinding, out VM : BaseViewModel> : Fragment(), IWindow,ILauncher by LauncherImpl(),
    ViewBindModelImpl<VB, VM> {
        
        ......
        private var container: ViewGroup? = null
        protected val viewBinding: VB by lazy { declaredViewBind(layoutInflater, container) }
        
        ......
}
        
```

ViewBindModelImpl.kt

```kotlin
interface ViewBindModelImpl<out VB : ViewBinding, out VM : BaseViewModel> {

    /**
     * view binding
     */
    @Suppress("UNCHECKED_CAST")
    fun declaredViewBind(
        layoutInflater: LayoutInflater,
        container: ViewGroup? = null
    ): VB {
        val type = javaClass.genericSuperclass as ParameterizedType
        val aClass = type.actualTypeArguments[0] as Class<VB>
        if (aClass.name == EmptyViewBinding.javaClass.name) {
            return EmptyViewBinding as VB
        }
        val method = aClass.getDeclaredMethod(
            "inflate",
            LayoutInflater::class.java,
            ViewGroup::class.java,
            Boolean::class.java
        )
        return method.invoke(null, layoutInflater, container, false) as VB
    }
    
    ......
    
}
```

---

### Error logs

```sh
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxx.debug, PID: 30602
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx.debug/com.xxx.xxx.ui.activities.LoginRegisterActivity}: java.lang.reflect.InvocationTargetException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.xxx.xxx.ui.base.impl.ViewBindModelImpl$DefaultImpls.declaredViewBind(ViewBindModelImpl.kt:49)
        at com.xxx.xxx.ui.base.BaseActivity.declaredViewBind(BaseActivity.kt:30)
        at com.xxx.xxx.ui.base.impl.ViewBindModelImpl$DefaultImpls.declaredViewBind$default(ViewBindModelImpl.kt:34)
        at com.xxx.xxx.ui.base.BaseActivity$viewBinding$2.invoke(BaseActivity.kt:46)
        at com.xxx.xxx.ui.base.BaseActivity$viewBinding$2.invoke(BaseActivity.kt:30)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.xxx.xxx.ui.base.BaseActivity.getViewBinding(Unknown Source:2)
        at com.xxx.xxx.ui.base.BaseActivity.onCreate(BaseActivity.kt:74)
        at com.xxx.xxx.ui.activities.Hilt_LoginRegisterActivity.onCreate(Hilt_LoginRegisterActivity.java:29)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.LinkageError: Method androidx.fragment.app.FragmentActivity com.xxx.xxx.ui.fragments.login.Hilt_LoginFragment.getActivity() overrides final method in class Landroidx/fragment/app/Fragment; (declaration of 'com.xxx.xxx.ui.fragments.login.Hilt_LoginFragment' appears in /data/app/~~Wk0--XoONsDW7ic00Sns-Q==/com.xxx.xxx.debug--TiGFUQanOEnNBUy2b4GTQ==/base.apk!classes2.dex)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at androidx.fragment.app.FragmentFactory.loadClass(FragmentFactory.java:47)
        at androidx.fragment.app.FragmentFactory.loadFragmentClass(FragmentFactory.java:88)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:595)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
        at androidx.navigation.fragment.FragmentNavigator.instantiateFragment(FragmentNavigator.java:132)
        at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.java:162)
        at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.java:58)
        at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.java:71)
        at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.java:28)
        at androidx.navigation.NavController.navigate(NavController.java:1057)
        at androidx.navigation.NavController.onGraphCreated(NavController.java:637)
        at androidx.navigation.NavController.setGraph(NavController.java:590)
        at androidx.navigation.NavController.setGraph(NavController.java:555)
        at androidx.navigation.NavController.setGraph(NavController.java:537)
2021-01-08 00:26:55.090 30602-30602/com.xxx.xxx.debug E/AndroidRuntime:     at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:248)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2921)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:496)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2173)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2089)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1954)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:306)
        at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.java:166)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:51)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:313)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:292)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1067)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:657)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at com.xxx.xxx.databinding.ActivityLoginBinding.inflate(ActivityLoginBinding.java:42)
        	... 25 more
2021-01-08 00:26:55.156 30602-30602/com.xxx.xxx.debug I/Process: Sending signal. PID: 30602 SIG: 9

```

---

I also saw other issue try to use, but to no effect, such as

```groovy
kapt 'com.squareup:javapoet:1.13.0'
```

My current module reference：

>Android Studio 4.1.1
>Build #AI-201.8743.12.41.6953283, built on November 5, 2020
>Runtime version: 1.8.0_242-release-1644-b01 amd64
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
>Windows 10 10.0

>```groovy
>ext {
>        hilt_version = '2.30.1-alpha'
>        hilt_view_model_version = '1.0.0-alpha02'
>}
>
>hiltAndroidKapt = "com.google.dagger:hilt-android-compiler:$hilt_version"
>hiltCompilerKapt = "androidx.hilt:hilt-compiler:$hilt_view_model_version"
>
>hiltAndroid = "com.google.dagger:hilt-android:$hilt_version"
>hiltViewModel = "androidx.hilt:hilt-lifecycle-viewmodel:$hilt_view_model_version"
>```

---

**Comment by bcorso** [comment]
It looks like the underlying issue is this part:

```
Caused by: java.lang.LinkageError: Method androidx.fragment.app.FragmentActivity com.xxx.xxx.ui.fragments.login.Hilt_LoginFragment.getActivity() overrides final method in class Landroidx/fragment/app/Fragment;
```

However, I'm not sure why `Hilt_LoginFragment` would be trying to override the `getActivity()` method. If possible, can you share the generated code for `Hilt_LoginFragment`?

Also, this is a shot in the dark, but maybe check that your `LoginFragment` and `BaseFragment` does not try to override `getActivity()`.

**Comment by TxcA** [comment]
> It looks like the underlying issue is this part:
> 
> ```
> Caused by: java.lang.LinkageError: Method androidx.fragment.app.FragmentActivity com.xxx.xxx.ui.fragments.login.Hilt_LoginFragment.getActivity() overrides final method in class Landroidx/fragment/app/Fragment;
> ```
> 
> However, I'm not sure why `Hilt_LoginFragment` would be trying to override the `getActivity()` method. If possible, can you share the generated code for `Hilt_LoginFragment`?
> 
> Also, this is a shot in the dark, but maybe check that your `LoginFragment` and `BaseFragment` does not try to override `getActivity()`.

thanks!
But I also checked Hilt_LoginFragment and found that it does not override the getActivity() method.

Hilt_LoginFragment.kt

```kotlin
package com.jhxhzn.art.ui.fragments.login;

import android.app.Activity;
import android.content.Context;
import android.content.ContextWrapper;
import android.os.Bundle;
import android.view.LayoutInflater;
import androidx.annotation.CallSuper;
import androidx.annotation.MainThread;
import androidx.lifecycle.ViewModelProvider;
import androidx.viewbinding.ViewBinding;
import com.jhxhzn.art.ui.base.BaseFragment;
import com.jhxhzn.art.ui.base.BaseViewModel;
import dagger.hilt.android.internal.lifecycle.DefaultViewModelFactories;
import dagger.hilt.android.internal.managers.FragmentComponentManager;
import dagger.hilt.internal.GeneratedComponentManagerHolder;
import dagger.hilt.internal.Preconditions;
import dagger.hilt.internal.UnsafeCasts;
import java.lang.Object;
import java.lang.Override;
import java.lang.SuppressWarnings;

/**
 * A generated base class to be extended by the @dagger.hilt.android.AndroidEntryPoint annotated class. If using the Gradle plugin, this is swapped as the base class via bytecode transformation.
 */
@SuppressWarnings("deprecation")
public abstract class Hilt_LoginFragment<VB extends ViewBinding, VM extends BaseViewModel> extends BaseFragment<VB, VM> implements GeneratedComponentManagerHolder {
  private ContextWrapper componentContext;

  private volatile FragmentComponentManager componentManager;

  private final Object componentManagerLock = new Object();

  @Override
  @CallSuper
  public void onAttach(Context context) {
    super.onAttach(context);
    initializeComponentContext();
  }

  @Override
  @CallSuper
  @MainThread
  public void onAttach(Activity activity) {
    super.onAttach(activity);
    Preconditions.checkState(componentContext == null || FragmentComponentManager.findActivity(componentContext) == activity, "onAttach called multiple times with different Context! Hilt Fragments should not be retained.");
    initializeComponentContext();
  }

  private void initializeComponentContext() {
    // Only inject on the first call to onAttach.
    if (componentContext == null) {
      // Note: The LayoutInflater provided by this componentContext may be different from super Fragment's because we getting it from base context instead of cloning from the super Fragment's LayoutInflater.
      componentContext = FragmentComponentManager.createContextWrapper(super.getContext(), this);
      inject();
    }
  }

  @Override
  public Context getContext() {
    return componentContext;
  }

  @Override
  public LayoutInflater onGetLayoutInflater(Bundle savedInstanceState) {
    LayoutInflater inflater = super.onGetLayoutInflater(savedInstanceState);
    return LayoutInflater.from(FragmentComponentManager.createContextWrapper(inflater, this));
  }

  @Override
  public final Object generatedComponent() {
    return this.componentManager().generatedComponent();
  }

  protected FragmentComponentManager createComponentManager() {
    return new FragmentComponentManager(this);
  }

  @Override
  public final FragmentComponentManager componentManager() {
    if (componentManager == null) {
      synchronized (componentManagerLock) {
        if (componentManager == null) {
          componentManager = createComponentManager();
        }
      }
    }
    return componentManager;
  }

  protected void inject() {
    ((LoginFragment_GeneratedInjector) this.generatedComponent()).injectLoginFragment(UnsafeCasts.<LoginFragment>unsafeCast(this));
  }

  @Override
  public ViewModelProvider.Factory getDefaultViewModelProviderFactory() {
    ViewModelProvider.Factory factory = DefaultViewModelFactories.getFragmentFactory(this);
    if (factory != null) {
      return factory;
    }
    return super.getDefaultViewModelProviderFactory();
  }
}
```

**Comment by bcorso** [comment]
Hmm, yeah something sounds very off here. Is there any way for you to put together a repro example for us to look into?

**Comment by TxcA** [comment]
> Hmm, yeah something sounds very off here. Is there any way for you to put together a repro example for us to look into?

I found the problem when writing the example!

In fact, the problem occurred in another `ILauncher` class of mine, this is an interface that uses `registerForActivityResult`. In order to bind the fragment and the lifecycle of the Activity, the activity or fragment is passed in. And there are two fields named activity and fragment in this interface. When BaseActivity and BaseFragment implement ILauncher interfaces, it will cause getActivity() to be rewritten (Kotlin will automatically rewrite get/set).

After I renamed `var activity` to `var activityInside` and `var fragment` to `var fragmentInside`, this problem was solved. **But I still haven't figured out why the problem was exposed after using `@AndroidEntryPoint`, when the `@AndroidEntryPoint` annotation is not use, the App can work normally.**



```kotlin
class LauncherImpl : ILauncher, LifecycleEventObserver {
    // This leads to override getActivity(),this is a hidden bug,i have renamed and fixed it.
    override var activity: BaseActivity<*, *>? = null
    override var fragment: BaseFragment<*, *>? = null

    override lateinit var activityLauncher: ActivityResultLauncher<Intent>
    override val activityResultCallback: Deque<(ActivityResult) -> Unit> = ArrayDeque()

    override fun onStateChanged(source: LifecycleOwner, event: Lifecycle.Event) {
        if (event == Lifecycle.Event.ON_CREATE) {
            activity?.registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
                activityResultCallback.pop()?.invoke(result)
            }?.apply { activityLauncher = this }

            fragment?.registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
                activityResultCallback.pop()?.invoke(result)
            }?.apply { activityLauncher = this }

        } else if (event == Lifecycle.Event.ON_DESTROY) {
            activity?.lifecycle?.removeObserver(this)
            fragment?.lifecycle?.removeObserver(this)
        }
    }

    override fun bindLauncherActivity(activity: BaseActivity<*, *>) {
        this.activity = activity
        this.activity?.lifecycle?.addObserver(this)
    }

    override fun bindLauncherFragment(fragment: BaseFragment<*, *>) {
        this.fragment = fragment
        this.fragment?.lifecycle?.addObserver(this)
    }
......
}
```


Thanks again @bcorso

**Comment by premacck** [comment]
Wow this issue turned out to be a lifesaver!
IJust migrated a large project from Dagger 2 to Hilt, and was experiencing same crash on app launch itself:

```
java.lang.LinkageError: Method java.lang.Object com.example.myapp.core.onboarding.ui.Hilt_OnboardingPageFragment.getHost() overrides final method in class Landroidx/fragment/app/Fragment; (declaration of 'com.example.myapp.core.onboarding.ui.Hilt_OnboardingPageFragment' appears in /data/app/com.example.myapp-_QgZ1wZBibZW21ItnXlPIQ==/base.apk!classes2.dex)
        at com.example.myapp.core.onboarding.ui.OnBoardingActivity.setupViewPager(OnBoardingActivity.kt:67)
        at com.example.myapp.core.onboarding.ui.OnBoardingActivity.onCreateSafe(OnBoardingActivity.kt:48)
        at com.example.myapp.base.ui.activity.BaseGarasiActivity.onCreate(BaseGarasiActivity.kt:87)
        at com.example.myapp.core.onboarding.ui.Hilt_OnBoardingActivity.onCreate(Hilt_OnBoardingActivity.java:33)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

After spending an hour searching for what could be the issue in my project, finding nothing on google, or stackoverflow even, finally stumbling onto this thread.
Turns out I was using a `host` property in a root interface that my `BaseFragment` was implementing, and it was being overridden in `BaseFragment` itself, that's why checking out the `Hilt_` counterpart of fragment couldn't help

So I just renamed `host` to some other name, and it works now.

Thanks a lot @TxcA and @bcorso !
