### ISSUE TITLE
[HELP] How to inject into @HitViewModel from SingletonComponent?

### ISSUE THREAD

**Issue by leonlatsch** [google/dagger#2348]
How do I inject a singleton from the SingletonComponent into a @HitViewModel?

I have red the documentation on this and it says `Only dependencies from the ViewModelComponent and its parent components can be provided into the ViewModel.`
Since [SingletonComponent is the parent of all components](https://dagger.dev/hilt/components).

This should work:

**AppModule**
```kotlin
@Module
@InstallIn(SingletonComponent::class)
object AppModule {

    @Provides
    @Singleton
    fun providePhotokDatabase(@ApplicationContext app: Context) = Room.databaseBuilder(
        app,
        PhotokDatabase::class.java,
        DATABASE_NAME
    ).build()
}
```

**ViewModel**
```kotlin
@HiltViewModel
class SplashScreenViewModel @Inject constructor(
    app: Application,
    private val config: Config
) : ObservableViewModel(app) { // ObservableViewModel is of type AndroidViewModel
```

But it gives me a: `java.lang.NoSuchMethodException` at runtime.
Did i understand it wrong?

**Comment by Chang-Eric** [comment]
A `NoSuchMethodException` is something else and indicates use of reflection. Dagger/Hilt should only use reflection in tests and only rarely, so I'm guessing this is something else in you code. If this were an issue of the dependency not being available, you'd get a compile time error.

**Comment by leonlatsch** [comment]
Weird, it appeared after these changes:

![image](https://user-images.githubusercontent.com/50983026/106511257-4b0c3b00-64d0-11eb-9d35-bdc7df1b75ca.png)

**Comment by leonlatsch** [comment]
I am using version: `2.29.1-alpha`

**Comment by Chang-Eric** [comment]
Are you able to share the stacktrace?

**Comment by leonlatsch** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.leonlatsch.photok, PID: 24967
    java.lang.RuntimeException: Cannot create an instance of class dev.leonlatsch.photok.ui.start.SplashScreenViewModel
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:269)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106)
        at androidx.hilt.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:81)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:84)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:108)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at dev.leonlatsch.photok.ui.start.SplashScreenFragment.getViewModel(Unknown Source:2)
        at dev.leonlatsch.photok.ui.start.SplashScreenFragment.onViewCreated(SplashScreenFragment.kt:43)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NoSuchMethodException: dev.leonlatsch.photok.ui.start.SplashScreenViewModel.<init> [class android.app.Application]
E/AndroidRuntime:     at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getConstructor(Class.java:1728)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:267)
        	... 43 more

```

**Comment by Chang-Eric** [comment]
Btw HiltViewModel was only released in 2.31 (https://github.com/google/dagger/releases/tag/dagger-2.31)

**Comment by leonlatsch** [comment]
Ohh, that could be the error. The deprecation for @ViewModelInject appered after updating these:
```gradle
implementation("androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha03")
    kapt("androidx.hilt:hilt-compiler:1.0.0-alpha03")
```

These are my dagger deps:
```gradle
    val daggerVersion = "2.29.1"
    val hiltVersion = "2.29.1-alpha"

    // Dagger Core
    implementation("com.google.dagger:dagger:$daggerVersion")
    kapt("com.google.dagger:dagger-compiler:$daggerVersion")

    // Dagger - Hilt
    implementation("com.google.dagger:hilt-android:$hiltVersion")
    kapt("com.google.dagger:hilt-android-compiler:$hiltVersion")

    implementation("androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha03")
    kapt("androidx.hilt:hilt-compiler:1.0.0-alpha03")
```

**Comment by leonlatsch** [comment]
And @HiltViewModel is available

**Comment by Chang-Eric** [comment]
Try upgrading to 2.31. It might be something like you have access to the annotation because of the deps on another target like the AndroidX extensions are resolving to a higher version, but the annotation processor is still 2.29 and so the annotation isn't doing anything.

**Comment by leonlatsch** [comment]
I'll try that., Thank you

**Comment by leonlatsch** [comment]
It works :)
