### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: com/android/Version   with hilt version 2.34

### ISSUE THREAD

**Issue by byrxs5216** [google/dagger#2547]
Caused by: java.lang.NoClassDefFoundError: com/android/Version
        at dagger.hilt.android.plugin.util.SimpleAGPVersion$Companion$ANDROID_GRADLE_PLUGIN_VERSION$2.invoke(SimpleAGPVersion.kt:23)
        at dagger.hilt.android.plugin.util.SimpleAGPVersion$Companion$ANDROID_GRADLE_PLUGIN_VERSION$2.invoke(SimpleAGPVersion.kt:21)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at dagger.hilt.android.plugin.util.SimpleAGPVersion$Companion.getANDROID_GRADLE_PLUGIN_VERSION(SimpleAGPVersion.kt)
        at dagger.hilt.android.plugin.HiltGradlePlugin.configureHilt(HiltGradlePlugin.kt:74)
        at dagger.hilt.android.plugin.HiltGradlePlugin.access$configureHilt(HiltGradlePlugin.kt:50)
        at dagger.hilt.android.plugin.HiltGradlePlugin$apply$1.execute(HiltGradlePlugin.kt:57)
        at dagger.hilt.android.plugin.HiltGradlePlugin$apply$1.execute(HiltGradlePlugin.kt:50)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:94)
        at org.gradle.api.internal.collections.CollectionFilter$1.execute(CollectionFilter.java:59)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:163)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:205)
        at dagger.hilt.android.plugin.HiltGradlePlugin.apply(HiltGradlePlugin.kt:55)
        at dagger.hilt.android.plugin.HiltGradlePlugin.apply(HiltGradlePlugin.kt:50)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)

**Comment by byrxs5216** [comment]
com.android.tools.build:gradle:3.5.3

**Comment by danysantiago** [comment]
Thats a decently old version of AGP, can you please try the latest stable? Hilt requires at least 4.x and sadly the APIs to check for versions are not available in the older versions of AGP so we can't quite throw the right error.

**Comment by byrxs5216** [comment]
The cost of upgrading AGP to 4.x is still quite high. Is there any solution that is compatible with the lower version

**Comment by danysantiago** [comment]
I'll try to workaround this issue and make a fix.
