### ISSUE TITLE
Configuration Cache and dagger.hilt.android.plugin

### ISSUE THREAD

**Issue by tinder-inakivillar** [google/dagger#2597]
Hi, we are testing AGP 4.2 with Gradle Configuration Cache. 
When the build reuses the configuration cache, all the modules with plugin `dagger.hilt.android.plugin` fail at the task `transformDebugClassesWithAsm`:

```
Caused by: java.lang.NullPointerException	
 at com.android.build.gradle.tasks.TransformClassesWithAsmTask.getInstrumentationManager(TransformClassesWithAsmTask.kt:250)	
 at com.android.build.gradle.tasks.TransformClassesWithAsmTask.doFullTaskAction(TransformClassesWithAsmTask.kt:133)	
 at com.android.build.gradle.tasks.TransformClassesWithAsmTask.doTaskAction(TransformClassesWithAsmTask.kt:124)	
 at com.android.build.gradle.internal.tasks.NewIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:66)	
 at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)	
 at com.android.build.gradle.internal.tasks.NewIncrementalTask.taskAction(NewIncrementalTask.kt:41)

```

**Comment by danysantiago** [comment]
This seems like an issue in the Android Gradle Plugin, I filled a bug to the team to investigate: https://issuetracker.google.com/187769343

**Comment by danysantiago** [comment]
Based on https://issuetracker.google.com/issues/187769343#comment3 this is fixed and the fix will be available in the next AGP versions.
