### ISSUE TITLE
 @Named causes Fatal error compiling: IllegalArgumentException

### ISSUE THREAD

**Issue by db82407** [google/dagger#260]
I was attempting to create an ExpensiveCoffeeMaker, with two @Named Heaters, as suggested in the docs, but as soon as I added the @Named annotations, I got this exception from the compiler:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project simple2: Fatal error compiling: java.lang.IllegalArgumentException -> [Help 1]
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108) ~[guava-18.0.jar:na]
	at dagger.internal.codegen.ProvisionBinding$Factory.forInjectConstructor(ProvisionBinding.java:190) ~[na:na]
	at dagger.internal.codegen.InjectBindingRegistry.getOrFindProvisionBinding(InjectBindingRegistry.java:239) ~[na:na]
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.lookUpBindings(BindingGraph.java:287) ~[na:na]
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.resolve(BindingGraph.java:407) ~[na:na]
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.resolve(BindingGraph.java:410) ~[na:na]
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.resolve(BindingGraph.java:410) ~[na:na]
	at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:168) ~[na:na]
	at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:105) ~[na:na]
	at dagger.internal.codegen.AbstractComponentProcessingStep.process(AbstractComponentProcessingStep.java:54) ~[na:na]
	at dagger.internal.codegen.AbstractComponentProcessingStep.process(AbstractComponentProcessingStep.java:30) ~[na:na]
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318) ~[na:na]

"simple2" is a copy of the "simple" example coffee app, with @Named("water") applied to the Heater in 3 places: CoffeeMaker, DripCoffeeModule and Thermosiphon. It is available in my (db82407) fork.

"simple3" is my attempt to create an ExpensiveCoffeeMaker, as suggested in the docs, but fails in the same way.

**Comment by ronshapiro** [comment]
So the root of the issue is that you have @Named("water") on the `Thermosiphon` constructor (which isn't allowed and doesn't really make sense[1]). If you move it to `Heater` parameter, then everything compiles correctly. There's a bug in the compiler that we should fix because you're not seeing a valid error here but the functionality is intended.

[1] Applying a qualifier on a constructor isn't useful since qualifiers allow you to have multiple kinds of the exact same type in your `@Component`. If you apply the qualifier to the constructor, you are effectively stating "the only Thermosiphon I can inject is a water one" - so there is only one kind and qualifier is redundant. For that reason, qualifiers are only allowed in modules, which are a place you can provide multiple [qualified] kinds of objects with the same type.

**Comment by ronshapiro** [comment]
Here is the line where the exception is thrown, just without a message: https://github.com/google/dagger/blob/master/compiler/src/main/java/dagger/internal/codegen/ProvisionBinding.java#L190

**Comment by ronshapiro** [comment]
I can't figure out why the error is not being printed out, but I am seeing it internally. I couldn't get the error reported when I cloned your repo (`mvn clean install`) and it seemed that nothing was happening, and gradle seems to mask some errors depending on the [lack of] flags passed and I wasn't getting consistent results. But it's possible that this is fixed in the internally but not yet externally.

When I pull in your code and try to compile, the output is:

```
Thermosiphon.java:9: error: @Qualifier annotations are not
allowed on @Inject constructors.
  @Inject @Named("water")
          ^
```

**Comment by db82407** [comment]
Hi, Thanks for your analysis and explanation.

I was trying to create a test-case for a problem I'm experiencing in a larger code base, and I didn't intend to place @Named() on the Thermosiphon constructor.

--
Derek
