### ISSUE TITLE
Generated classes are not accessible in Android < 5

### ISSUE THREAD

**Issue by cheskos** [google/dagger#266]
Hello. 

I've been working on a project that uses this great library along with Autodagger for the past pair of months. My main test devices are Genymotion emulators loaded with KitKat and Lollipop and I switch between them indistinctively. 

Yesterday I found out that running the project on either emulator or a real device with 4.x causes the following exception:

```java
11-20 15:36:31.637 7189-7189/? E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: com.chiskosystems.debito.DebitoAppModule_ProvideRestAdapterFactory
    at com.chiskosystems.debito.DaggerDebitoAppComponent.initialize(DaggerDebitoAppComponent.java:30)
    at com.chiskosystems.debito.DaggerDebitoAppComponent.<init>(DaggerDebitoAppComponent.java:19)
    at com.chiskosystems.debito.DaggerDebitoAppComponent.<init>(DaggerDebitoAppComponent.java:11)
    at com.chiskosystems.debito.DaggerDebitoAppComponent$Builder.build(DaggerDebitoAppComponent.java:72)
    at com.chiskosystems.debito.DebitoApp.setupComponent(DebitoApp.java:130)
    at com.chiskosystems.debito.DebitoApp.onCreate(DebitoApp.java:75)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
    at android.app.ActivityThread.access$1300(ActivityThread.java:130)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4745)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
```

but it runs fine in > 5.0 

If I launch a 
```shell
find /path/to/my/project -name DebitoAppModule_ProvideRestAdapterFactory.java
```
I get a result. Any pointers on to what can be wrong will be greatly appreciated. 

Thanks a lot!

**Comment by ronshapiro** [comment]
Are you able to run the `find` command on a clean build? This sounds like an issue with the Android build tools and not with dagger; the code compiled fine but then is not loaded correctly. Are you using proguard?

**Comment by cheskos** [comment]
Hi Ron. Thanks for your reply.

Yes, I'm using proguard, and it looks like this:

```
## Retrofit ------------------------------
-dontwarn retrofit.**
-keep class retrofit.** { *; }
-keepattributes Signature
-keepattributes Exceptions
-keepclassmembers
# ----------------------------------------
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes InnerClasses

# LeakCanary
-keep class org.eclipse.mat.** { *; }
-keep class com.squareup.leakcanary.** { *; }

-keepclassmembers,allowobfuscation class * {
@javax.inject.* *; 
@dagger.* *; 
<init>(); 
}
 -keep class **$ModuleAdapter
 -keep class **$InjectAdapter
 -keep class **$StaticInjection
 -keep class **$Adapter
 -keepnames class dagger.Lazy
```

Could you please specify what you mean by "clean build"?

**Comment by ronshapiro** [comment]
Are you using gradle? Run `/.gradlew clean` from your project root and then try and build again, then run your `find` command.

**Comment by ronshapiro** [comment]
Also, it looks like your proguard rules are related to Dagger 1 but shouldn't be relevant in Dagger 2

**Comment by cheskos** [comment]
OK, so I changed Build tools to 23.0.1, cleaned project, removed proguard rules, ran ```find``` and the class is there. But now I'm getting warnings related to what I think are the proguard rules I deleted:

```
Note: there were 1 references to unknown class members.
      You should check your configuration for typos.
Note: there were 19 classes trying to access annotations using reflection.
      You should consider keeping the annotation attributes
      (using '-keepattributes *Annotation*').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 19 classes trying to access generic signatures using reflection.
      You should consider keeping the signature attributes
      (using '-keepattributes Signature').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 3 classes trying to access enclosing classes using reflection.
      You should consider keeping the inner classes attributes
      (using '-keepattributes InnerClasses').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 11 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 25 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Note: you're ignoring all warnings!
```
and also a bunch of these:
```
Note: butterknife.internal.BindingClass calls 'Field.getAnnotation'
Note: butterknife.internal.ButterKnifeProcessor calls 'Class.getAnnotation'
Note: butterknife.internal.ButterKnifeProcessor calls 'Field.getAnnotation'
Note: com.google.ads.mediation.MediationServerParameters calls 'Field.getAnnotation'
Note: com.google.gson.FieldAttributes calls 'Field.getAnnotation'
Note: com.google.gson.FieldAttributes calls 'Field.getAnnotations'
Note: android.support.v7.internal.widget.DrawableUtils: can't find dynamically referenced class android.graphics.Insets
Note: com.google.android.gms.maps.internal.zzy: can't find dynamically referenced class com.google.android.gms.maps.internal.CreatorImpl
Note: com.google.gson.internal.UnsafeAllocator: can't find dynamically referenced class sun.misc.Unsafe
Note: com.squareup.okhttp.internal.Platform: can't find dynamically referenced class com.android.org.conscrypt.OpenSSLSocketImpl
Note: com.squareup.okhttp.internal.Platform: can't find dynamically referenced class org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl
Note: com.squareup.okhttp.internal.Platform: can't find dynamically referenced class android.net.TrafficStats
Note: com.squareup.okhttp.internal.Platform: can't find dynamically referenced class android.net.Network
Note: retrofit.Platform: can't find dynamically referenced class android.os.Build
Note: retrofit.Platform: can't find dynamically referenced class rx.Observable
```

and the build is not completed because:
```
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/opt/java/jdk1.8.0_66/bin/java'' finished with non-zero exit value 3
```

But my build.gradle file has:
```
android {
    compileSdkVersion 22
    buildToolsVersion "23.0.2"
    defaultConfig {
        ...
        multiDexEnabled true
    }
```

**Comment by ronshapiro** [comment]
I only meant these proguard rules, not the entire file:

```
-keepclassmembers,allowobfuscation class * {
@javax.inject.* *; 
@dagger.* *; 
<init>(); 
}
 -keep class **$ModuleAdapter
 -keep class **$InjectAdapter
 -keep class **$StaticInjection
 -keep class **$Adapter
 -keepnames class dagger.Lazy
```

Let's continue this on StackOverflow so we don't spam other maintainers, this doesn't appear to be a Dagger bug. If it is we can reopen the ticket and solve it here.

**Comment by cheskos** [comment]
Sure. Please see 
http://stackoverflow.com/questions/33836579/

**Comment by cheskos** [comment]
Please consider reopening this. It seems like a strange but real issue. See [this SO question](http://stackoverflow.com/questions/33836579/dagger2-generated-classes-are-not-accessible-in-android-5-0)

Thanks
