### ISSUE TITLE
Hilt and Android library

### ISSUE THREAD

**Issue by LajosNeto** [google/dagger#2663]
I was trying to implement the following module approach for a project :

- Module App (Android application)
- Module A (Android library)
- Module B (Android library)
- Module Core (Android library)

I would like to inject dependencies from module Core on modules A and B, and then inject dependencies from modules A and B on module App.

Injecting from A and B into module App is not a problem as App includes @HiltAndroidApp on its BaseApplication class. But what about injecting module Core dependencies into A and B (all of them being Android Libraries) ?

I already searched similar previous issues and I found issue [#2132](https://github.com/google/dagger/issues/2132) that follows almost the same idea.

Is it a valid use case for Hilt? 

Thx!

**Comment by bcorso** [comment]
Yes that should work fine with Hilt. 

You probably also want to enable [classpath aggregation](https://dagger.dev/hilt/gradle-setup#classpath-aggregation) so that Hilt has access to the transitive deps without requiring `api` usage.

RE: Issue #2132. That is a more complicated case where the library may not be used by a Hilt application. In your case, it sounds like "Module Core" will always be used by a Hilt application ("Module App"), so things should just work.

**Comment by LajosNeto** [comment]
Thank you very much for the quick response!

I just tested the mentioned module structure and also applied the configuration suggestion for the classpath aggregation and it is working!

**Comment by iChavezF** [comment]
I have the same problem or question, I have a library that has activities, framgents, a database and uses retrofit. But when calling an activity from the main application I get some errors.


> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.concredito.calleraar, PID: 11672
    java.lang.RuntimeException: Unable to instantiate application com.concredito.milibreta.MiLibretaApplication: java.lang.ClassNotFoundException: Didn't find class "com.concredito.milibreta.MiLibretaApplication" on path: DexPathList[[zip file "/data/app/com.concredito.calleraar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.concredito.calleraar-1/lib/x86, /system/lib, /vendor/lib]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:802)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5335)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.concredito.milibreta.MiLibretaApplication" on path: DexPathList[[zip file "/data/app/com.concredito.calleraar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.concredito.calleraar-1/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5335) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/concredito/milibreta/Hilt_MiLibretaApplication;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        		... 12 more
     Caused by: java.lang.ClassNotFoundException: com.concredito.milibreta.Hilt_MiLibretaApplication
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 15 more
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ldagger/hilt/internal/GeneratedComponentManagerHolder;
        		... 15 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "dagger.hilt.internal.GeneratedComponentManagerHolder" on path: DexPathList[[zip file "/data/app/com.concredito.calleraar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.concredito.calleraar-1/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 15 more
