### ISSUE TITLE
After upgrading the new version, there are a lot of crashes in our release version

### ISSUE THREAD

**Issue by henjue** [google/dagger#2672]
**hilt version:**    2.36  
**android os:**     7.0  
**compileSdkVersion:**    29  
**buildToolsVersion:**     "30.0.2"  
**ndkVersion:**     "21.3.6528147"  
**minSdkVersion** :     23  
**targetSdkVersion :**     29  
**android gradle plugin version:**      4.2.1  

```log
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tiptop.live/com.tiptop.live.ui.view.Main2Activity}: java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Application
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2748)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2813)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4651)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6300)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1076)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
```
```log
Caused by java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Application
       at dagger.hilt.android.internal.modules.ApplicationContextModule.provideApplication(ApplicationContextModule.java:45)
       at dagger.hilt.android.internal.modules.ApplicationContextModule_ProvideApplicationFactory.provideApplication(ApplicationContextModule_ProvideApplicationFactory.java:32)
       at com.tiptop.live.DaggerTiptopApplication_HiltComponents_SingletonC$ActivityRetainedCImpl$ActivityCImpl.getHiltInternalFactoryFactory(DaggerTiptopApplication_HiltComponents_SingletonC.java:749)
       at dagger.hilt.android.internal.lifecycle.DefaultViewModelFactories.getActivityFactory(DefaultViewModelFactories.java:56)
       at com.tiptop.live.common.fragment.Hilt_AbstractActivity.getDefaultViewModelProviderFactory(Hilt_AbstractActivity.java:68)
       at androidx.activity.ActivityViewModelLazyKt$viewModels$factoryPromise$1.invoke(ActivityViewModelLazyKt.java:44)
       at com.tiptop.live.ui.view.Main2Activity$special$$inlined$viewModels$default$1.invoke(Main2Activity.java:44)
       at androidx.activity.ActivityViewModelLazyKt$viewModels$factoryPromise$1.invoke(ActivityViewModelLazyKt.java:44)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.java:52)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.java:41)
       at com.tiptop.live.ui.view.Main2Activity.<clinit>(Main2Activity.java:53)
       at com.tiptop.live.ui.view.Main2Activity.onCreate(Main2Activity.java:91)
       at android.app.Activity.performCreate(Activity.java:6700)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2701)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2813)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4651)
       at android.app.ActivityThread.-wrap19(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6300)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1076)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
```

![image](https://user-images.githubusercontent.com/1314740/120877606-09a8ab00-c5ea-11eb-9e78-42ff59ac1751.png)

![image](https://user-images.githubusercontent.com/1314740/120877594-f72e7180-c5e9-11eb-9363-2d6ce20cb7bb.png)

**Comment by BAndersonMatjik** [comment]
i have problem maybe same but get error at providing context app to room init,but my error more like Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lid/***/*****/DbModules_ProvideDbFactory; its like not found that factory class but when i search in generated code it have that factory dbmodules

**Comment by Chang-Eric** [comment]
@henjue - Can you confirm your previous version of Hilt? Nothing has changed in that area for a while so I'd be surprised if this is related to upgrading the Hilt version. Do you get these crashes more on a specific OS version or anything like that?

Also, does your Application class override `attachBaseContext()` or `getApplicationContext()` and do anything with the context there?

**Comment by henjue** [comment]
@Chang-Eric I can see from firebase that previous versions also have this problem,There are also some custom modules that use. But I don't quite understand the difference between the following code
### code1
```java
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(customModule.attachBaseContext(base));
        MultiDex.install(this);
    }
```

### code2
```java
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(customModule.attachBaseContext(this));
        MultiDex.install(this);
    }
```

**Comment by henjue** [comment]
@Chang-Eric On the problem of getapplicationcontext，i use the lib https://github.com/zeugma-solutions/locale-helper-android

**Comment by kishansolanki124** [comment]
I am also having this problem after updating dependency.

![oie_v9ksG3W8Bjmt](https://user-images.githubusercontent.com/26580224/121228717-b87b0e80-c8aa-11eb-8fa5-74c12579a652.png)

**Comment by Chang-Eric** [comment]
I put in a fix that should avoid relying on the `getApplicationContext()` call, so it should find the Application properly now.

**Comment by amarilindra** [comment]
Remove `override fun getApplicationContext(): Context` from your activity or base activity and it should solve the issue. If you are overriding  getApplicationContext for Light/Dark theme switching, use `baseContext` instead of `applicationContext`
