### ISSUE TITLE
[Hilt] Bazel HiltViewModel inject java.lang.RuntimeException: Cannot create an instance of class MyViewModel

### ISSUE THREAD

**Issue by geaden** [google/dagger#2696]
After following instruction on integrating with Bazel, I'm getting the follwing exception

```
/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 10134
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.example.app.MyActivity}: java.lang.RuntimeException: Cannot create an instance of class com.example.app.MyViewModel
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.example.app.MyViewModel
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.example.app.MyActivity.getViewModel(MyActivity.kt:51)
        at com.example.app.MyActivity.onCreate(MyActivity.kt:55)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.InstantiationException: java.lang.Class<com.example.app.MyViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create
```

`MyViewModel.kt`

```kotlin
@HiltViewModel
class MyViewModel @Inject constructor(private val repository: MyRepository) {
   ...
}
```

`MyActivity.kt`

```kotlin
@AndroidEntryPoint
class MyActivity : AppCompatActivity() {
    private val viewModel by viewModels<MyViewModel>()
    ...
}
```

`BUILD.bazel`

```python
kt_android_library(
    name = "mylib",
	...
    plugins = [
       "//:androidx_hilt_compiler",
    ],
    deps = [
       "//:hilt-android",
	   "@maven//:androidx_hilt_hilt_lifecycle_viewmodel",
    ]
)
```

Plugin is declared as:

```python
kt_compiler_plugin(
    name = "androidx_hilt_compiler_plugin",
    id = "androidx.hilt.compiler",
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:androidx_hilt_hilt_compiler",
    ],
)
```

Previously opened issue #2147 is related to Gradle, but didn't found a solution for Bazel.

Dagger/Hilt version 2.37

**Comment by geaden** [comment]
Most likely the issue is related to using `kt_android_library` https://github.com/bazelbuild/rules_kotlin/issues/514

With `//:dagger` target the code is generated.

**Comment by danysantiago** [comment]
If `androidx_hilt_compiler_plugin` is for [`androidx.hilt:hilt-compiler`](https://maven.google.com/web/index.html?q=hilt-com#androidx.hilt:hilt-compiler) then that is the wrong processor to apply, the `ViewModel` functionality was moved to Hilt's main compiler during the alpha cycles. You should be applying the [`com.google.dagger:hilt-compiler`](https://search.maven.org/artifact/com.google.dagger/hilt-compiler/2.37/jar) instead.

Release migration steps in the release notes here: https://github.com/google/dagger/releases/tag/dagger-2.34

**Comment by geaden** [comment]
> I think this might also be due to something else...
> 
> If `androidx_hilt_compiler_plugin` is for [`androidx.hilt:hilt-compiler`](https://maven.google.com/web/index.html?q=hilt-com#androidx.hilt:hilt-compiler) then that is the wrong processor to apply, the `ViewModel` functionality was moved to Hilt's main compiler during the alpha cycles. You should be applying the [`com.google.dagger:hilt-compiler`](https://search.maven.org/artifact/com.google.dagger/hilt-compiler/2.37/jar) instead.
> 
> Release migration steps in the release notes here: [`dagger-2.34` (release)](https://github.com/google/dagger/releases/tag/dagger-2.34)

Thanks for pointing that out! I tried but with no luck, when using `kt_android_library` code generation is not working so far with `:hilt-android`.

**Comment by Chang-Eric** [comment]
Just to clarify, when you say `:hilt-android` is not working, is that the `:hilt-android` target from our `hilt_android_rules` macro? https://github.com/google/dagger/blob/f8892a4173aeb84b5dc2cf1351150e4b2c1bac9a/workspace_defs.bzl#L146

Also, how are you using that target? Is it a `dep` to your `kt_android_library` target or do you still have a `kt_compiler_plugin` defined in your code? FWIW, my guess is that `kt_compiler_plugin` is the wrong rule to use as they should all be `java_plugin`. That is probably why the original code didn't work. `:hilt-android` though should set up all the `java_plugin` targets for you though and export them, so you should just need to take a dep on that target for it to work.

**Comment by geaden** [comment]
> Just to clarify, when you say `:hilt-android` is not working, is that the `:hilt-android` target from our `hilt_android_rules` macro?
> 
> https://github.com/google/dagger/blob/f8892a4173aeb84b5dc2cf1351150e4b2c1bac9a/workspace_defs.bzl#L146
> 
> Also, how are you using that target? Is it a `dep` to your `kt_android_library` target or do you still have a `kt_compiler_plugin` defined in your code? FWIW, my guess is that `kt_compiler_plugin` is the wrong rule to use as they should all be `java_plugin`. That is probably why the original code didn't work. `:hilt-android` though should set up all the `java_plugin` targets for you though and export them, so you should just need to take a dep on that target for it to work.

As @danysantiago pointed out I was wrong using `kt_compiler_plugin` for hilt-compile. So I only left `//:hilt-android` as `dep` to `kt_android_library`. Please, take a look at [demo app](https://github.com/geaden/bazel_hilt_demo). Unfortunately, it's not compilable so far, as `kt_android_library` loses `android_library.exported_plugins` and required code is not generated.

**Comment by Chang-Eric** [comment]
I see, thanks. I see you already found the issue filed on the Kotlin rules side https://github.com/bazelbuild/rules_kotlin/issues/514 so I'm not sure there is much we can do on the Hilt side.

**Comment by geaden** [comment]
> I see, thanks. I see you already found the issue filed on the Kotlin rules side [bazelbuild/rules_kotlin#514](https://github.com/bazelbuild/rules_kotlin/issues/514) so I'm not sure there is much we can do on the Hilt side.

Ok, thanks! I'm closing the issue.
