### ISSUE TITLE
Hilt plugin crash with android gradle plugin 7 beta04

### ISSUE THREAD

**Issue by MTomczynski** [google/dagger#2700]
Versions:

Android Studio Arctic Fox Beta 4
Android tools gradle plugin 7.0.0-beta04
kotlin gradle plugin 1.5.10
dagger 2.37

Gradle build fails when applying hilt plugin to the module:
```
plugins {
    ...
    id("dagger.hilt.android.plugin")
    ...
}

```

Partial stacktrace
```
com/android/build/api/extension/AndroidComponentsExtension$DefaultImpls

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoClassDefFoundError: com/android/build/api/extension/AndroidComponentsExtension$DefaultImpls
	at dagger.hilt.android.plugin.HiltGradlePlugin.configureBytecodeTransformASM(HiltGradlePlugin.kt:258)
	at dagger.hilt.android.plugin.HiltGradlePlugin.configureHilt(HiltGradlePlugin.kt:89)
	at dagger.hilt.android.plugin.HiltGradlePlugin.access$configureHilt(HiltGradlePlugin.kt:59)
	at dagger.hilt.android.plugin.HiltGradlePlugin$apply$1.execute(HiltGradlePlugin.kt:66)
	at dagger.hilt.android.plugin.HiltGradlePlugin$apply$1.execute(HiltGradlePlugin.kt:59)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:112)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:95)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:74)

```

EDIT
If anyone needs a quick fix without downgrading AS it compiles without errors on alpha using Android Studio Bumblebee Canary 2 and AGP 7.1.0-alpha02.

**Comment by danysantiago** [comment]
The Android Gradle Plugin team is aware of the issue and a fix for this will be available in AGP 7 beta05.

**Comment by florianmski** [comment]
For people like me who need to downgrade, here is the link for the previous mac version (beta03) https://dl.google.com/edgedl/android/studio/ide-zips/2020.3.1.18/android-studio-2020.3.1.18-mac.zip

**Comment by ubuntudroid** [comment]
@danysantiago is there an issue that we can follow to get updates on the progress?

**Comment by n1k3c** [comment]
I think [this](https://github.com/google/dagger/issues/2634#issuecomment-863337870) will fix the issue

**Comment by roshanrajaratnam** [comment]
@danysantiago is there timeline on the fix?

**Comment by roshanrajaratnam** [comment]
Answer by @krzdabrowski on #2634 worked for me.

**Comment by danysantiago** [comment]
Sorry all for the issue, AGP is expected to have a release sometime next week for 7.0-beta, if all goes well. Meanwhile using 7.1-alpha02 should work.

And just for context, this is related to Hilt's bytecode transform which uses [AGP's new ASM pipeline](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/plugin/src/main/kotlin/dagger/hilt/android/plugin/HiltGradlePlugin.kt#L234) starting in 4.2 which is way more efficient and correct than the 'previous' version. The APIs for the ASM transform are planned to become stable soon in 7.0 so hopefully, in the near future this should be less of an issue.

**Comment by LachlanMcKee** [comment]
AGP 7.0.0-beta05 has been released and seems to have fixed this :)
