### ISSUE TITLE
IllegalArgumentException: SavedStateProvider with the given key is already registered

### ISSUE THREAD

**Issue by quanlt** [google/dagger#2709]
I tried to search for open/closed issse, and I've found 4 issues related to that stack trace. But my crash is different from those crashes because I do not use the keyed ViewModel. 
Currently, there are many crashes in prod env, and I can't reproduce them.

The crash stack trace
```Caused by java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
       at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.java:111)
       at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.java:50)
       at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:70)
       at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
       at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:84)
       at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:109)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.java:54)
       at androidx.lifecycle.ViewModelLazy.<init>(ViewModelLazy.java:41)
       at com.vingroup.vinid.ui.main.MainActivity.getMMainViewModel(MainActivity.java:2)
       at com.vingroup.vinid.ui.main.MainActivity.provideViewModel(MainActivity.java:179)
       at com.vingroup.vinid.ui.main.MainActivity.onCreate(MainActivity.java:226)
       at android.app.Activity.performCreate(Activity.java:7963)
       at android.app.Activity.performCreate(Activity.java:7952)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

My main activity
```
@AndroidEntryPoint
class MainActivity : BaseActivity<MainViewModel>() {
    private val mMainViewModel: MainViewModel by viewModels()
    override fun provideViewModel() = mMainViewModel
    private lateinit var mBinding: ActivityMainBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        mBinding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(mBinding.root)
        val pendingDeeplink = provideViewModel().getPendingDeeplink()
    }
}
```
the viewmodel
```class MainViewModel
@ViewModelInject constructor(
    private val context: Context,
    private val authRepository: AuthRepository,
    private val systemUtils: SystemUtils,
) : BaseViewModel() {
...
}
```

I'm using
``` // Hilt
    private const val hiltVersion = "2.32-alpha"
    private const val hiltExtAndroidX = "1.0.0-alpha03"
    const val hilt_android = "com.google.dagger:hilt-android:$hiltVersion"
    // Hilt with androidX
    const val hilt_androidX_common = "androidx.hilt:hilt-common:$hiltExtAndroidX"
    const val hilt_androidX_viewModel = "androidx.hilt:hilt-lifecycle-viewmodel:$hiltExtAndroidX"
    const val hilt_androidX_worker = "androidx.hilt:hilt-work:$hiltExtAndroidX"

    // kapt
    const val hilt_compiler = "com.google.dagger:hilt-compiler:$hiltVersion"
    const val hilt_androidX_compiler = "androidx.hilt:hilt-compiler:$hiltExtAndroidX"
```

**Comment by danysantiago** [comment]
You should update your libraries to the stable versions, and also the `androidx.hilt:hilt-lifecycle-viewmodel` artifact is deprecated and should be removed. It was merged into the core `hilt-android` artifact. See the migration notes here: https://github.com/google/dagger/releases/tag/dagger-2.34 and documentation here: https://dagger.dev/hilt/view-model
