### ISSUE TITLE
Var not initialized in application derived class

### ISSUE THREAD

**Issue by ecdpalma** [google/dagger#2778]
AS/AGP Bumblebee alpha04,
 gradle 7.1

Maybe related to https://github.com/google/dagger/issues/2766.

After updating from 2.37 to 2.38, I started getting this at runtime:

```
    java.lang.RuntimeException: Unable to create application com.myapp.android.App: kotlin.UninitializedPropertyAccessException: lateinit property someObject has not been initialized
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property someObject has not been initialized
        at com.myapp.android.App.getSomeObject(App.kt:41)
        at com.myapp.android.App.onCreate(App.kt:52)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

Simplified code:

```
@HiltAndroidApp()
open class App : Application() {

    @Inject
    lateinit var someObject: SomeObject

    override fun onCreate() {
        Log.d(TAG, "onCreate")
        super.onCreate()

        someObject.init()
    }
}
```

**Comment by Chang-Eric** [comment]
Thanks for the report, I believe this is happening due to #2784. Closing this as a duplicate assuming that is the case.
