### ISSUE TITLE
2.38: UninitializedPropertyAccessException for @Inject lateinit var

### ISSUE THREAD

**Issue by ImaginativeShohag** [google/dagger#2782]
The below code is working fine in version 2.37:

```kotlin
// SharedPref.kt
@Singleton
class SharedPref @Inject constructor(
   @ApplicationContext context: Context
) {
    // ...
}

// MainActivity.kt
@AndroidEntryPoint
class MainActivity : AppCompatActivity() {

    @Inject
    lateinit var sharedPref: SharedPref

    // ...
}
```

But, after upgrading to version 2.38 the following exception is thrown:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.imaginativeworld.simplemvvm.debug, PID: 24533
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.imaginativeworld.simplemvvm.debug/org.imaginativeworld.simplemvvm.ui.activities.main.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property sharedPref has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2925)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property sharedPref has not been initialized
        at org.imaginativeworld.simplemvvm.ui.activities.main.MainActivity.getSharedPref(MainActivity.kt:37)
        at org.imaginativeworld.simplemvvm.ui.activities.main.MainActivity.onCreate(MainActivity.kt:52)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6762) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
I/Process: Sending signal. PID: 24533 SIG: 9
```

I tried adding a provider for `SharedPref` class like this:

```kotlin
@InstallIn(SingletonComponent::class)
@Module
class AppModule {

    // ...

    @Provides
    fun provideSharedPref(@ApplicationContext context: Context): SharedPref {
        return SharedPref(context)
    }

}
```

But it also not working! What I am doing wrong?

**Comment by masterj3y** [comment]
I've got the same problem

**Comment by Chang-Eric** [comment]
Thanks for the report, I believe this is happening due to #2784. Closing this as a duplicate assuming that is the case.
