### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by appsapiconsole** [google/dagger#2833]
**Hilt Version 2.38.1**

Android Studio Arctic Fox | 2020.3.1 Patch 1
Build #AI-203.7717.56.2031.7621141, built on August 7, 2021

Hi,
I am using bottom navigation bar which have two fragments. In 1st Fragment button click Open New Activity to collect text from user. When user submit app than I use a Viewmodel to save data. 
But onSaveInstanceState app Crashed on below line

private val mHistoryImpViewModel: HistoryImpViewModel by viewModels() 

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.savedstate.SavedStateRegistry.runOnNextRecreation(SavedStateRegistry.java:168)
        at androidx.lifecycle.SavedStateHandleController.tryToAddRecreator(SavedStateHandleController.java:109)
        at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:71)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:84)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:109)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:171)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProviderExtensions.kt:55)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProviderExtensions.kt:42)
        at com.example.newtranslator.ui.home.fragments.TranslatorFragment.getMHistoryImpViewModel(TranslatorFragment.kt:50)
        at com.example.newtranslator.ui.home.fragments.TranslatorFragment.getTranslation(TranslatorFragment.kt:230)
        at com.example.newtranslator.ui.home.fragments.TranslatorFragment.access$getTranslation(TranslatorFragment.kt:46)
        at com.example.newtranslator.ui.home.fragments.TranslatorFragment$setupTranslationData$1$1$1.invokeSuspend(TranslatorFragment.kt:114)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:377)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.example.newtranslator.ui.home.fragments.TranslatorFragment.setupTranslationData(TranslatorFragment.kt:104)
        at com.example.newtranslator.ui.home.fragments.TranslatorFragment.textResultLauncher$lambda-2(TranslatorFragment.kt:94)
        at com.example.newtranslator.ui.home.fragments.TranslatorFragment.$r8$lambda$PknFu9mhqWvRKakzo39nq8JooiE(Unknown Source:0)
        at com.example.newtranslator.ui.home.fragments.TranslatorFragment$$ExternalSyntheticLambda12.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:3024)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:568)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1331)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2772)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2722)
2021-08-31 17:31:53.908 25325-25325/com.example.newtranslator E/AndroidRuntime:     at androidx.fragment.app.Fragment.performStart(Fragment.java:3028)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:568)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1331)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2772)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2722)
        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:273)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:486)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8231)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3845)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8587)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by danysantiago** [comment]
Can you share some code?

It seems a ViewModel is being access too early (in `onActivityResult`) and the saved state handle has not been restored yet. There also seem to be a coroutine between the result callback and the ViewModel being accessed. Are you using the [LifecycleScope](https://developer.android.com/topic/libraries/architecture/coroutines#lifecyclescope) ? Can you try delaying accessing your ViewModel?

This does not seem related to Hilt as it can happen with any other ViewModel.

**Comment by appsapiconsole** [comment]
Yes Try it by showing progress dialog for 1 second after that accessing viewmodel model it working fine.
