### ISSUE TITLE
hiltJavaCompileDebug breaks build with no value present error

### ISSUE THREAD

**Issue by hcknl** [google/dagger#2835]
Hello,

Tried many things with a very old project but couldn't be able to run hilt on :app: module.

However the config I tried works very well on the feature module.

Since the sharing logs not allowed, I am gonna write some of it.

:module: HiltAndroidApp and hilt modules -> core module with hilt modules (from maven repo) works very well.

If I move this logic to app module (very old, mostly java and a few kotlin) build breaks with below error.

App:hiltJavaCompileDevDebug -> java.util.NoSuchElementException: No value present.

Any recommendations will be appreciated. Thanks.

```
at jdk compiler/com.sun.tools capi.JavacTaskimpl.doCall(JavacTaskimpl.java:100)

Caused by: java.util.NoSuchElementException: No value present

at dagger.internal.codegen.binding. Key Factory.binding MethodKeyType(KeyFactory.java:222)

at dagger.internal.codegen.binding.KeyFactory.for Binding Method (KeyFactory.java:182)

at dagger.internal.codegen.binding Key Factory.forBindsMethod (KeyFactory.java:148)

at dagger.internal.codegen.binding.Delegate Declaration $Factory.create(Delegate Declaration.java:85) at dagger internal.codegen.binding.Module Descriptor$Factory.create Uncached (Module Descriptor java:157)

at dagger.internal.codegen.base.Util.reentrantComputelfAbsent (Util.java:33)

at dagger.internal.codegen.binding Module Descriptor$Factory.create (Module Descriptor.java:138)

at com.google.common.collect.Iterators$6.transform(Iterators.java:783)

at com.google.common.collect.Transformedlterator.next(Transformed iterator.java:47) at com.google.common.graph.Traverser$GraphTraverser.depth FirstPreOrder (Traverser.java:360)

at dagger.internal.codegen.binding.Module Descriptor$Factory.transitive Modules (ModuleDescriptor.java:217)

at dagger.internal.codegen.binding ComponentDescriptorFactory.create(Component DescriptorFactory.java:144)

at dagger.internal.codegen.binding.ComponentDescriptorFactory.rootComponent Descriptor (ComponentDescriptorFactory.java:78) at dagger.internal.codegen.Component ProcessingStep processRootComponent (Component ProcessingStep.java:110)

at dagger.internal.codegen.Component ProcessingStep.process (Component Processing Step.java:95)

at dagger.internal.codegen.Component ProcessingStep.process (Component Processing Step.java:55)

at dagger.internal.codegen.validation.XTypeChecking Processing Step lambda$process$0(XTypeChecking Processing at com.google.common.collect.RegularimmutableMap.forEach(RegularlmmutableMap.java:185)

Step.java:55)

at dagger.internal codegen validation XTypeChecking Processing Step.process (XTypeChecking Processing Step.java:52)

at dagger.internal.codegen.validation.XTypeChecking Processing Step.process (XTypeChecking Processing Step.java:39)

at dagger.shaded.androidx.room.compiler.processing.javac.Javac BasicAnnotation Processor $DelegatingStoneell

163)
```

**Comment by wanyingd1996** [comment]
Hi, the error message seems a little bit truncated, I'm suspecting some @MapKey annotated annotation isn't set up correctly (possibly missing a key-value entry inside of it). Is it possible for you to provide a sample project for us to reproduce the error? 

Meanwhile, I'm adding debug message to cover some of the `NoSuchElementException` case, once that's out, will let you know.
