### ISSUE TITLE
[Hilt] Android Hilt : java.lang.RuntimeException: Unable to instantiate application

### ISSUE THREAD

**Issue by namlxcntt** [google/dagger#2846]
I faced a problem deploying Hilt Android App.
 Below is my Application code
```
  `@HiltAndroidApp
class MyApplication : Application() {
    override fun onCreate() {
        super.onCreate()
    }
}
```

AndroidManifest.xml 
```
`<application
        android:name=".MyApplication"
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
   `
```

And here is the error I got
` java.lang.RuntimeException: Unable to instantiate application com.lxn.toeic4u.MyApplication: java.lang.ClassNotFoundException: Didn't find class "com.lxn.toeic4u.MyApplication" on path: DexPathList[[zip file "/data/app/com.lxn.toeic4u-DySUG_JomE2lqI2qdmyO9w==/base.apk"],nativeLibraryDirectories=[/data/app/com.lxn.toeic4u-DySUG_JomE2lqI2qdmyO9w==/lib/x86, /data/app/com.lxn.toeic4u-DySUG_JomE2lqI2qdmyO9w==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1226)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

I don't know why can't find my application class.
Can someone help me?

**Comment by Chang-Eric** [comment]
Sorry, but I don't think this is related to Hilt. This could be a multidex issue or something with your build system, but not sure we can help out much more.

**Comment by Spider8019** [comment]
Can you please elaborate more about the possibilites of mistakes
