### ISSUE TITLE
Dagger 2.1-SNAPSHOT and Eclipse compile error

### ISSUE THREAD

**Issue by rkapsi** [google/dagger#290]
I don't have much more info than this stack trace but I'm suddenly seeing this error in Eclipse (4.5.1) in conjunction with Dagger 2.1-SNAPSHOT.

My best guess is that it has something to do with differences in how Eclipse's `org.eclipse.jdt.internal.compiler.apt.model.TypesImpl` is implemented vs. javac.

```
org.eclipse.jdt.internal.compiler.apt.model.TypesImpl.asMemberOf(TypesImpl.java:129)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.injectionSiteForInjectMethod(MembersInjectionBinding.java:154)
```

```
!ENTRY org.eclipse.jdt.apt.pluggable.core 4 1 2016-01-05 14:52:27.388
!MESSAGE Exception thrown by Java annotation processor dagger.internal.codegen.ComponentProcessor@6a740d75
!STACK 0
java.lang.IllegalArgumentException: element protected abstract void initChannel(C) throws java.lang.Exception is not a member of the containing type io.netty.channel.ChannelInitializer<io.netty.channel.socket.SocketChannel> nor any of its superclasses
	at org.eclipse.jdt.internal.compiler.apt.model.TypesImpl.asMemberOf(TypesImpl.java:129)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.injectionSiteForInjectMethod(MembersInjectionBinding.java:154)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.access$100(MembersInjectionBinding.java:136)
	at dagger.internal.codegen.MembersInjectionBinding$Factory$4.visitExecutableAsMethod(MembersInjectionBinding.java:318)
	at dagger.internal.codegen.MembersInjectionBinding$Factory$4.visitExecutableAsMethod(MembersInjectionBinding.java:314)
	at javax.lang.model.util.ElementKindVisitor6.visitExecutable(ElementKindVisitor6.java:340)
	at org.eclipse.jdt.internal.compiler.apt.model.ExecutableElementImpl.accept(ExecutableElementImpl.java:59)
	at javax.lang.model.util.AbstractElementVisitor6.visit(AbstractElementVisitor6.java:97)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.getInjectionSites(MembersInjectionBinding.java:248)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.hasInjectedMembers(MembersInjectionBinding.java:179)
	at dagger.internal.codegen.InjectBindingRegistry.tryRegisterConstructor(InjectBindingRegistry.java:236)
	at dagger.internal.codegen.InjectBindingRegistry.tryRegisterConstructor(InjectBindingRegistry.java:215)
	at dagger.internal.codegen.InjectProcessingStep$1.visitExecutableAsConstructor(InjectProcessingStep.java:64)
	at dagger.internal.codegen.InjectProcessingStep$1.visitExecutableAsConstructor(InjectProcessingStep.java:60)
	at javax.lang.model.util.ElementKindVisitor6.visitExecutable(ElementKindVisitor6.java:334)
	at org.eclipse.jdt.internal.compiler.apt.model.ExecutableElementImpl.accept(ExecutableElementImpl.java:59)
	at dagger.internal.codegen.InjectProcessingStep.process(InjectProcessingStep.java:59)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:171)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:909)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:367)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:179)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:304)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by rkapsi** [comment]
Here's a repro. 

```java
// io.netty.channel.ChannelInitializer
public abstract class ChannelInitializer<T extends Channel> {
  protected abstract void initChannel(T ch) throws Exception;
}

// This works (use Channel for T, see above)
public class MyChannel extends ChannelInitializer<Channel> {

  @Inject 
  public MyChannel() {}

  @Override
  protected void initChannel(Channel ch) throws Exception {}
}

// This doesn't (use a subclass of Channel for T)
public class MyChannel extends ChannelInitializer<SocketChannel> {

  @Inject 
  public MyChannel() {}

  @Override
  protected void initChannel(SocketChannel ch) throws Exception {}
}
```

**Comment by gk5885** [comment]
Does this work with `javac`?

**Comment by rkapsi** [comment]
Yes, no problems with javac

**Comment by gk5885** [comment]
@emcmanus, is this one of the Eclipse bugs for which you have developed a workaround?

**Comment by gk5885** [comment]
Whoops.  Wrong person.  @eamonnmcmanus is who I was looking for.

**Comment by eamonnmcmanus** [comment]
It looks very similar to the Eclipse bug that caused me to add [this workaround](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/EclipseHack.java#L95) to AutoValue. Types.asMemberOf is unreliable in Eclipse. In the cases I encountered, it failed to allow for a method to be inherited from a superinterface rather than a superclass. The example here looks different but I'm guessing Types.asMemberOf is also broken in cases like this that involve type variables. It might well be possible to use a similar workaround, though it's a pain because you essentially need different code paths for javac and the Eclipse compiler.

**Comment by afdia** [comment]
I have noticed that with the current 2.1-SNAPSHOT, dagger-compiler contains many classes from other packages such as org.eclipse.*, which it did not in 2.0.2.

Is this intentional? Perhaps this change is causing the issue.

**Comment by tbroyer** [comment]
@afdia Oh, this is actually #228: the bug has been fixed upstream (google-java-format) but there hasn't been a new release since then; some changes might also be needed in Dagger POMs themselves.

**Comment by afdia** [comment]
Thanks for pointing me to the other issue, I've missed is due to its title.

**Comment by DDJarod** [comment]
This might be fixed in eclipse 4.6 M3.
[Bug 382590 - TypesImpl.asMemberOf must also work with a subclass and its superclass' element] (https://bugs.eclipse.org/bugs/show_bug.cgi?id=382590)
At least for me with eclipse 4.5.1 and gradle 2.2 the compile error is still there

**Comment by ronshapiro** [comment]
Can anyone confirm that this is fixed in eclipse?

**Comment by DDJarod** [comment]
yes I can, Eclipse 4.6 with gradle 2.2 works fine
