### ISSUE TITLE
Confusing error when type cannot be resolved

### ISSUE THREAD

**Issue by vRallev** [google/dagger#2920]
We're seeing
```
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at dagger.internal.codegen.binding.SubcomponentDeclaration$Factory.forModule(SubcomponentDeclaration.java:72)
	at dagger.internal.codegen.binding.ModuleDescriptor$Factory.createUncached(ModuleDescriptor.java:178)
	at dagger.internal.codegen.base.Util.reentrantComputeIfAbsent(Util.java:33)
	at dagger.internal.codegen.binding.ModuleDescriptor$Factory.create(ModuleDescriptor.java:138)
```
when a type cannot be resolved. We have a very large repository and dependency graph and therefore I cannot share the project. I think this error is caused by a module include:
```kotlin
@Module(includes = [Abc::class, Def::class])
```
The problem is that the modules `Abc` and `Def` are imported from other Gradle modules through an `implementation` dependency, meaning other modules downstream that compile the Dagger components don't see the module types, because they're not part of the compile classpath.

This certainly is an issue from our side and the fix is trivial. However, the error itself is very confusing and I wish there would be a better message like "unknown type".

**Comment by bcorso** [comment]
This should now be fixed. The fix will be included in the next release (v2.41).
