### ISSUE TITLE
Hilt Class Cast exception in aar library when minifyEnabled true in library.

### ISSUE THREAD

**Issue by wasim-apalya** [google/dagger#2931]
I got a class cast exception when I am using hilt in android Library module It works fine when project is added as normal module but when built aar file of the library module and used in separate project. it throws a runtime exception .

java.lang.RuntimeException: Unable to start activity ComponentInfo{pckname.musicsample/pckname.dev.ui.MusicHomeActivity}: java.lang.ClassCastException: pckname.musicsample.DaggerApp_HiltComponents_SingletonC$ActivityCImpl cannot be cast to f.b
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2740)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6358)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
     Caused by: java.lang.ClassCastException: com.apalya.vimusic.musicsample.DaggerApp_HiltComponents_SingletonC$ActivityCImpl cannot be cast to f.b
        at f.a$a.onContextAvailable(Unknown Source)
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
        at com.apalya.myplexmusic.dev.ui.MusicHomeActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:6840)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6358)

**Comment by PopFisher** [comment]
Encountering the same problem, after enabling confusion（minifyEnabled true ）, the aar package generated by the submodule crashes when running

**Comment by tarukhan19** [comment]
I am also facing same issue, did anyone get any solution?
