### ISSUE TITLE
 onAttach called multiple times with different Context! Hilt Fragments should not be retained.

### ISSUE THREAD

**Issue by izhakl** [google/dagger#3114]
Hi I'm stuck in a situation where I have no way to fix it.
I have viewpager2 with fragmentAdapter.
When I change Theme from day to night mode or reverse then I go back to the app and try to click on last tab and then first or second tab the app crashes.

```
2021-12-15 14:11:25.519 32697-32697/com.test.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.test, PID: 32697
    java.lang.IllegalStateException: onAttach called multiple times with different Context! Hilt Fragments should not be retained.
        at dagger.hilt.internal.Preconditions.checkState(Preconditions.java:83)
        at com.test.android.module.home.Hilt_TestOneFragment.onAttach(Hilt_TestOneFragment.java:48)
        at androidx.fragment.app.Fragment.onAttach(Fragment.java:1783)
        at com.test.android.module.home.Hilt_TestOneFragment.onAttach(Hilt_TestOneFragment.java:38)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
        at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:353)
        at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:284)
        at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:72)
        at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7867)
        at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:893)
        at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8902)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8860)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1647)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1395)
        at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1124)
        at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1969)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5476)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:728)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7971)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

```

my code : 

BaseActivity:
```
@AndroidEntryPoint
abstract class BaseActivity: AppCompatActivity(),
    NavigationListener, ConnectivityReceiver.ConnectivityReceiverListener{

    companion object {
        private val TAG: String = BaseActivity::class.simpleName.toString()
    }


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        bindViewModel()
    }


    override fun onStart() {
        super.onStart()
        receiver = ConnectivityReceiver()
        val intentFilter = IntentFilter()
        intentFilter.addAction("android.net.conn.CONNECTIVITY_CHANGE");
        intentFilter.addAction(BluetoothAdapter.ACTION_STATE_CHANGED)
        intentFilter.addAction(LocationManager.PROVIDERS_CHANGED_ACTION)
        intentFilter.addAction(AIR_MODE)

        ConnectivityReceiver.connectivityReceiverListener = this
        registerReceiver(receiver, intentFilter)
    }

    override fun onStop() {
        unregisterReceiver(receiver)
        ConnectivityReceiver.connectivityReceiverListener = null
        super.onStop()
    }
    
    /**
     * handle dark/light mode
     */
    override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        when (resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK) {
            Configuration.UI_MODE_NIGHT_YES ->
                AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO)
            Configuration.UI_MODE_NIGHT_NO ->
                AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)
        }
    }

  

    /**
     * handle font size
     */
    override fun attachBaseContext(newBase: Context?) {
        super.attachBaseContext(newBase)
        val newOverride = Configuration(newBase?.resources?.configuration)
        if (newOverride.fontScale > 1.30){
            newOverride.fontScale = 1.30f
        }
        applyOverrideConfiguration(newOverride)
    }

    /**
     *  set locale (rtl or ltr) app -- if default language diff language from device  , we need to do recreate()
     */
    private fun setLocale() {
        val locale = Locale(mLanguageManager.getLanguageCodeOrDefault())
        Locale.setDefault(locale)
        val configuration = resources.configuration
        configuration.setLocale(locale)
        createConfigurationContext(configuration)
    }

}

```

HomeActivity:

```
class HomeActivity : BaseActivity() {

    private lateinit var appBarConfiguration: AppBarConfiguration
    private lateinit var binding: ActivityHomeBinding


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityHomeBinding.inflate(layoutInflater)
        setContentView(binding.root)
    }

    override fun onSupportNavigateUp(): Boolean {
        val navController = findNavController(R.id.nav_host_fragment_content_home)
        return navController.navigateUp(appBarConfiguration)
                || super.onSupportNavigateUp()
    }

    override fun onNext(action: Action) {

    }
}
```

Home Fragment :

```
@AndroidEntryPoint
class HomeFragment : BasePwsDisconnectFragment<HomeViewModel>(), View.OnClickListener {
    ////////////////////////////////////////////////////////////////////////////////////////////////
    // Public Constants
    ////////////////////////////////////////////////////////////////////////////////////////////////

    ////////////////////////////////////////////////////////////////////////////////////////////////
    // Constants
    ////////////////////////////////////////////////////////////////////////////////////////////////

    override fun getViewModel(): Class<HomeViewModel> {
        return HomeViewModel::class.java
    }

  

    private lateinit var binding: FragmentHomeBinding


    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        binding = FragmentHomeBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        initView()
    }


  


   

    private fun initTabs(fragmentList: List<SuperFeatureType?>){
        val pagerAdapter =
            TabItemPagerAdapter(this, fragmentList,requireContext())
        binding.vpWifiTutorial.adapter = pagerAdapter

        TabLayoutMediator(binding.tlWifiTutorial, binding.vpWifiTutorial)
        { tab, position ->
            tab.customView = pagerAdapter.getTabView(position)
        }.attach()

        binding.tlWifiTutorial.addOnTabSelectedListener(object : OnTabSelectedListener {
            override fun onTabSelected(tab: TabLayout.Tab) {
                val customView = tab.customView as ConstraintLayout
                val tabTextView = customView.getChildAt(1) as TextView
                tabTextView.setTypeface(null, Typeface.BOLD)
            }

            override fun onTabUnselected(tab: TabLayout.Tab) {
                val customView = tab.customView as ConstraintLayout
                val tabTextView = customView.getChildAt(1) as TextView
                tabTextView.setTypeface(null, Typeface.NORMAL)
            }

            override fun onTabReselected(tab: TabLayout.Tab) {}
        })
    }
```

The fragment within the list crash:

```
@AndroidEntryPoint(BasePwsDisconnectFragment::class)
class TestOneFragment() : Hilt_TestOneFragment<HomeViewModel>(), View.OnClickListener {
    

    ////////////////////////////////////////////////////////////////////////////////////////////////
    // Definitions
    ////////////////////////////////////////////////////////////////////////////////////////////////

    ////////////////////////////////////////////////////////////////////////////////////////////////
    // Fields
    ////////////////////////////////////////////////////////////////////////////////////////////////

    private lateinit var binding: FragmentTestOneBinding
    ////////////////////////////////////////////////////////////////////////////////////////////////
    // Methods
    ////////////////////////////////////////////////////////////////////////////////////////////////

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        binding = FragmentTestOneBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        initView()
    }

   
    override fun getViewModel(): Class<HomeViewModel> {
        return HomeViewModel::class.java
    }
```
I would really love to help 👍 

  

}

**Comment by bcorso** [comment]
This error message happens when you try to re-attach a fragment to a different instance of an activity than what it was originally created with.

```
java.lang.IllegalStateException: onAttach called multiple times with different Context! Hilt Fragments should not be retained.
```

This isn't allowed in Hilt is because the `@Inject` fields of the fragment have already been created with access to the original activity.

I'm not too familiar with ViewPager, but the fix would be to either ensure the Fragments are attached to the same activity instance or ensure that whenever you get a new activity instance you also create new Fragment instances.

**Comment by izhakl** [comment]
> This error message happens when you try to re-attach a fragment to a different instance of an activity than what it was originally created with.
> 
> ```
> java.lang.IllegalStateException: onAttach called multiple times with different Context! Hilt Fragments should not be retained.
> ```
> 
> This isn't allowed in Hilt because the `@Inject` fields of the fragment have already been created with access to the original activity.
> 
> I'm not too familiar with ViewPager, but the fix would be to either ensure the Fragments are attached to the same activity instance or ensure that whenever you get a new activity instance you also create new Fragment instances.

Thanks for the answer, that was the problem..I always sent to viewpager the same instance of the fragments. Thank you!
