### ISSUE TITLE
java.lang.reflect.InvocationTargetException | 2.40.5

### ISSUE THREAD

**Issue by ektefa** [google/dagger#3193]
Kotlin: 1.6.10
Dagger: 2.40.5
AS: BumbleBee 2021.1.1
AGP: 7.1.0
Gradle: 7.2

`Caused by: java.lang.StackOverflowError
        at kotlin.SynchronizedLazyImpl.<init>(LazyJVM.kt:55)
        at kotlin.LazyKt__LazyJVMKt.lazy(LazyJVM.kt:21)
        at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacType.<init>(JavacType.kt:40)
        at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacDeclaredType.<init>(JavacDeclaredType.kt:33)
        at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacDeclaredType.<init>(JavacDeclaredType.kt:61)
        at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacAnnotationValueKt$UNWRAP_VISITOR$1.visitType(JavacAnnotationValue.kt:125)
        at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacAnnotationValueKt$UNWRAP_VISITOR$1.visitType(JavacAnnotationValue.kt:47)
        at jdk.compiler/com.sun.tools.javac.code.Attribute$Class.accept(Attribute.java:139)
        at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacAnnotationValueKt$UNWRAP_VISITOR$1$visitArray$1$1.invoke(JavacAnnotationValue.kt:88)
        at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacAnnotationValue$value$2.invoke(JavacAnnotationValue.kt:42)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacAnnotationValue.getValue(JavacAnnotationValue.kt:42)
        at dagger.spi.shaded.androidx.room.compiler.processing.XAnnotationValue.asType(XAnnotationValue.kt:42)
        at dagger.spi.shaded.androidx.room.compiler.processing.XAnnotationValue.asTypeList(XAnnotationValue.kt:45)
        at dagger.spi.shaded.androidx.room.compiler.processing.XAnnotation.getAsTypeList(XAnnotation.kt:57)
        at dagger.internal.codegen.base.ComponentAnnotation.modules(ComponentAnnotation.java:151)
        at dagger.internal.codegen.base.AutoValue_ComponentAnnotation.modules(AutoValue_ComponentAnnotation.java:58)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:129)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
        at dagger.internal.codegen.binding.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:93)
`

**Comment by danysantiago** [comment]
Dagger shouldn't crash like this, but it seems like you have a subcomponent whose parent is the same subcomponent (or a common one in a chain of components). In other words you have a cycle in your parent - child subcomponents declarations.

**Comment by ektefa** [comment]
> Dagger shouldn't crash like this, but it seems like you have a subcomponent whose parent is the same subcomponent (or a common one in a chain of components). In other words you have a cycle in your parent - child subcomponents declarations.

Exactly, there was a cycle casuing this.
My bad, sorry. Close this please.
Thanks for your help.
