### ISSUE TITLE
2.40.5 broken in eclipse

### ISSUE THREAD

**Issue by sb1121** [google/dagger#3198]
I have a repro at https://github.com/sb1121/dagger-test/tree/dagger-2.40.5

To try it yourself, `./gradlew eclipse` to set it up, and then import projects.

The bug seems to affect 2.40.2 to 2.40.5.

```
java.lang.Exception: java.lang.IllegalStateException: Unable to create variable element for engine
        at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:172)
        at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
        at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)
        at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
        at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:950)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
        at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:379)
        at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
        at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:311)
        at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:272)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:198)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:853)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:232)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:281)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:334)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:337)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:389)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:410)
        at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:160)
        at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:251)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalStateException: Unable to create variable element for engine
        at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacProcessingEnv.wrapVariableElement(JavacProcessingEnv.kt:282)
        at dagger.spi.shaded.androidx.room.compiler.processing.compat.XConverters.toXProcessing(XConverters.kt:116)
        at dagger.internal.codegen.binding.DependencyRequestFactory.forRequiredResolvedVariable(DependencyRequestFactory.java:165)
        at dagger.internal.codegen.binding.DependencyRequestFactory.forRequiredResolvedVariable(DependencyRequestFactory.java:157)
        at dagger.internal.codegen.binding.BindingFactory.injectionBinding(BindingFactory.java:137)
        at dagger.internal.codegen.validation.InjectBindingRegistryImpl.tryRegisterConstructor(InjectBindingRegistryImpl.java:277)
        at dagger.internal.codegen.validation.InjectBindingRegistryImpl.tryRegisterInjectConstructor(InjectBindingRegistryImpl.java:253)
        at dagger.internal.codegen.InjectProcessingStep.process(InjectProcessingStep.java:66)
        at dagger.internal.codegen.validation.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:65)
        at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:68)
        at dagger.internal.codegen.validation.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:55)
        at dagger.internal.codegen.validation.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:40)
        at dagger.spi.shaded.androidx.room.compiler.processing.CommonProcessorDelegate.processRound(XBasicAnnotationProcessor.kt:114)
        at dagger.spi.shaded.androidx.room.compiler.processing.javac.JavacBasicAnnotationProcessor.process(JavacBasicAnnotationProcessor.kt:63)
        at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
        ... 24 more

```

**Comment by bcorso** [comment]
Following the stacktrace, it looks like the issue comes from the XProcessing library in [`JavacProcessingEnv.java`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/room-compiler-processing/src/main/java/androidx/room/compiler/processing/javac/JavacProcessingEnv.kt;l=288-290) where it tries to match a given parameter with one in the enclosing method's parameter list:

```
executableElement.parameters.find { param ->
                    param.element === element
                } ?: error("Unable to create variable element for $element")
```

I tried your repro project in Intellij and everything passes, so my guess is that the difference lies in Eclipse's fork of the javac compiler which is known to have subtle differences/bugs from javac.

We may be able to work around this issue by matching on the parameter name instead of the element (since the parameter name should be unique within the list of method parameters). Let me bring this up with the Room team (who owns the XProcessing library) and I'll get back to you.

**Comment by bcorso** [comment]
Filed a bug for XProcessing here: https://issuetracker.google.com/217598326

**Comment by bcorso** [comment]
Looks like the XProcessing bug is fixed now, so Dagger will include the fix in the next Dagger release.
