### ISSUE TITLE
dagger.lint.DaggerKotlinIssueDetector failing in recent versions of dagger/hilt/agp

### ISSUE THREAD

**Issue by ColtonIdle** [google/dagger#3201]
In the past few days I've been upgrading my repo from chipmunk c5 and a bunch of dependencies. I haven't been able to figure out the exact culprit, but when I run lint, lint crashes internally seemingly. It gives me this error.

```
The crash seems to involve the detector dagger.lint.DaggerKotlinIssueDetector.
You can try disabling it with something like this:
    android {
        lintOptions {
            disable "JvmStaticProvidesInObjectDetector", "FieldSiteTargetOnQualifierAnnotation", "ModuleCompanionObjects", "ModuleCompanionObjectsNotInModuleParent"
        }
    }
```

I'll try to report back with more info but let me know if this seems like an agp thing or dagger.

**Comment by danysantiago** [comment]
It can be a both (AGP or Dagger) issue, we'll have to try it out, or if you do and get more info, let us know.

**Comment by fbarthelery** [comment]
I think it's AGP. I'm using 7.2.0-beta01 and I got this stacktrace
```
 Task :app:lintAnalyzeDebug
java.lang.NoSuchMethodError: 'java.util.List org.jetbrains.uast.UField.getAnnotations()'
	at dagger.lint.DaggerKotlinIssueDetector$createUastHandler$1.visitField(DaggerKotlinIssueDetector.kt:166)
	at com.android.tools.lint.client.api.UElementVisitor$DispatchPsiVisitor.visitField(UElementVisitor.kt:671)
	at org.jetbrains.uast.kotlin.KotlinUField.accept(KotlinUField.kt:51)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:23)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:42)
	at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:23)
	at org.jetbrains.uast.UFile$DefaultImpls.accept(UFile.kt:87)
	at org.jetbrains.uast.kotlin.KotlinUFile.accept(KotlinUFile.kt:14)
	at com.android.tools.lint.client.api.UElementVisitor$visitFile$3.run(UElementVisitor.kt:284)
	at com.android.tools.lint.client.api.LintClient.runReadAction(LintClient.kt:1784)
	at com.android.tools.lint.client.api.LintDriver$LintClientWrapper.runReadAction(LintDriver.kt:2766)
	at com.android.tools.lint.client.api.UElementVisitor.visitFile(UElementVisitor.kt:280)
	at com.android.tools.lint.client.api.LintDriver$visitUastDetectors$1.run(LintDriver.kt:2083)
	at com.android.tools.lint.client.api.LintClient.runReadAction(LintClient.kt:1784)
	at com.android.tools.lint.client.api.LintDriver$LintClientWrapper.runReadAction(LintDriver.kt:2766)
	at com.android.tools.lint.client.api.LintDriver.visitUastDetectors(LintDriver.kt:2083)
	at com.android.tools.lint.client.api.LintDriver.visitUast(LintDriver.kt:2042)
	at com.android.tools.lint.client.api.LintDriver.runFileDetectors(LintDriver.kt:1417)
	at com.android.tools.lint.client.api.LintDriver.checkProject(LintDriver.kt:1181)
	at com.android.tools.lint.client.api.LintDriver.checkProjectRoot(LintDriver.kt:644)
	at com.android.tools.lint.client.api.LintDriver.access$checkProjectRoot(LintDriver.kt:159)
	at com.android.tools.lint.client.api.LintDriver$analyzeOnly$1.invoke(LintDriver.kt:458)
	at com.android.tools.lint.client.api.LintDriver$analyzeOnly$1.invoke(LintDriver.kt:451)
	at com.android.tools.lint.client.api.LintDriver.doAnalyze(LintDriver.kt:518)
	at com.android.tools.lint.client.api.LintDriver.analyzeOnly(LintDriver.kt:451)
	at com.android.tools.lint.LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:243)
	at com.android.tools.lint.LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:243)
	at com.android.tools.lint.LintCliClient.run(LintCliClient.kt:285)
	at com.android.tools.lint.LintCliClient.run$default(LintCliClient.kt:268)
	at com.android.tools.lint.LintCliClient.analyzeOnly(LintCliClient.kt:243)
	at com.android.tools.lint.Main.run(Main.java:1661)
	at com.android.tools.lint.Main.run(Main.java:275)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.android.build.gradle.internal.lint.AndroidLintWorkAction.invokeLintMainRunMethod(AndroidLintWorkAction.kt:93)
	at com.android.build.gradle.internal.lint.AndroidLintWorkAction.runLint(AndroidLintWorkAction.kt:82)
	at com.android.build.gradle.internal.lint.AndroidLintWorkAction.execute(AndroidLintWorkAction.kt:64)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by danysantiago** [comment]
Ah, this looks familiar, I had a change (https://github.com/google/dagger/pull/2639) to move from that method since it was marked as `@Deprecated` but never merged it since I had bundle it with the `Vendor` API. I think it's time to merge that change.

**Comment by gagan-hotstar** [comment]
@danysantiago is this change released? I am also getting the same error while updating to AGP 7.2.0-beta01

**Comment by gagan-hotstar** [comment]
@danysantiago thanks, any rough ETA for the next release, this will be helpful in upgrading the AGP

**Comment by danysantiago** [comment]
Umm, sometime this month. 🙂

We are just trying to also finish a few more fixes before making a release. Thank you for your patience!
