### ISSUE TITLE
SavedStateViewModelFactory constructed with empty constructor supports only calls to create(modelClass: Class<T>, extras: CreationExtras)

### ISSUE THREAD

**Issue by sebastinto** [google/dagger#3226]
I am getting `SavedStateViewModelFactory constructed with empty constructor supports only calls to create(modelClass: Class, extras: CreationExtras)` errors when `createBiometricPrompt()` is called in the code below:

```kotlin
@HiltAndroidApp
class MyApplication : Application() {

    override fun onCreate() {
        super.onCreate()

        // Logging
        Timber.plant(Timber.DebugTree())
    }
}
```

```kotlin
@OptIn(
    ExperimentalAnimationApi::class,
    ExperimentalMaterialApi::class,
    ExperimentalComposeUiApi::class,
    ExperimentalFoundationApi::class
)
@AndroidEntryPoint
class MainActivity : FragmentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        WindowCompat.setDecorFitsSystemWindows(window, false)
        setContent {
            MyTheme() {
                ProvideWindowInsets {
                    Navigation()
                }
            }
        }
    }
```

```kotlin
@OptIn(
    ExperimentalAnimationApi::class,
    ExperimentalMaterialApi::class,
    ExperimentalComposeUiApi::class,
    ExperimentalFoundationApi::class
)
@Composable
fun Navigation(
   // other params...
    authViewModel: AuthViewModel = hiltViewModel(),
   // other params...
) {

    Root( ) { scaffoldState, coroutineScope ->
        AnimatedNavHost(
            navController = navController,
            startDestination = //...
        ) {
          
            composable(route = Screen.Auth.name) {
                // fixme: this crashes with `SavedStateViewModelFactory constructed with empty constructor supports only calls to create(modelClass: Class, extras: CreationExtras)`
                BiometricPromptDialog(
                    biometricPrompt = authViewModel.createBiometricPrompt(
                        activity = LocalContext.current as FragmentActivity,
                        onSuccess = {
                            navController.navigate(/* some screen */) {
                                // remove biometric screen from back stack
                                popUpTo(/* some screen *) {
                                    inclusive = true
                                }
                            }
                        }
                    ),
                      // other params...
            }
            // other composable()
        }
    }
}
```

```kotlin
@HiltViewModel
class AuthViewModel @Inject constructor(
    @BiometricSupported isBiometricAuthSupported: Boolean,
    @IoDispatcher private val ioDispatcher: CoroutineDispatcher,
    private val preferenceDataStore: PreferenceDataStore
) : ViewModel() {

// other code...

fun createBiometricPrompt(
        activity: FragmentActivity,
        onSuccess: (BiometricPrompt.AuthenticationResult) -> Unit
    ): BiometricPrompt {
        val executor = ContextCompat.getMainExecutor(activity)

        val callback = object : BiometricPrompt.AuthenticationCallback() {
            override fun onAuthenticationError(errCode: Int, errString: CharSequence) {
                super.onAuthenticationError(errCode, errString)
                Timber.e("Error authenticating. Code $errCode ($errString")
                promptState = BiometricPromptState.ERROR
            }

            override fun onAuthenticationFailed() {
                super.onAuthenticationFailed()
                Timber.e("Biometric authentication failed.")
                promptState = BiometricPromptState.FAIL
            }

            override fun onAuthenticationSucceeded(result: BiometricPrompt.AuthenticationResult) {
                super.onAuthenticationSucceeded(result)
                Timber.d("Authentication successful")
                promptState = BiometricPromptState.SUCCESS
                onSuccess(result)
            }
        }
        return BiometricPrompt(activity, executor, callback)
    }
}
```
```gradle
buildscript {
    
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.1.1")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10")
        classpath("com.google.dagger:hilt-android-gradle-plugin:2.40.5"
    }
}

tasks.register("clean", Delete::class) {
    delete(rootProject.buildDir)
}
```
```gradle
plugins {
    id("com.android.application")
    kotlin("android")
    id("kotlin-parcelize")
    kotlin("kapt")
    id("dagger.hilt.android.plugin")
    id("com.google.protobuf") version "0.8.12"
    id("com.mikepenz.aboutlibraries.plugin") version "10.0.0-b08"
}

dependencies {
    // other dependencies...


    implementation("com.google.dagger:hilt-android:2.40.5")
    kapt("com.google.dagger:hilt-compiler:2.40.5}")
    kapt("androidx.hilt:hilt-compiler:1.0.0")
    implementation("androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha03")
    implementation("androidx.hilt:hilt-navigation-compose:1.0.0")

    // other dependencies...
}
```

The error occurs also when creating an instance of `AuthViewModel` in `MainActivity` and passing it down as a parameter to `Navigation()` (instead of using `hiltViewModel()`)

```kotlin
private val authViewModel by viewModels<AuthViewModel>()
```

Can't seem to figure this one out. What step can I take to find the source of the issue? Any pointer is appreciated, thanks!

Full crash log:

```
2022-02-06 22:35:29.957 31668-31668/com.my.package E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.package, PID: 31668
    java.lang.UnsupportedOperationException: SavedStateViewModelFactory constructed with empty constructor supports only calls to create(modelClass: Class<T>, extras: CreationExtras).
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:165)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:220)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:111)
        at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.kt:79)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:168)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:137)
        at androidx.biometric.BiometricPrompt.getViewModel(BiometricPrompt.java:1029)
        at androidx.biometric.BiometricPrompt.<init>(BiometricPrompt.java:847)
        at com.my.package.viewmodel.AuthViewModel.createBiometricPrompt(AuthViewModel.kt:105)
        at com.my.package.navigation.NavigationKt$Navigation$13$1$1.invoke(Navigation.kt:165)
        at com.my.package.navigation.NavigationKt$Navigation$13$1$1.invoke(Navigation.kt:162)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9$1.invoke(AnimatedNavHost.kt:212)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9$1.invoke(AnimatedNavHost.kt:210)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:60)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
        at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
        at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9.invoke(AnimatedNavHost.kt:210)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9.invoke(AnimatedNavHost.kt:202)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:658)
        at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:648)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:935)
        at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:606)
2022-02-06 22:35:29.958 31668-31668/com.my.package E/AndroidRuntime:     at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke(AnimatedContent.kt:638)
        at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke(AnimatedContent.kt:625)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:671)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:197)
        at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:91)
        at com.my.package.navigation.NavigationKt$Navigation$13.invoke(Navigation.kt:151)
        at com.my.package.navigation.NavigationKt$Navigation$13.invoke(Navigation.kt:150)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at com.my.package.ui.components.RootKt$Root$3$4.invoke(Root.kt:215)
        at com.my.package.ui.components.RootKt$Root$3$4.invoke(Root.kt:214)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:142)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2413)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2594)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2580)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2580)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2556)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:624)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:795)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:106)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:465)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:434)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by danysantiago** [comment]
It does not seem to be `AuthViewModel` failing to be created but some other view model being created during initialization of `BiometricPrompt`, specifically this part of the trace points to another call that is not using `hiltViewModel()`:
```
        at androidx.biometric.BiometricPrompt.<init>(BiometricPrompt.java:847)
        at com.my.package.viewmodel.AuthViewModel.createBiometricPrompt(AuthViewModel.kt:105)
```

By any chance do you create your own `SavedStateViewModelFactory`?

**Comment by sebastinto** [comment]
Thanks for the help!

> By any chance do you create your own `SavedStateViewModelFactory`?

I'm afraid I don't.

> some other view model being created during initialization of `BiometricPrompt`

I can't seem to find any reference to another view model in my own code related to the initialization of `BiometricPrompt` but the `androidx.biometric` library seems to be using its own `BiometricViewModel` internally.

>  specifically this part of the trace points to another call that is not using hiltViewModel():

How can you tell this is not using `hiltViewModel()`? Sorry if this is obvious.

**Comment by danysantiago** [comment]
Oh - I didn't realize `BiometricPrompt` was from androidx... I'll keep looking a bit more 🧐 

> How can you tell this is not using hiltViewModel()? Sorry if this is obvious.

In your trace `AuthViewModel` is already created and in fact a member function of it being called:
```
at com.my.package.viewmodel.AuthViewModel.createBiometricPrompt(AuthViewModel.kt:105)
```
I also don't see [`androidx.lifecycle.viewmodel.compose.viewModel`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-viewmodel-compose/src/main/java/androidx/lifecycle/viewmodel/compose/ViewModel.kt;l=65) in the trace, which is a non-inlined function that all `hiltViewModel()` overloads call, therefore the ViewModel causing the issue (which seems to be the one from `BiometricPrompt`) is not being created via `hiltViewModel()`.

I know later in the trace we see `HiltViewModelFactory`, but that factory [delegates to whatever factory the Activity / Fragment had before if the ViewModel being created is not a `@HiltViewModel`](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/internal/lifecycle/HiltViewModelFactory.java#L107-L113).

**Comment by danysantiago** [comment]
By the way, can you please share the version of `androidx.navigation` and `androidx.biometric` being used?

**Comment by sebastinto** [comment]
> By the way, can you please share the version of androidx.navigation and androidx.biometric being used?

`androidx.navigation:navigation-compose:2.5.0-alpha01`

`androidx.biometric:biometric-ktx:1.2.0-alpha04`

**Comment by sebastinto** [comment]
> In your trace `AuthViewModel` is already created and in fact a member function of it being called:
> 
> ```
> at com.my.package.viewmodel.AuthViewModel.createBiometricPrompt(AuthViewModel.kt:105)
> ```
> 
> I also don't see [`androidx.lifecycle.viewmodel.compose.viewModel`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-viewmodel-compose/src/main/java/androidx/lifecycle/viewmodel/compose/ViewModel.kt;l=65) in the trace, which is a non-inlined function that all `hiltViewModel()` overloads call, therefore the ViewModel causing the issue (which seems to be the one from `BiometricPrompt`) is not being created via `hiltViewModel()`.
> 
> I know later in the trace we see `HiltViewModelFactory`, but that factory [delegates to whatever factory the Activity / Fragment had before if the ViewModel being created is not a `@HiltViewModel`](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/internal/lifecycle/HiltViewModelFactory.java#L107-L113).

Thanks for the detailed explanation!

**Comment by VladDaniliuk** [comment]
I have the same problem with using BiometricPrompt.
When I use ```androidx.activity:activity-compose:1.5.0-alpha01``` I have the same error.
But when I change version to ```1.3.1``` code works correctly.

@sebastinto , can you please check the version of ```androidx.activity``` being used?

**Comment by VladDaniliuk** [comment]
And I also have this error when up version of ```androidx.navigation:navigation``` from ```2.4.0-beta02``` to ```2.5.0-alpha01```.
Version ```2.4.0``` works correctly.

**Comment by sebastinto** [comment]
@VladDaniliuk interesting!

I'm using `androidx.activity:activity-compose:1.4.0`. Rolling back to `1.3.1` did not fix the issue on my end. 

However rolling back `androidx.navigation:navigation-compose` from `2.5.0-alpha01` to `2.4.0` did!

**Comment by TylerMcCraw** [comment]
I can confirm that rolling back the androidx navigation dependency fixes this issue for me.
However, I wanted to note here that if you're using Android Gradle Plugin 7.1.0 or higher, you may need to use `androidx.navigation:navigation-*:2.4.1` (See [here](https://developer.android.com/jetpack/androidx/releases/navigation#version_241_3))

My current dependencies that allow me to avoid the UnsupportedOperationException as mentioned above with BiometricPrompt are:
`com.android.tools.build:gradle:7.1.1`
`com.google.dagger:hilt-android:2.40.5`
`androidx.biometric:biometric:1.2.0-alpha04`
`androidx.navigation:navigation-*:2.4.1` <-- this is the important one

**Comment by ColtonIdle** [comment]
I'm using 

com.android.tools.build:gradle:7.1.1
com.google.dagger:hilt-android:2.40.5
androidx.navigation:navigation-*:2.4.1

and I still get a crash.


java.lang.UnsupportedOperationException: SavedStateViewModelFactory constructed with empty constructor supports only calls to create(modelClass: Class<T>, extras: CreationExtras).
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:146)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:186)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:111)
        at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.kt:79)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:168)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:137)

The code that crashes doesn't use compose either.

**Comment by danysantiago** [comment]
To give an update, the issue is related to the `CreationExtras` in [Lifecycle 2.5.0-alpha](https://developer.android.com/jetpack/androidx/releases/lifecycle), which can come from many other alpha libraries, like `androidx.activity`, `androidx.fragment` or `androidx.navigation`, etc.

The issue happens when a non-Hilt ViewModel is trying to be created, but because its not `@HiltViewModel`-annotated, Hilt will delegate to another factory to create it (https://github.com/google/dagger/blob/master/java/dagger/hilt/android/internal/lifecycle/HiltViewModelFactory.java#L111).

The factory is just whatever `super.getDefaultViewModelProviderFactory()` returns, i.e. in generated code we basically do:
```
// Hilt generated activity / fragment:
@Override
public ViewModelProvider.Factory getDefaultViewModelProviderFactory() {
  return new HiltViewModelFactory(
      ..., 
      super.getDefaultViewModelProviderFactory // <--- this is the delegate
  )
}
```
Which for `FragmentActivity` (more precisely `ComponentActivity`) it seems to just be a `SavedStateViewModelFactory ` built using the default ctor: https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:activity/activity/src/main/java/androidx/activity/ComponentActivity.java;l=595

Then `ViewModelProvider` calls the `create()` with extras but since `HiltViewModelFactory` does not override the newer version, it goes to the `create()` version without extras and Hilt's factory ends up calling the `SavedStateViewModelFactory` from `ComponentActivity`, but it calls again the `create()` without the extras and then... boom, big crash!

The issue likely affects other delegating factory patterns, not just Hilt's. We'll try to fix it in `androidx.lifecycle` but if not then we might need to patch Hilt.

As for ways to avoid it... if you own the `ViewModel` you can make it a `@HiltViewModel` even if it has no injected dependencies. If you don't own it but control its creation, then passing a new `SavedStateViewModelFactory` in the factory argument of `ViewModelProvider` constructor or Compose's `viewModel()` function can workaround the issue. If the view model is some implementation detail, like it is with the Biometric library, then I can only suggest to hold-off on using the alpha version of the libraries with the creation extras.

**Comment by ColtonIdle** [comment]
Thanks for the update. I own it and control its impl. But its related to some old code that I don't want to touch for now (i.e. some ViewModelProvider.Factorys) so until there is a migration guide I suppose I will just downgrade anything related to 2.5.0-alpha to 2.4.0. I will update here if that works (im assuming it will) was just clarifying that its not _just_ navigation or anything. seems like any dep that uses the 2.5.0 alpha like you said. Thank you @danysantiago appreciate it

**Comment by sebastinto** [comment]
Thanks for the update. The detailed explanation is once again very much appreciated!

**Comment by danysantiago** [comment]
Hey - Wanted to share an update that a [change in androidx](https://android-review.googlesource.com/c/platform/frameworks/support/+/2019219) is going to fix this issue and if all goes well, it will be available in a future alpha version of androidx's activity, fragment and viewmodel-savedstate artifacts.

**Comment by danysantiago** [comment]
Thanks for confirming the fix. Closing this issue now, the fix is in [2.5.0-alpha05 of androidx.lifecyle](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.5.0-alpha05)
