### ISSUE TITLE
dagger crash with NoSuchElementException

### ISSUE THREAD

**Issue by nicks** [google/dagger#324]
I'm still trying to figure out a minimal repro case, but here is the stack trace. It's likely a bug in our code but it seems like dagger should report an error message instead of crashing.

Repro'd with dagger-compiler 2.0.2

```
Caused by: java.util.NoSuchElementException
	at com.sun.tools.javac.util.List$2.next(List.java:432)
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:302)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:289)
	at dagger.internal.codegen.DependencyRequest$Factory.extractKindAndType(DependencyRequest.java:285)
	at dagger.internal.codegen.DependencyRequest$Factory.newDependencyRequest(DependencyRequest.java:245)
	at dagger.internal.codegen.DependencyRequest$Factory.forRequiredResolvedVariable(DependencyRequest.java:171)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.injectionSiteForInjectField(MembersInjectionBinding.java:161)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.access$200(MembersInjectionBinding.java:126)
	at dagger.internal.codegen.MembersInjectionBinding$Factory$1.visitVariableAsField(MembersInjectionBinding.java:208)
	at dagger.internal.codegen.MembersInjectionBinding$Factory$1.visitVariableAsField(MembersInjectionBinding.java:197)
	at com.sun.tools.javac.code.Symbol$VarSymbol.accept(Symbol.java:1237)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.forInjectedType(MembersInjectionBinding.java:195)
	at dagger.internal.codegen.InjectBindingRegistry.getOrFindMembersInjectionBinding(InjectBindingRegistry.java:256)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.rollUpMembersInjectionBindings(BindingGraph.java:313)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.rollUpMembersInjectionBindings(BindingGraph.java:317)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.lookUpBindings(BindingGraph.java:305)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.resolve(BindingGraph.java:407)
	at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:168)
	at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:105)
	at dagger.internal.codegen.AbstractComponentProcessingStep.process(AbstractComponentProcessingStep.java:54)
	at dagger.internal.codegen.AbstractComponentProcessingStep.process(AbstractComponentProcessingStep.java:30)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:171)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
```

**Comment by nicks** [comment]
fwiw, the problem was that the injection target (the class i was injecting into) was extending a generic class, but forgot the template argument. i can probably come up with a repro case if you need one.

**Comment by gk5885** [comment]
Was this on 2.0.2 or at head?  If not head, could you try to reproduce with that?

**Comment by nicks** [comment]
is there a way to get head from a maven repo?

the docs (https://github.com/google/dagger#status) say that there should be a 2.1-SNAPSHOT, but i don't see one... https://repo1.maven.org/maven2/com/google/dagger/dagger-compiler/

**Comment by JakeWharton** [comment]
It's in the snapshots repo of Sonatype:
https://oss.sonatype.org/content/repositories/snapshots/

**Comment by nicks** [comment]
cool, thanks. It also repros with head. Here's the stack trace from 2.1-SNAPSHOT

Caused by: java.util.NoSuchElementException
	at com.sun.tools.javac.util.List$2.next(List.java:432)
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:302)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:289)
	at dagger.internal.codegen.DependencyRequest$Factory$2.visitDeclared(DependencyRequest.java:423)
	at dagger.internal.codegen.DependencyRequest$Factory$2.visitDeclared(DependencyRequest.java:407)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:936)
	at dagger.internal.codegen.DependencyRequest$Factory.extractKindAndType(DependencyRequest.java:406)
	at dagger.internal.codegen.DependencyRequest$Factory.newDependencyRequest(DependencyRequest.java:373)
	at dagger.internal.codegen.DependencyRequest$Factory.forRequiredResolvedVariable(DependencyRequest.java:258)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.injectionSiteForInjectField(MembersInjectionBinding.java:169)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.access$200(MembersInjectionBinding.java:136)
	at dagger.internal.codegen.MembersInjectionBinding$Factory$4.visitVariableAsField(MembersInjectionBinding.java:324)
	at dagger.internal.codegen.MembersInjectionBinding$Factory$4.visitVariableAsField(MembersInjectionBinding.java:314)
	at com.sun.tools.javac.code.Symbol$VarSymbol.accept(Symbol.java:1237)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.getInjectionSites(MembersInjectionBinding.java:248)
	at dagger.internal.codegen.MembersInjectionBinding$Factory.forInjectedType(MembersInjectionBinding.java:200)
	at dagger.internal.codegen.InjectBindingRegistry.tryRegisterMembersInjectedType(InjectBindingRegistry.java:262)
	at dagger.internal.codegen.InjectBindingRegistry.getOrFindMembersInjectionBinding(InjectBindingRegistry.java:323)
	at dagger.internal.codegen.BindingGraph$Factory$Resolver.lookUpBindings(BindingGraph.java:438)
	at dagger.internal.codegen.BindingGraph$Factory$Resolver.resolve(BindingGraph.java:620)
	at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:258)
	at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:189)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:136)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:46)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:171)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)

**Comment by gk5885** [comment]
There's no chance that you're holding on to a raw type of `Provider` or `Lazy` or `MembersInjector` or something, is there?

**Comment by nicks** [comment]
I don't think so? But I haven't been able to come up with an isolated repro case. I can only repro it in my big complex project. So I guess anything is possible?

**Comment by ronshapiro** [comment]
I think this is the same as #419, which should be fixed externally very soon
