### ISSUE TITLE
Hilt throws NoSuchMethodException when injecting a worker 

### ISSUE THREAD

**Issue by vincent-paing** [google/dagger#3359]
Error log:

```
java.lang.NoSuchMethodException: dev.aungkyawpaing.hiltnosuchmethod.ExampleWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
        at java.lang.Class.getConstructor0(Class.java:2363)
        at java.lang.Class.getDeclaredConstructor(Class.java:2201)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```
        
Reproducable repo: https://github.com/vincent-paing/HiltNoSuchMethodIssue
Work Manager version : 2.7.1
Hilt version : 2.41
Kotlin version : 1.6.21

I run a debugger to see what went wrong and `workerFactories` is empty in `WorkerFactoryModule` instead of having `ExampleWorker_Factory`

**Comment by danysantiago** [comment]
You are missing the `@HiltWorker` annotation in your [worker](https://github.com/vincent-paing/HiltNoSuchMethodIssue/blob/main/app/src/main/java/dev/aungkyawpaing/hiltnosuchmethod/ExampleWorker.kt#L10), per the Hilt + WorkManager integration doc: https://developer.android.com/training/dependency-injection/hilt-jetpack#workmanager
