### ISSUE TITLE
Hilt failes to generate files for fragment inside 'import' package

### ISSUE THREAD

**Issue by kezc** [google/dagger#3424]
Hello everyone.
I have a fragment ImportFragment inside `import` package. The fragment is annotated with `@AndroidEntryPoint`. This results in a crash when trying to open the fragment. I've done clean builds, invalidated caches, and restarted android studio multiple times.
```
2022-06-10 13:13:09.796 15060-15060/com.put.ubi E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.put.ubi, PID: 15060
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/put/ubi/import/Hilt_ImportFragment;
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:615)
        a...
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.put.ubi.import.Hilt_ImportFragment" on path: DexPathList[[dex file "/data/data/com.put.ubi/code_cache/.overlay/base.apk/classes9.dex", zip file "/data/app/~~kQWC_QwsSyxO5dxSAu1QZA==/com.put.ubi-6_A_-9Fq1E7HrzvWQpnebg==/base.apk"],nativeLibraryDirectories=[/data/app/~~kQWC_QwsSyxO5dxSAu1QZA==/com.put.ubi-6_A_-9Fq1E7HrzvWQpnebg==/lib/x86, /system/lib, /system_ext/lib]]
      ...
```
However, after changing the package name suddenly it started working.

**Comment by danysantiago** [comment]
You need to avoid using Java keywords in your package names since KAPT will drop such classes and Hilt won't be able to process them. See: https://github.com/google/dagger/issues/2743#issuecomment-878004836. Sadly Kotlin team wanted to add a strict mode to KAPT to prevent this but I don't think it ever got completed: https://youtrack.jetbrains.com/issue/KT-25518/Kapt-Add-a-strict-mode.
