### ISSUE TITLE
UnsupportedOperationException thrown when providing named SET_VALUES

### ISSUE THREAD

**Issue by maciekjanusz** [google/dagger#343]
Using `com.google.dagger:dagger-compiler:2.0.2` and `org.glassfish:javax.annotation:10.0-b28` with `com.neenbedankt.gradle.plugins:android-apt:1.8` gradle plugin, I get `UnsupportedOperationException` while trying to generate source providing a dependency annotated with `@Named` and `@Provides(type = Provides.Type.SET_VALUES)`. Gradle throws `TaskExecutionException` and below is the stack trace of the cause exception thrown by dagger compiler:

```
java.lang.UnsupportedOperationException
	at dagger.internal.codegen.KeyVariableNamer.apply(KeyVariableNamer.java:44)
	at dagger.internal.codegen.ComponentGenerator.frameworkFieldForSyntheticContributionBinding(ComponentGenerator.java:1003)
	at dagger.internal.codegen.ComponentGenerator.writeField(ComponentGenerator.java:730)
	at dagger.internal.codegen.ComponentGenerator.writeFields(ComponentGenerator.java:615)
	at dagger.internal.codegen.ComponentGenerator.writeComponent(ComponentGenerator.java:391)
	at dagger.internal.codegen.ComponentGenerator.write(ComponentGenerator.java:221)
	at dagger.internal.codegen.ComponentGenerator.write(ComponentGenerator.java:120)
	at dagger.internal.codegen.SourceFileGenerator.generate(SourceFileGenerator.java:53)
	at dagger.internal.codegen.AbstractComponentProcessingStep.process(AbstractComponentProcessingStep.java:59)
	at dagger.internal.codegen.AbstractComponentProcessingStep.process(AbstractComponentProcessingStep.java:30)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:171)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 89 more
```

Someone also complains about this in the comment below [this answer on StackOverflow](http://stackoverflow.com/a/33177815/4191629).

**Comment by maciekjanusz** [comment]
Nevermind, I see it's fixed in version 2.1
