### ISSUE TITLE
Hilt - Incremental build issue - java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by henieek** [google/dagger#3455]
Hi,

We encountered a potential bug in Hilt which breaks the code generation in incremental builds, effectively causing a runtime crash on the start. This is the stacktrace we get:

```
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/example/hiltissue/DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider;
        at com.example.hiltissue.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl.initialize(DaggerMainApplication_HiltComponents_SingletonC.java:469)
        at com.example.hiltissue.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl.<init>(DaggerMainApplication_HiltComponents_SingletonC.java:463)
        at com.example.hiltissue.DaggerMainApplication_HiltComponents_SingletonC$SingletonCImpl.<init>(DaggerMainApplication_HiltComponents_SingletonC.java:454)
        at com.example.hiltissue.DaggerMainApplication_HiltComponents_SingletonC$Builder.build(DaggerMainApplication_HiltComponents_SingletonC.java:69)
```

I created a sample project which presents the problem: https://github.com/henieek/hilt-incremental-build-issue

Relevant files:
1. `MyService` in the feature module  https://github.com/henieek/hilt-incremental-build-issue/blob/main/feature/src/main/java/com/example/feature/MyService.kt
2. `MyService` gets injected to `MainApplication` as `Lazy`: https://github.com/henieek/hilt-incremental-build-issue/blob/main/app/src/main/java/com/example/hiltissue/MainApplication.kt

Steps to reproduce:
1. Checkout the project
3. `./gradlew installDebug`
4. In the `MyService` class, change the name of the `doStuff()` method to `doStuff2()`
5. `./gradlew installDebug` again
6. Try to launch the app.

Some findings:

1. Clean build fixes the issue.
2. Injecting an instance directly, without `Lazy`, seems to fix the issue too.

I would appreciate if you could take a look - let me know if I can help with more information.

Thanks a ton!

**Comment by danysantiago** [comment]
Hey - Thanks for the repro app, super helpful!

I was able to narrow the issue down to Dagger (not Hilt specifically) and some sort of issue with Gradle incremental annotation processing, I ended up filling a bug to the Gradle team: https://github.com/gradle/gradle/issues/21203. Sadly I don't have a workaround, if I find something I'll let you know ASAP.

**Comment by d4rken** [comment]
Any workaround available for this? I don't inject `Lazy` and still encounter this.

**Comment by d4rken** [comment]
This demo project of mine reproduces it:
https://github.com/d4rken/android-starter-v4/tree/dagger-issue-3455

If I clean the project before deploying, it works.
If i just deploy a second time without cleaning, I get:

```java
2022-07-13 14:43:42.504 13746-13746/eu.darken.androidstarter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.darken.androidstarter, PID: 13746
    java.lang.NoClassDefFoundError: Failed resolution of: Leu/darken/androidstarter/DaggerApp_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider;
        at eu.darken.androidstarter.DaggerApp_HiltComponents_SingletonC$SingletonCImpl.initialize(DaggerApp_HiltComponents_SingletonC.java:800)
        at eu.darken.androidstarter.DaggerApp_HiltComponents_SingletonC$SingletonCImpl.<init>(DaggerApp_HiltComponents_SingletonC.java:793)
        at eu.darken.androidstarter.DaggerApp_HiltComponents_SingletonC$SingletonCImpl.<init>(DaggerApp_HiltComponents_SingletonC.java:754)
        at eu.darken.androidstarter.DaggerApp_HiltComponents_SingletonC$Builder.build(DaggerApp_HiltComponents_SingletonC.java:139)
        at eu.darken.androidstarter.Hilt_App$1.get(Hilt_App.java:23)
        at dagger.hilt.android.internal.managers.ApplicationComponentManager.generatedComponent(ApplicationComponentManager.java:40)
        at eu.darken.androidstarter.Hilt_App.generatedComponent(Hilt_App.java:34)
        at eu.darken.androidstarter.Hilt_App.hiltInternalInject(Hilt_App.java:49)
        at eu.darken.androidstarter.Hilt_App.onCreate(Hilt_App.java:40)
        at eu.darken.androidstarter.App.onCreate(App.kt:16)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1223)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6762)
        at android.app.ActivityThread.access$1500(ActivityThread.java:256)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "eu.darken.androidstarter.DaggerApp_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider" on path: DexPathList[[zip file "/data/app/~~L4t94MtqIyG5HRbwOIlGHQ==/eu.darken.androidstarter-D6HPNnNoWZFtYpI16jMIHA==/base.apk"],nativeLibraryDirectories=[/data/app/~~L4t94MtqIyG5HRbwOIlGHQ==/eu.darken.androidstarter-D6HPNnNoWZFtYpI16jMIHA==/lib/arm64, /data/app/~~L4t94MtqIyG5HRbwOIlGHQ==/eu.darken.androidstarter-D6HPNnNoWZFtYpI16jMIHA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at eu.darken.androidstarter.DaggerApp_HiltComponents_SingletonC$SingletonCImpl.initialize(DaggerApp_HiltComponents_SingletonC.java:800) 
        at eu.darken.androidstarter.DaggerApp_HiltComponents_SingletonC$SingletonCImpl.<init>(DaggerApp_HiltComponents_SingletonC.java:793) 
        at eu.darken.androidstarter.DaggerApp_HiltComponents_SingletonC$SingletonCImpl.<init>(DaggerApp_HiltComponents_SingletonC.java:754) 
        at eu.darken.androidstarter.DaggerApp_HiltComponents_SingletonC$Builder.build(DaggerApp_HiltComponents_SingletonC.java:139) 
        at eu.darken.androidstarter.Hilt_App$1.get(Hilt_App.java:23) 
        at dagger.hilt.android.internal.managers.ApplicationComponentManager.generatedComponent(ApplicationComponentManager.java:40) 
        at eu.darken.androidstarter.Hilt_App.generatedComponent(Hilt_App.java:34) 
        at eu.darken.androidstarter.Hilt_App.hiltInternalInject(Hilt_App.java:49) 
        at eu.darken.androidstarter.Hilt_App.onCreate(Hilt_App.java:40) 
        at eu.darken.androidstarter.App.onCreate(App.kt:16) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1223) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6762) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:256) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7870) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by danysantiago** [comment]
This issue was fixed by the Gradle team: https://github.com/gradle/gradle/issues/21203, and it seems it will be availbale in Gradle 7.6 RC1, so closing this one out.
