### ISSUE TITLE
[Hilt] Can't provide scoped dependency with custom component

### ISSUE THREAD

**Issue by steviek** [google/dagger#3462]
I tried setting up a custom component like this:

```
@Scope
@Retention(AnnotationRetention.SOURCE)
annotation class UserScoped

@UserScoped
@DefineComponent(parent = SingletonComponent::class)
interface UserComponent

@DefineComponent.Builder
interface UserComponentBuilder {
    fun userId(@BindsInstance @UserId userId: String): UserComponentBuilder
    fun build(): UserComponent
}

@Qualifier
annotation class UserId
```

This compiles and I can inject `UserComponentBuilder` into classes in the `SingletonComponent` and have modules with `@InstallIn(UserComponent::class)`.

However, if I have a `UserScoped` binding, e.g.

```
@InstallIn(UserComponent::class)
@Module
object UserModule {
    @UserScoped
    @Provides
    fun provideUserScopedBinding() = Any()
}
```

Then compilation fails:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':amalgamate:hiltJavaCompileFoxfoodDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:188)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:186)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:174)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	...
Caused by: java.lang.RuntimeException: java.util.NoSuchElementException
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:163)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at org.gradle.internal.compiler.java.IncrementalCompileTask.call(IncrementalCompileTask.java:89)
	at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:94)
	...
Caused by: java.util.NoSuchElementException
	at dagger.internal.codegen.extension.DaggerCollectors$ToOptionalState.getElement(DaggerCollectors.java:145)
	at dagger.internal.codegen.extension.DaggerCollectors.lambda$static$1(DaggerCollectors.java:61)
	at dagger.internal.codegen.binding.InjectionAnnotations.getScopesFromScopeMetadata(InjectionAnnotations.java:138)
	at dagger.internal.codegen.binding.InjectionAnnotations.getScopes(InjectionAnnotations.java:103)
	at dagger.internal.codegen.binding.InjectionAnnotations.getScope(InjectionAnnotations.java:86)
```

**Comment by Chang-Eric** [comment]
Your scope annotation should be at least `AnnotationRetention.CLASS`. `SOURCE` retention annotations will be thrown away by the compiler so you're probably hitting some sort of mismatch where there is disagreement with what is expected from a compiled dependency.

**Comment by Chang-Eric** [comment]
Oops yea, I should have said `BINARY`, my Java bias is showing haha. Hope you're doing well too, glad to see you're using Hilt =)
