### ISSUE TITLE
Force close app after upgrade to 2.43 (Jetpack Compose)

### ISSUE THREAD

**Issue by barry-irvine** [google/dagger#3492]
I keep getting this crash if I upgrade to 2.43. I have tried it with versions 2.5.0 and 2.5.1 of lifecycle and compose navigation  and 1.5.0/1.5.1 of activity/fragment but all to no avail. It looks the same as #3484 but those dependencies all check out okay.

```
2022-07-29 12:38:16.206 21022-21022/com.smartdestinations.gocityhub.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.smartdestinations.gocityhub.debug, PID: 21022
    java.lang.IllegalArgumentException: CreationExtras must have a value by `SAVED_STATE_REGISTRY_OWNER_KEY`
        at androidx.lifecycle.SavedStateHandleSupport.createSavedStateHandle(SavedStateHandleSupport.kt:91)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:89)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:111)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:215)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.get$default(ViewModel.kt:195)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:120) 
```

```
implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.5.1'
implementation 'androidx.hilt:hilt-navigation-compose:1.0.0'
implementation 'androidx.activity:activity-compose:1.5.1'
implementation 'androidx.fragment:fragment-ktx:1.5.1'
implementation 'androidx.navigation:navigation-compose:2.5.1
```

**Comment by barry-irvine** [comment]
My mistake! It looks like I'd declared navigation-compose in my dependencies file but never actually implemented it in the app/build.gradle

**Comment by nisagurbulak** [comment]
Hey im getting the same error but i dont understand what should i do?

**Comment by iwo** [comment]
I resolved this error in my project by adding `implementation("androidx.fragment:fragment-ktx:1.5.1")` dependency. `Fragment.viewModels()` is defined in this library and previously it was only transitive dependency resolved to the older version.
