### ISSUE TITLE
Getting Hilt to work with Robolectric setupActivity and start fragment

### ISSUE THREAD

**Issue by akhilrm** [google/dagger#3494]
We use Robolectric setupActivity to create a test activity instance and start a fragment. The tests are run against the fragments. After each tests we are not destroying the activity. Instead, we replace the fragment on the test activity. This is a tradeoff to execute UTs. But it worked fine. Till we migrated the app to Hilt. Now the tests are failing.

```
java.lang.IllegalStateException: The component was not created. Check that you have added the HiltAndroidRule.
	at dagger.hilt.internal.Preconditions.checkState(Preconditions.java:83)
	at dagger.hilt.android.internal.testing.TestApplicationComponentManager.generatedComponent(TestApplicationComponentManager.java:96)
	at com.example.android.ext.HiltTestApplication_Application.generatedComponent(HiltTestApplication_Application.java:31)
	at dagger.hilt.EntryPoints.get(EntryPoints.java:59)
	at dagger.hilt.android.EntryPointAccessors.fromApplication(EntryPointAccessors.kt:35)
	at dagger.hilt.android.flags.FragmentGetContextFix.isFragmentGetContextFixDisabled(FragmentGetContextFix.java:67)
	at com.example.android.ext.search.Hilt_SearchFragment.initializeComponentContext(Hilt_SearchFragment.java:61)
	at com.example.android.ext.search.Hilt_SearchFragment.onAttach(Hilt_SearchFragment.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.example.android.ext.search.Hilt_SearchFragment.onAttach(Hilt_SearchFragment.java:51)
	at androidx.fragment.app.Fragment.onAttach(Fragment.java:1827)
```

We have HiltAndRule for the UTs. After spending lot of time, we found that using [launchFragmentInHiltContainer](https://developer.android.com/training/dependency-injection/hilt-testing#launchfragment) fixes the issue. However this would require us to modify thousands of tests. Is there any way to avoid this ? Can we keep using the current setup with Hilt ?

**Comment by bcorso** [comment]
> We use Robolectric setupActivity to create a test activity instance and start a fragment. The tests are run against the fragments. After each tests we are not destroying the activity. Instead, we replace the fragment on the test activity. This is a tradeoff to execute UTs. But it worked fine. Till we migrated the app to Hilt. Now the tests are failing.

Hi @akhilrm, Can you give example code that demonstrates your setup so that I can repro the issue?

**Comment by akhilrm** [comment]
I have create a sample repo, [RobolectricHiltIssue](https://github.com/akhilrm/RobolectricHiltIssue). The issue is reproducible on this repo.

**Comment by bcorso** [comment]
Hi @akhilrm,

Sorry for the late reply. 

Is there a reason you need to reuse the activity for multiple test cases? In particular, one way to fix the repro sample you linked is to build a new activity for each fragment started, e.g.

```diff
object TestHelper {
-    private val testMainActivity: MainActivity =
-        Robolectric.buildActivity(MainActivity::class.java).setup().get()

    fun startFragmentInMainContentFrame(fragment: Fragment) {
-       testMainActivity
+        Robolectric.buildActivity(MainActivity::class.java).setup().get()
            .supportFragmentManager.beginTransaction()
            .replace(R.id.container, fragment)
            .commitNow()
    }
}
```

In general, this is a best practice as using the same activity across multiple test cases can easily leak state and cause issues.

**Comment by akhilrm** [comment]
Yeah. We made the same change to fix this issue.

Thanks!
