### ISSUE TITLE
Hilt 2.43.1 breaks ViewModel injection for custom views

### ISSUE THREAD

**Issue by alapshin** [google/dagger#3497]
I have following code in one of my custom views
```
    override fun onAttachedToWindow() {
        super.onAttachedToWindow()

        ViewModelProvider(checkNotNull(findViewTreeViewModelStoreOwner())).get<HomeSkillsViewModel>().let {
            viewModel = it
            bind(this, viewModel)
        }
    }
```

This view is place in fragment using following code
```
lateinit var skillsView: HomeSkillsView

override fun onCreateView(
    inflater: LayoutInflater,
    container: ViewGroup?,
    savedInstanceState: Bundle?
): View {
    return binding.root.also {
        skillsView = HomeSkillsView(requireContext())
    }
}
    
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
    super.onViewCreated(view, savedInstanceState)

    binding.homeScrollviewContainer.addView(
        skillsView,
        LinearLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT
        )
    )
}
```

This code was working fine until recent update to 2.43.1
After update it crashes application with following stacktrace
```
2022-08-02 16:10:38.003 11404-11404/com.placeholder.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.placeholder.app, PID: 11404
    java.lang.IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
        at androidx.savedstate.SavedStateRegistry.consumeRestoredStateForKey(SavedStateRegistry.kt:72)
        at androidx.lifecycle.SavedStateHandlesProvider.performRestore(SavedStateHandleSupport.kt:163)
        at androidx.lifecycle.SavedStateHandlesProvider.consumeRestoredStateForKey(SavedStateHandleSupport.kt:176)
        at androidx.lifecycle.SavedStateHandleSupport.createSavedStateHandle(SavedStateHandleSupport.kt:71)
        at androidx.lifecycle.SavedStateHandleSupport.createSavedStateHandle(SavedStateHandleSupport.kt:103)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:89)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:111)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
        at com.placeholder.home.view.HomeSkillsView.onAttachedToWindow(HomeSkillsView.kt:105)
        at android.view.View.dispatchAttachedToWindow(View.java:20479)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5278)
        at android.view.ViewGroup.addView(ViewGroup.java:5064)
        at android.view.ViewGroup.addView(ViewGroup.java:5036)
        at com.placeholder.home.view.HomeFragment.onViewCreated(HomeFragment.kt:137)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I assume that is caused by string of updates for various `androidx` dependencies. If I downgrade `hilt` back to 2.42 while keeping `androidx` dependencies at their new versions code above works fine.

What is intersting is that this case doesn't happen if I move this view to another fragment. However both fragments have fairly similar structure/code it just second fragment have simpler view hierarchy/less view created at runtime. Maybe it is related somehow.

**Comment by Chang-Eric** [comment]
Hm, this does seem like it may not be Hilt-specific if downgrading the dependencies fixes the issue. Have you tried seeing if the issue happens if you access a non-Hilt ViewModel that uses SavedState?

**Comment by alapshin** [comment]
> Hm, this does seem like it may not be Hilt-specific if downgrading the dependencies fixes the issue. Have you tried seeing if the issue happens if you access a non-Hilt ViewModel that uses SavedState?

I'm not sure that it is Hilt specific either. However it happens only with Hilt >= 2.43.1. With Hilt 2.42 it does work fine. All other AndroidX dependencies (activity, fragment, lifecycle etc) are the same between cases and at latest release version (so there is no chance that newer Hilt pulls newer dependencies).

I tried to get instance of non-Hilt ViewModel with savedStateHandle constructor argument and still got same error message.

In the end I was able to workaround this issue by by deferring viewModel creation until parent lifecylceOwner is in CREATED state using following approach
```
    private val viewModel by lazy {
        val viewModelStoreOwner = checkNotNull(findViewTreeViewModelStoreOwner())
        ViewModelProvider(viewModelStoreOwner).get<HomeSkillsViewModel>()
    }

    override fun onAttachedToWindow() {
        super.onAttachedToWindow()

        findViewTreeLifecycleOwner()?.lifecycle?.addObserver(object : DefaultLifecycleObserver {
            override fun onCreate(owner: LifecycleOwner) {
                super.onCreate(owner)
                // access viewModel property here
            }
        })
    }
```
