### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError: No interface method putIfAbsent on Android 6 API level 23

### ISSUE THREAD

**Issue by sahilandroid19** [google/dagger#3600]
Hi, I just upgraded my dagger version from 2.34.1 to 2.40.1 and now i am getting this crash on Android 6 devices in production. App gets crashed at starting only. 
Please find below the crash logs:

```
Fatal Exception: java.lang.NoSuchMethodError: No interface method putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/Map; or its super classes (declaration of 'java.util.Map' appears in /system/framework/core-libart.jar)
       at com.google.common.collect.JdkBackedImmutableMap.create(JdkBackedImmutableMap.java:42)
       at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:114)
       at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
       at com.paytm.pos.di.component.DaggerAppComponent.mapOfClassOfAndProviderOfAndroidInjectorFactoryOf(DaggerAppComponent.java:882)
       at com.paytm.pos.di.component.DaggerAppComponent.dispatchingAndroidInjectorOfObject(DaggerAppComponent.java:886)
       at com.paytm.pos.di.component.DaggerAppComponent.injectPOSApplication(DaggerAppComponent.java:1836)
       at com.paytm.pos.di.component.DaggerAppComponent.inject(DaggerAppComponent.java:1826)
       at com.paytm.pos.ui.POSApplication.applicationInjector(POSApplication.java:64)
       at dagger.android.DaggerApplication.injectIfNecessary(DaggerApplication.java:62)
       at dagger.android.DaggerApplication.onCreate(DaggerApplication.java:38)
       at com.paytm.pos.ui.POSApplication.onCreate(POSApplication.java:69)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4740)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5468)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
```

**Comment by bcorso** [comment]
Hmm, I don't think this is a Dagger issue. It looks more like a Guava versioning issue. 

In particular, this stack trace looks like it's coming from Guava's [jre](https://mvnrepository.com/artifact/com.google.guava/guava/31.1-jre) library (https://github.com/google/guava/tree/master/guava/src/com/google/common/collect) rather than Guava's [android](https://mvnrepository.com/artifact/com.google.guava/guava/31.1-android) library (https://github.com/google/guava/tree/master/android/guava/src/com/google/common/collect) because `JdkBackedImmutableMap` doesn't even exist on the android side.

You should be able to fix the issue if you can remove the guava jre library and replace it with the guava android library in your deps. You may first need to do some digging to figure out where the guava jre library is being pulled in.

**Comment by bcorso** [comment]
Closing, as there hasn't been an update for a while. Feel free to add an update with more information if you're still having issues.
