### ISSUE TITLE
Latest Hilt stable version is not working with latest stable Kotlin version in latest stable Android Studio [2.44 <-> 1.7.21 <-> Dolphin | 2021.3.1 Patch 1]

### ISSUE THREAD

**Issue by jimmytrivedi** [google/dagger#3629]
Error:
```
error: [Hilt]
  Unsupported metadata version. Check that your Kotlin version is >= 1.0: java.lang.IllegalStateException: Unsupported metadata version. Check that your Kotlin version is >= 1.0
  	at dagger.internal.codegen.kotlin.KotlinMetadata.metadataOf(KotlinMetadata.java:206)
  	at dagger.internal.codegen.kotlin.KotlinMetadata.from(KotlinMetadata.java:187)
  	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
  	at dagger.internal.codegen.kotlin.KotlinMetadataFactory.create(KotlinMetadataFactory.java:56)
  	at dagger.internal.codegen.kotlin.KotlinMetadataUtil.isObjectClass(KotlinMetadataUtil.java:91)
[Hilt]
```

With Kotlin 1.6.10 and Hilt 2.42 was working fine. Not I upgraded and it is not working. Unnecessary developer time wasting to figure out the solution!

Please note:  In Kotlin 1.7 series, 2.44 and 2.43.2 is not working with any permutation and combination.

**Comment by kuanyingchou** [comment]
Hi, @jimmytrivedi , this is working on my side. Could you please check that if your hilt-android-gradle-plugin is also updated to the same version?

**Comment by jimmytrivedi** [comment]
Hi @kuanyingchou Sorry my bad. I didn't look on that. It is working fine after upgrading plugin. Thanks.
