### ISSUE TITLE
Upgrading Hilt 2.44.1 -> 2.44.2 breaks build

### ISSUE THREAD

**Issue by massivemadness** [google/dagger#3690]
Versions: AGP 7.3.1, Hilt 2.44.2, Room 2.4.3, Hilt-WorkManager 1.0.0, Hilt-Navigation 1.0.0

I'm not sure if it's hilt bug or AGP, but after upgrading Hilt 2.44.1 to 2.44.2 I'm getting this type of error:

```
> Task :main:app-main:dexBuilderDebug FAILED
AGPBI: {"kind":"error","text":"Compilation of classes com.opencap.android.OpenCapApp_HiltComponents$ViewWithFragmentC$Builder, com.opencap.android.OpenCapApp_HiltComponents$FragmentC, com.opencap.android.OpenCapApp_HiltComponents$ViewModelC, com.opencap.android.OpenCapApp_HiltComponents$ActivityRetainedC$Builder, com.opencap.android.OpenCapApp_HiltComponents$ActivityCBuilderModule, com.opencap.android.OpenCapApp_HiltComponents$ActivityRetainedCBuilderModule, com.opencap.android.OpenCapApp_HiltComponents$ServiceCBuilderModule requires its nest mates com.opencap.android.OpenCapApp_HiltComponents$SingletonC (unavailable) to be on program or class path.(Classes com.opencap.android.OpenCapApp_HiltComponents, com.opencap.android.OpenCapApp_HiltComponents$ViewWithFragmentC, com.opencap.android.OpenCapApp_HiltComponents$FragmentC$Builder, com.opencap.android.OpenCapApp_HiltComponents$ViewC, com.opencap.android.OpenCapApp_HiltComponents$ViewC$Builder, com.opencap.android.OpenCapApp_HiltComponents$ViewModelC$Builder, com.opencap.android.OpenCapApp_HiltComponents$ActivityC, com.opencap.android.OpenCapApp_HiltComponents$ActivityC$Builder, com.opencap.android.OpenCapApp_HiltComponents$ActivityRetainedC, com.opencap.android.OpenCapApp_HiltComponents$ServiceC, com.opencap.android.OpenCapApp_HiltComponents$ServiceC$Builder, com.opencap.android.OpenCapApp_HiltComponents$ViewWithFragmentCBuilderModule, com.opencap.android.OpenCapApp_HiltComponents$FragmentCBuilderModule, com.opencap.android.OpenCapApp_HiltComponents$ViewCBuilderModule, com.opencap.android.OpenCapApp_HiltComponents$ViewModelCBuilderModule from the same nest are on class path).","sources":[{"file":"/Users/massivemadness/Documents/GitHub/OpenCAP/main/app-main/build/intermediates/asm_instrumented_project_classes/debug/com/opencap/android/OpenCapApp_HiltComponents.class"}],"tool":"D8"}
org.gradle.workers.WorkerExecutionException: There were multiple failures while executing work items
	at org.gradle.workers.internal.DefaultWorkerExecutor.workerExecutionException(DefaultWorkerExecutor.java:269)
	at org.gradle.workers.internal.DefaultWorkerExecutor.await(DefaultWorkerExecutor.java:249)
	at com.android.build.gradle.internal.tasks.DexArchiveBuilderTaskDelegate.doProcess(DexArchiveBuilderTaskDelegate.kt:227)
	at com.android.build.gradle.internal.tasks.DexArchiveBuilderTask.doTaskAction(DexArchiveBuilderTask.kt:255)
	at com.android.build.gradle.internal.tasks.NewIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(BaseTask.kt:69)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
	at com.android.build.gradle.internal.tasks.NewIncrementalTask.taskAction(NewIncrementalTask.kt:46)
	at jdk.internal.reflect.GeneratedMethodAccessor8552.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.IncrementalInputsTaskAction.doExecute(IncrementalInputsTaskAction.java:32)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':main:app-main:dexBuilderDebug'.
> There were multiple failures while executing work items
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: /Users/massivemadness/Documents/GitHub/OpenCAP/main/app-main/build/intermediates/asm_instrumented_project_classes/debug
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: /Users/massivemadness/Documents/GitHub/OpenCAP/main/app-main/build/intermediates/asm_instrumented_project_classes/debug
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: /Users/massivemadness/Documents/GitHub/OpenCAP/main/app-main/build/intermediates/asm_instrumented_project_classes/debug
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: /Users/massivemadness/Documents/GitHub/OpenCAP/main/app-main/build/intermediates/asm_instrumented_project_classes/debug
```

**Full build output:** [build.txt](https://github.com/google/dagger/files/10358995/build.txt). Let me know if you need more info

**Comment by Chang-Eric** [comment]
Since you said you weren't sure if this was Hilt or AGP, were you using a different AGP version before when it worked?

**Comment by massivemadness** [comment]
Just checked it again on 2.44.2 and everything works 😯
Before creating this issue I did Clean Project / Invalidate Caches, but that didn't help me either. Closing issue
