### ISSUE TITLE
Mocking @HiltViewModels doesn't work

### ISSUE THREAD

**Issue by stephandrab** [google/dagger#3854]
I have the same issue as posted [on stackoverflow](https://stackoverflow.com/questions/68351244/android-test-fragmen-with-mock-viewmodel-using-hilt): I am using a `@HiltViewModel` in an activity + a `@HiltAndroidTests` where I mock out the view model using Mockito with `@BindValue @Mock` to implement an activity unit test. The line `new ViewModelProvider(this).get(MyViewModel.class)` produces this error in the test:

```
java.lang.NullPointerException: Cannot enter synchronized block because "this.mBagOfTags" is null
	at androidx.lifecycle.ViewModel.setTagIfAbsent(ViewModel.java:208)
	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.kt:98)
	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.kt:126)
	// HiltViewModelFactory
	at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.kt:83)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
	// Activity
```

**Comment by danysantiago** [comment]
Hey - This seems like a general issue with Mocking and `androidx.lifecycle.ViewModel` and not really related to Hilt. I think you would run into this issue to even if not using `@HiltViewModel`.
