### ISSUE TITLE
@Binds - Circular binding needs better feedback

### ISSUE THREAD

**Issue by trevjonez** [google/dagger#390]
I created this binding
 `@Binds abstract MemberRepository<Member> memberRepo(MemberRepository<Member> memberRepo);` 
It was a total typo on my part and was intended to be 
`@Binds abstract MemberRepository memberRepo(MemberRepository<Member> memberRepo);`

Didn't take long to find once I saw the stack trace but there was no information about the exact location of the problem or the type involved.

It seems that it should be relatively simple to find and provide an error by comparing the parameter and return types of the annotated ExecutableElement.
# Stack Snippet

```
Caused by: java.lang.StackOverflowError
        at dagger.shaded.auto.common.MoreTypes$3.visitDeclared(MoreTypes.java:392)
        at dagger.shaded.auto.common.MoreTypes$3.visitDeclared(MoreTypes.java:366)
        at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:944)
        at dagger.shaded.auto.common.MoreTypes.hash(MoreTypes.java:458)
        at dagger.shaded.auto.common.MoreTypes.access$100(MoreTypes.java:70)
        at dagger.shaded.auto.common.MoreTypes$1.doHash(MoreTypes.java:79)
        at dagger.shaded.auto.common.MoreTypes$1.doHash(MoreTypes.java:71)
        at com.google.common.base.Equivalence.hash(Equivalence.java:106)
        at com.google.common.base.Equivalence$Wrapper.hashCode(Equivalence.java:220)
        at dagger.internal.codegen.AutoValue_Key.hashCode(AutoValue_Key.java:70)
        at com.google.common.collect.RegularImmutableMap.get(RegularImmutableMap.java:119)
        at com.google.common.collect.RegularImmutableMap.get(RegularImmutableMap.java:111)
        at com.google.common.collect.ImmutableSetMultimap.get(ImmutableSetMultimap.java:362)
        at dagger.internal.codegen.BindingGraph$Factory$Resolver.getExplicitBindings(BindingGraph.java:577)
        at dagger.internal.codegen.BindingGraph$Factory$Resolver.lookUpBindings(BindingGraph.java:360)
        at dagger.internal.codegen.BindingGraph$Factory$Resolver.delegateBindings(BindingGraph.java:462)
        at dagger.internal.codegen.BindingGraph$Factory$Resolver.lookUpBindings(BindingGraph.java:378)
        at dagger.internal.codegen.BindingGraph$Factory$Resolver.delegateBindings(BindingGraph.java:462)
        at dagger.internal.codegen.BindingGraph$Factory$Resolver.lookUpBindings(BindingGraph.java:378)
        at dagger.internal.codegen.BindingGraph$Factory$Resolver.delegateBindings(BindingGraph.java:462)
        at dagger.internal.codegen.BindingGraph$Factory$Resolver.lookUpBindings(BindingGraph.java:378)
        at dagger.internal.codegen.BindingGraph$Factory$Resolver.delegateBindings(BindingGraph.java:462)
```

**Comment by gk5885** [comment]
Whoopsies.

**Comment by ronshapiro** [comment]
@gk5885 I thought you had submitted a fix for this, but I can't seem to find it...

**Comment by ronshapiro** [comment]
Internal: b/73900644

**Comment by bcorso** [comment]
Cleaning up some older bugs...

This issue was fixed a while ago and is covered by [`DependencyCycleValidationTest.selfReferentialBinds()`](https://github.com/google/dagger/blob/master/javatests/dagger/internal/codegen/DependencyCycleValidationTest.java#L682).
