### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by ghousesheikz** [google/dagger#3974]
Caused by: java.lang.IllegalStateException: Unsupported metadata version. Check that your Kotlin version is >= 1.0
	at dagger.internal.codegen.kotlin.KotlinMetadata.metadataOf(KotlinMetadata.java:206)
	at dagger.internal.codegen.kotlin.KotlinMetadata.from(KotlinMetadata.java:186)
	at dagger.internal.codegen.kotlin.KotlinMetadataFactory.create(KotlinMetadataFactory.java:56)
	at dagger.internal.codegen.kotlin.KotlinMetadataUtil.isCompanionObjectClass(KotlinMetadataUtil.java:100)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:116)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:59)
	at dagger.internal.codegen.validation.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:51)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
	at dagger.internal.codegen.validation.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:48)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:104)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:59)
	at dagger.shaded.auto.common.BasicAnnotationProcessor$ProcessingStepAsStep.process(BasicAnnotationProcessor.java:495)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:228)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:208)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:985)

**Comment by ghousesheikz** [comment]
Getting this error when i update my kotlin version from 1.4.3 to 1.8.0
current gradle version is 7.3.1

**Comment by danysantiago** [comment]
Please update your Dagger version to 2.43.2 or higher as that supports Kotlin 1.8: https://github.com/google/dagger/releases/tag/dagger-2.43.2
