### ISSUE TITLE
Firebase breaks Dagger

### ISSUE THREAD

**Issue by digitalbuddha** [google/dagger#399]
We recently added a class that extends `FirebaseMessagingService` to our code base.  We use Dagger2 for dependency injection and noticed that our app started to have compilations errors. If we instead just extend Service everything works fine.

When putting verbose stacktrace on we get following stacktrace
```
Caused by: java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
    at dagger.internal.codegen.writer.ClassName.peerNamed(ClassName.java:130)
    at dagger.internal.codegen.SourceFiles.membersInjectorNameForMembersInjectionBinding(SourceFiles.java:266)
    at dagger.internal.codegen.InjectBindingRegistry.registerBinding(InjectBindingRegistry.java:194)
    at dagger.internal.codegen.InjectBindingRegistry.getOrFindMembersInjectionBinding(InjectBindingRegistry.java:256)
    at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.rollUpMembersInjectionBindings(BindingGraph.java:313)
    at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.rollUpMembersInjectionBindings(BindingGraph.java:317)
    at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.lookUpBindings(BindingGraph.java:305)
    at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.resolve(BindingGraph.java:407)
    at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.resolve(BindingGraph.java:410)
    at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:168)
    at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:105)
```

The key part is:
```
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
    at dagger.internal.codegen.writer.ClassName.peerNamed(ClassName.java:130)
```

Looking at source we see:
```
public ClassName peerNamed(String peerClassName) {
  checkNotNull(peerClassName);
  checkArgument(SourceVersion.isIdentifier(peerClassName));
  checkArgument(Ascii.isUpperCase(peerClassName.charAt(0)));
  return new ClassName(packageName(), enclosingSimpleNames(), peerClassName);
}
```
The line in question is:
  `checkArgument(Ascii.isUpperCase(peerClassName.charAt(0)));`
the issue is due to FirebaseMessagingService extending com.google.firebase.iid.zzb which is in fact a class starting with a lower case letter.  Not sure how I should proceed. Is this validation necessary?

**Comment by caplan** [comment]
this might actually be a javapoet issue - I believe `dagger.internal.codegen.writer.ClassName` is a rebundled `com.squareup.javapoet.ClassName`

**Comment by JakeWharton** [comment]
This is different from [JavaPoet's `peerClass(String)` method][1].

 [1]: https://github.com/square/javapoet/blob/3d54bd91f17fcb212010470f158c5e79c8e79d26/src/main/java/com/squareup/javapoet/ClassName.java#L103-L112

**Comment by artem-zinnatullin** [comment]
JFYI: for now you can solve this by indirect class where you can inject dependencies required for service that extends `FirebaseInstanceIdService`.

Something like this:

```java
class MyFirebaseInstanceIdService extends FirebaseInstanceIdService {
  
  class DiContainer {
    // Container for dependencies required for MyFirebaseInstanceIdService.

    @Inject Dep1 dep1;
    @Inject Dep2 dep2;
  }

  public void onCreate() {
    DiContainer diContainer = new DiContainer();
    MyApp.get(this).objectGraph().inject(diContainer);
   
    // Grab dependencies from diContainer.
  }
}
```

**Comment by ronshapiro** [comment]
No, it's not JavaPoet repackaged, but we removed JavaWriter in favor of JavaPoet a while ago. Can you try to compile with version `2.5` which was just released yesterday and see if you still get a breakage?

**Comment by ronshapiro** [comment]
And if you could post any other relevant information (like Firebase version) that'd be great

**Comment by digitalbuddha** [comment]
@ronshapiro you are gentleman and a scholar.  All set with version 2.5. Thank you for your help

**Comment by goldstei** [comment]
We were using com.google.firebase:firebase-messaging:9.0.2

**Comment by digitalbuddha** [comment]
Also we were on Dagger 2.02 (shamefully)
