### ISSUE TITLE
Bazel sync failed on tag 'dagger-2.42'

### ISSUE THREAD

**Issue by sunyongsheng** [google/dagger#4036]
I want to make some changes on Dagger 2.42 because our project has not been upgraded to AGP 7.0+, so I checkout tag `dagger-2.42`(commit id `46fc0503de3b3a9866d57acc3d6ae9f352de3cad`), following [CONTRIBUTING docs](https://github.com/google/dagger/blob/dagger-2.42/CONTRIBUTING.md#building-dagger) to import dagger project, but sync failed. Run `bazel clean --expunge` doesn't help. Here is the error message:

```
Updating VCS...
Running Bazel info...
Command: /opt/homebrew/bin/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --
INFO: Repository io_bazel_rules_kotlin instantiated at:
  /Users/bytedance/WorkSpace/dagger/WORKSPACE:137:19: in <toplevel>
  /private/var/tmp/_bazel_bytedance/72e6dab39370f4d13f37b5971ea3fa52/external/io_bazel_rules_kotlin_head/src/main/starlark/release_archive/repository.bzl:188:24: in archive_repository
Repository rule _archive_repository defined at:
  /private/var/tmp/_bazel_bytedance/72e6dab39370f4d13f37b5971ea3fa52/external/io_bazel_rules_kotlin_head/src/main/starlark/release_archive/repository.bzl:118:38: in <toplevel>
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_kotlin':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_bytedance/72e6dab39370f4d13f37b5971ea3fa52/external/io_bazel_rules_kotlin_head/src/main/starlark/release_archive/repository.bzl", line 89, column 17, in archive_repository_implementation
		fail("%s: %s\n%s\n\nenv:%s" % (str(workspace), result.stderr, result.stdout, environ))
Error in fail: /private/var/tmp/_bazel_bytedance/72e6dab39370f4d13f37b5971ea3fa52/external/io_bazel_rules_kotlin_head: Loading: 
Loading: 0 packages loaded
DEBUG: /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: buildkite_config not using checked in configs; Bazel version 4.2.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"], "2.0.0": ["10.0.0"], "2.1.0": ["10.0.0"], "2.1.1": ["10.0.0", "11.0.0"], "2.2.0": ["11.0.0"], "3.0.0": ["11.0.0"], "3.1.0": ["11.0.0"], "3.2.0": ["11.0.0"], "3.3.0": ["11.0.0"], "3.3.1": ["11.0.0"], "3.4.1": ["11.0.0"], "3.5.0": ["11.0.0"], "3.5.1": ["11.0.0"], "3.6.0": ["11.0.0"], "3.7.0": ["11.0.0"], "3.7.1": ["11.0.0"], "3.7.2": ["11.0.0"], "4.0.0": ["11.0.0"]}
Analyzing: target //:rules_kotlin_release (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:rules_kotlin_release (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 6] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/external/rkt_1_4/jvm/BUILD.bazel:9:16: PackageTar external/rkt_1_4/jvm/pkg.tgz failed: (Exit 127): build_tar failed: error executing command 
  (cd /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/sandbox/darwin-sandbox/45/execroot/dev_io_bazel_rules_kotlin && \
  exec env - \
    PATH='/Users/bytedance/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-arm64/bin:/Users/bytedance/.rbenv/shims:/Users/bytedance/.rbenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/puppetlabs/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/bytedance/Library/Android/sdk/platform-tools:/Users/bytedance/Library/Android/sdk/tools/bin/:/Users/bytedance/Software/flutter/bin:/Users/bytedance/Software/apache-maven-3.9.3/bin:/Users/bytedance/Library/Application Support/JetBrains/Toolbox/scripts' \
  bazel-out/host/bin/external/rules_pkg/build_tar @bazel-out/darwin_arm64-fastbuild/bin/external/rkt_1_4/jvm/pkg.args)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
env: python: No such file or directory
Target //:rules_kotlin_release failed to build
INFO: Elapsed time: 0.195s, Critical Path: 0.10s
INFO: 11 processes: 11 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully



env:{"ANDROID_HOME": "/Users/bytedance/Library/Android/sdk", "ANDROID_NDK_HOME": "/Users/bytedance/Library/Android/sdk/ndk", "ANDROID_SDK_TOOLS": "/Users/bytedance/Library/Android/sdk/tools/bin/", "ANDROID_TOOLS": "/Users/bytedance/Library/Android/sdk/platform-tools", "BAZELISK_SKIP_WRAPPER": "true", "COMMAND_MODE": "unix2003", "FLUTTER_HOME": "/Users/bytedance/Software/flutter/bin", "HOME": "/Users/bytedance", "HOMEBREW_CELLAR": "/opt/homebrew/Cellar", "HOMEBREW_PREFIX": "/opt/homebrew", "HOMEBREW_REPOSITORY": "/opt/homebrew", "INFOPATH": "/opt/homebrew/share/info:", "JAVA_11": "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/", "JAVA_17": "/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/", "JAVA_1_8": "/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/", "JAVA_HOME": "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/", "LC_CTYPE": "en_US.UTF-8", "LESS": "-R", "LOGNAME": "bytedance", "LSCOLORS": "Gxfxcxdxbxegedabagacad", "LS_COLORS": "di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43", "MANPATH": "/opt/homebrew/share/man::", "MAVEN_HOME": "/Users/bytedance/Software/apache-maven-3.9.3/bin", "OLDPWD": "/", "PAGER": "less", "PATH": "/Users/bytedance/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-arm64/bin:/Users/bytedance/.rbenv/shims:/Users/bytedance/.rbenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/puppetlabs/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/bytedance/Library/Android/sdk/platform-tools:/Users/bytedance/Library/Android/sdk/tools/bin/:/Users/bytedance/Software/flutter/bin:/Users/bytedance/Software/apache-maven-3.9.3/bin:/Users/bytedance/Library/Application Support/JetBrains/Toolbox/scripts", "PWD": "/Users/bytedance/WorkSpace/dagger", "RBENV": "/Users/bytedance/.rbenv/bin", "RBENV_SHELL": "zsh", "SHELL": "/bin/zsh", "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.Y63bRs0YSv/Listeners", "TMPDIR": "/var/folders/b1/0fd1b6hs7lz0fm_mh346lybm0000gn/T/", "TOOLBOX_SCRIPTS": "/Users/bytedance/Library/Application Support/JetBrains/Toolbox/scripts", "USER": "bytedance", "XPC_FLAGS": "0x0", "XPC_SERVICE_NAME": "application.com.google.android.studio.79307268.79311417", "ZSH": "/Users/bytedance/.oh-my-zsh", "__CFBundleIdentifier": "com.google.android.studio", "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0"}
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_bytedance/72e6dab39370f4d13f37b5971ea3fa52/external/io_bazel_rules_kotlin_head/src/main/starlark/release_archive/repository.bzl", line 89, column 17, in archive_repository_implementation
		fail("%s: %s\n%s\n\nenv:%s" % (str(workspace), result.stderr, result.stdout, environ))
Error in fail: /private/var/tmp/_bazel_bytedance/72e6dab39370f4d13f37b5971ea3fa52/external/io_bazel_rules_kotlin_head: Loading: 
Loading: 0 packages loaded
DEBUG: /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: buildkite_config not using checked in configs; Bazel version 4.2.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"], "2.0.0": ["10.0.0"], "2.1.0": ["10.0.0"], "2.1.1": ["10.0.0", "11.0.0"], "2.2.0": ["11.0.0"], "3.0.0": ["11.0.0"], "3.1.0": ["11.0.0"], "3.2.0": ["11.0.0"], "3.3.0": ["11.0.0"], "3.3.1": ["11.0.0"], "3.4.1": ["11.0.0"], "3.5.0": ["11.0.0"], "3.5.1": ["11.0.0"], "3.6.0": ["11.0.0"], "3.7.0": ["11.0.0"], "3.7.1": ["11.0.0"], "3.7.2": ["11.0.0"], "4.0.0": ["11.0.0"]}
Analyzing: target //:rules_kotlin_release (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:rules_kotlin_release (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 6] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/external/rkt_1_4/jvm/BUILD.bazel:9:16: PackageTar external/rkt_1_4/jvm/pkg.tgz failed: (Exit 127): build_tar failed: error executing command 
  (cd /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/sandbox/darwin-sandbox/45/execroot/dev_io_bazel_rules_kotlin && \
  exec env - \
    PATH='/Users/bytedance/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-arm64/bin:/Users/bytedance/.rbenv/shims:/Users/bytedance/.rbenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/puppetlabs/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/bytedance/Library/Android/sdk/platform-tools:/Users/bytedance/Library/Android/sdk/tools/bin/:/Users/bytedance/Software/flutter/bin:/Users/bytedance/Software/apache-maven-3.9.3/bin:/Users/bytedance/Library/Application Support/JetBrains/Toolbox/scripts' \
  bazel-out/host/bin/external/rules_pkg/build_tar @bazel-out/darwin_arm64-fastbuild/bin/external/rkt_1_4/jvm/pkg.args)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
env: python: No such file or directory
Target //:rules_kotlin_release failed to build
INFO: Elapsed time: 0.195s, Critical Path: 0.10s
INFO: 11 processes: 11 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully



env:{"ANDROID_HOME": "/Users/bytedance/Library/Android/sdk", "ANDROID_NDK_HOME": "/Users/bytedance/Library/Android/sdk/ndk", "ANDROID_SDK_TOOLS": "/Users/bytedance/Library/Android/sdk/tools/bin/", "ANDROID_TOOLS": "/Users/bytedance/Library/Android/sdk/platform-tools", "BAZELISK_SKIP_WRAPPER": "true", "COMMAND_MODE": "unix2003", "FLUTTER_HOME": "/Users/bytedance/Software/flutter/bin", "HOME": "/Users/bytedance", "HOMEBREW_CELLAR": "/opt/homebrew/Cellar", "HOMEBREW_PREFIX": "/opt/homebrew", "HOMEBREW_REPOSITORY": "/opt/homebrew", "INFOPATH": "/opt/homebrew/share/info:", "JAVA_11": "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/", "JAVA_17": "/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/", "JAVA_1_8": "/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/", "JAVA_HOME": "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/", "LC_CTYPE": "en_US.UTF-8", "LESS": "-R", "LOGNAME": "bytedance", "LSCOLORS": "Gxfxcxdxbxegedabagacad", "LS_COLORS": "di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43", "MANPATH": "/opt/homebrew/share/man::", "MAVEN_HOME": "/Users/bytedance/Software/apache-maven-3.9.3/bin", "OLDPWD": "/", "PAGER": "less", "PATH": "/Users/bytedance/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-arm64/bin:/Users/bytedance/.rbenv/shims:/Users/bytedance/.rbenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/puppetlabs/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/bytedance/Library/Android/sdk/platform-tools:/Users/bytedance/Library/Android/sdk/tools/bin/:/Users/bytedance/Software/flutter/bin:/Users/bytedance/Software/apache-maven-3.9.3/bin:/Users/bytedance/Library/Application Support/JetBrains/Toolbox/scripts", "PWD": "/Users/bytedance/WorkSpace/dagger", "RBENV": "/Users/bytedance/.rbenv/bin", "RBENV_SHELL": "zsh", "SHELL": "/bin/zsh", "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.Y63bRs0YSv/Listeners", "TMPDIR": "/var/folders/b1/0fd1b6hs7lz0fm_mh346lybm0000gn/T/", "TOOLBOX_SCRIPTS": "/Users/bytedance/Library/Application Support/JetBrains/Toolbox/scripts", "USER": "bytedance", "XPC_FLAGS": "0x0", "XPC_SERVICE_NAME": "application.com.google.android.studio.79307268.79311417", "ZSH": "/Users/bytedance/.oh-my-zsh", "__CFBundleIdentifier": "com.google.android.studio", "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0"}
ERROR: no such package '@io_bazel_rules_kotlin//kotlin': /private/var/tmp/_bazel_bytedance/72e6dab39370f4d13f37b5971ea3fa52/external/io_bazel_rules_kotlin_head: Loading: 
Loading: 0 packages loaded
DEBUG: /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: buildkite_config not using checked in configs; Bazel version 4.2.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"], "2.0.0": ["10.0.0"], "2.1.0": ["10.0.0"], "2.1.1": ["10.0.0", "11.0.0"], "2.2.0": ["11.0.0"], "3.0.0": ["11.0.0"], "3.1.0": ["11.0.0"], "3.2.0": ["11.0.0"], "3.3.0": ["11.0.0"], "3.3.1": ["11.0.0"], "3.4.1": ["11.0.0"], "3.5.0": ["11.0.0"], "3.5.1": ["11.0.0"], "3.6.0": ["11.0.0"], "3.7.0": ["11.0.0"], "3.7.1": ["11.0.0"], "3.7.2": ["11.0.0"], "4.0.0": ["11.0.0"]}
Analyzing: target //:rules_kotlin_release (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:rules_kotlin_release (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 6] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/external/rkt_1_4/jvm/BUILD.bazel:9:16: PackageTar external/rkt_1_4/jvm/pkg.tgz failed: (Exit 127): build_tar failed: error executing command 
  (cd /private/var/tmp/_bazel_bytedance/82944a7fbba87d7b74345b43ba6dd1fc/sandbox/darwin-sandbox/45/execroot/dev_io_bazel_rules_kotlin && \
  exec env - \
    PATH='/Users/bytedance/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-arm64/bin:/Users/bytedance/.rbenv/shims:/Users/bytedance/.rbenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/puppetlabs/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/bytedance/Library/Android/sdk/platform-tools:/Users/bytedance/Library/Android/sdk/tools/bin/:/Users/bytedance/Software/flutter/bin:/Users/bytedance/Software/apache-maven-3.9.3/bin:/Users/bytedance/Library/Application Support/JetBrains/Toolbox/scripts' \
  bazel-out/host/bin/external/rules_pkg/build_tar @bazel-out/darwin_arm64-fastbuild/bin/external/rkt_1_4/jvm/pkg.args)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
env: python: No such file or directory
Target //:rules_kotlin_release failed to build
INFO: Elapsed time: 0.195s, Critical Path: 0.10s
INFO: 11 processes: 11 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully



env:{"ANDROID_HOME": "/Users/bytedance/Library/Android/sdk", "ANDROID_NDK_HOME": "/Users/bytedance/Library/Android/sdk/ndk", "ANDROID_SDK_TOOLS": "/Users/bytedance/Library/Android/sdk/tools/bin/", "ANDROID_TOOLS": "/Users/bytedance/Library/Android/sdk/platform-tools", "BAZELISK_SKIP_WRAPPER": "true", "COMMAND_MODE": "unix2003", "FLUTTER_HOME": "/Users/bytedance/Software/flutter/bin", "HOME": "/Users/bytedance", "HOMEBREW_CELLAR": "/opt/homebrew/Cellar", "HOMEBREW_PREFIX": "/opt/homebrew", "HOMEBREW_REPOSITORY": "/opt/homebrew", "INFOPATH": "/opt/homebrew/share/info:", "JAVA_11": "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/", "JAVA_17": "/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/", "JAVA_1_8": "/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/", "JAVA_HOME": "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/", "LC_CTYPE": "en_US.UTF-8", "LESS": "-R", "LOGNAME": "bytedance", "LSCOLORS": "Gxfxcxdxbxegedabagacad", "LS_COLORS": "di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43", "MANPATH": "/opt/homebrew/share/man::", "MAVEN_HOME": "/Users/bytedance/Software/apache-maven-3.9.3/bin", "OLDPWD": "/", "PAGER": "less", "PATH": "/Users/bytedance/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-arm64/bin:/Users/bytedance/.rbenv/shims:/Users/bytedance/.rbenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/puppetlabs/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/bytedance/Library/Android/sdk/platform-tools:/Users/bytedance/Library/Android/sdk/tools/bin/:/Users/bytedance/Software/flutter/bin:/Users/bytedance/Software/apache-maven-3.9.3/bin:/Users/bytedance/Library/Application Support/JetBrains/Toolbox/scripts", "PWD": "/Users/bytedance/WorkSpace/dagger", "RBENV": "/Users/bytedance/.rbenv/bin", "RBENV_SHELL": "zsh", "SHELL": "/bin/zsh", "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.Y63bRs0YSv/Listeners", "TMPDIR": "/var/folders/b1/0fd1b6hs7lz0fm_mh346lybm0000gn/T/", "TOOLBOX_SCRIPTS": "/Users/bytedance/Library/Application Support/JetBrains/Toolbox/scripts", "USER": "bytedance", "XPC_FLAGS": "0x0", "XPC_SERVICE_NAME": "application.com.google.android.studio.79307268.79311417", "ZSH": "/Users/bytedance/.oh-my-zsh", "__CFBundleIdentifier": "com.google.android.studio", "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0"}
```

My Android Studio info is:

```
Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 12800M
Cores: 10
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.experimental.ui=true
```

MacOS version is `13.5 (22G74)`. Specify Bazel version as 4.2.1 by creating file `.bazelversion`.

**Comment by bcorso** [comment]
Hmm, I'm not sure. None of the error messages are directly related to Dagger, so it's likely something specific to your setup.

One thing that sticks out is `env: python: No such file or directory`. You will need to `python` installed to install some of the dependencies. If you already have python installed but it's under `python3` you may also need the [python-is-python3 package](https://askubuntu.com/a/1296793)).

**Comment by sunyongsheng** [comment]
> Hmm, I'm not sure. None of the error messages are directly related to Dagger, so it's likely something specific to your setup.
> 
> One thing that sticks out is `env: python: No such file or directory`. You will need to `python` installed to install some of the dependencies. If you already have python installed but it's under `python3` you may also need the [python-is-python3 package](https://askubuntu.com/a/1296793)).

`Python` should not be the primary reason because `python` can run properly in CLI(`python` is the alias of python3). I checkout to the latest commit, anything works, soI guess if there is any issue in the Bazel `BUILD`/`WORKSPACE` file or a missing Bazel configuration that is not listed in the CONTRIBUTING docs for the old version of Dagger?

**Comment by bcorso** [comment]
I would try first seeing if you can get Dagger 2.42 building separately from your other project (i.e. in a minimal reproducible example project). If you still can't get it to work you can link the minimal reproducible example project and we can take a closer look.

**Comment by sunyongsheng** [comment]
> I would try first seeing if you can get Dagger 2.42 building separately from your other project (i.e. in a minimal reproducible example project). If you still can't get it to work you can link the minimal reproducible example project and we can take a closer look.

Well, using Dagger in project is ok.  I encountered the same issue on another computer when import Dagger project. Can you try building Dagger 2.42 on your computer to see if there are any errors?

**Comment by sunyongsheng** [comment]
It seems that the issue is not related to the Android Studio version. I used Android Studio Arctic Fox, but still got the same error.
