### ISSUE TITLE
[KSP] Unhelpful "Check failed" error when migrating project to Dagger KSP

### ISSUE THREAD

**Issue by msfjarvis** [google/dagger#4042]
While migrating my project to Dagger KSP [msfjarvis/compose-lobsters@`c441963` (#397)](https://github.com/msfjarvis/compose-lobsters/pull/397/commits/c441963d988591ce33e936bf9c9dd020fe9900a3), I ran into an assertion failure that I can't find any way to debug on my end.

The failing `check` is [here](https://github.com/androidx/androidx/blob/7bc858c034eb03c4f4422b275f47f34016af5df6/room/room-compiler-processing/src/main/java/androidx/room/compiler/processing/ksp/KspType.kt#L127C16-L127C16), which manifests as this:

```
> Task :android:kspDebugKotlin FAILED
e: [ksp] java.lang.IllegalStateException: Check failed.
        at dagger.spi.shaded.androidx.room.compiler.processing.ksp.KspType$superTypes$2.invoke(KspType.kt:127)
        at dagger.spi.shaded.androidx.room.compiler.processing.ksp.KspType$superTypes$2.invoke(KspType.kt:103)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at dagger.spi.shaded.androidx.room.compiler.processing.ksp.KspType.getSuperTypes(KspType.kt:103)
        at dagger.internal.codegen.xprocessing.XTypes.nonObjectSuperclass(XTypes.java:392)
        at dagger.internal.codegen.binding.InjectionSiteFactory.getInjectionSites(InjectionSiteFactory.java:67)
        at dagger.internal.codegen.binding.BindingFactory.membersInjectionBinding(BindingFactory.java:518)
        at dagger.internal.codegen.validation.InjectBindingRegistryImpl.tryRegisterMembersInjectedType(InjectBindingRegistryImpl.java:318)
        at dagger.internal.codegen.validation.InjectBindingRegistryImpl.tryRegisterInjectField(InjectBindingRegistryImpl.java:283)
        at dagger.internal.codegen.processingstep.InjectProcessingStep.process(InjectProcessingStep.java:75)
        at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:82)
```

The app does use Square's [Anvil](https://github.com/square/anvil) compiler plugin and an [extension built on top of it](https://github.com/msfjarvis/whetstone) so there's a non-zero possibility Dagger itself is not responsible, but I figured I would report here anyway and get any pointers if the fix needs to be outside Dagger.

**Comment by bcorso** [comment]
Thanks for reporting this!

This may be due to the KSP bug here: https://github.com/google/ksp/issues/1443.

We can add more information in the exception message to help you pin point where this is failing in your code. This may take a few days though, as we'll need to update the XProcessing library first and then drop the new jars into Dagger.

**Comment by msfjarvis** [comment]
This was fixed
