### ISSUE TITLE
[KSP] java.lang.NoSuchMethodError: 'boolean dagger.internal.codegen.xprocessing.XTypeElements.isKotlinSource(dagger.spi.shaded.androidx.room.compiler.processing.XTypeElement)'

### ISSUE THREAD

**Issue by ZhaohuaZeng-at** [google/dagger#4043]
Hi team,

When trying to migrate to ksp from kapt in dagger 2.48, I encountered the following compilation error. Is there anything I am missing?

```
kotlin version: 1.9.0
error message: java.lang.NoSuchMethodError: 'boolean dagger.internal.codegen.xprocessing.XTypeElements.isKotlinSource(dagger.spi.shaded.androidx.room.compiler.processing.XTypeElement)'
	at dagger.hilt.android.processor.internal.androidentrypoint.AndroidEntryPointMetadata.generatedClassModifiers(AndroidEntryPointMetadata.java:162)
	at dagger.hilt.android.processor.internal.androidentrypoint.ActivityGenerator.generate(ActivityGenerator.java:53)
	at dagger.hilt.android.processor.internal.androidentrypoint.AndroidEntryPointProcessingStep.processEach(AndroidEntryPointProcessingStep.java:93)
	at dagger.hilt.processor.internal.BaseProcessingStep.process(BaseProcessingStep.java:118)
	at dagger.hilt.processor.internal.BaseProcessingStep.process(BaseProcessingStep.java:49)
	at dagger.spi.shaded.androidx.room.compiler.processing.CommonProcessorDelegate.processRound(XBasicAnnotationProcessor.kt:130)
	at dagger.spi.shaded.androidx.room.compiler.processing.ksp.KspBasicAnnotationProcessor.process(KspBasicAnnotationProcessor.kt:62)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:305)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:303)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:409)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:303)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:168)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1497)
	at jdk.internal.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by bcorso** [comment]
Hi @ZhaohuaZeng-at,

My guess is that you upgraded the dagger compiler to 2.48 but forgot to upgrade the hilt compiler. 

The error message mentions a `NoSuchMethodError`:

```
error message: java.lang.NoSuchMethodError: 'boolean dagger.internal.codegen.xprocessing.XTypeElements.isKotlinSource(dagger.spi.shaded.androidx.room.compiler.processing.XTypeElement)'
```

That method was removed from 2.47 to 2.48:

https://github.com/google/dagger/compare/dagger-2.47...dagger-2.48#diff-d025296358eb932e86e361ed594c051a0ba22ca8d3cf7e3ea63e1f9623b19f85

**Comment by ZhaohuaZeng-at** [comment]
Hi @bcorso , thank you for the quick response! This solved my issue!

**Comment by diegoflassa** [comment]
Which version of the hilt compiler should i use?

**Comment by bcorso** [comment]
@diegoflassa the important thing is that your dagger and hilt versions match. 

If you're using `com.google.dagger:dagger-compiler:2.48` you should be using `com.google.dagger:hilt-compiler:2.48`

**Comment by Daphne-CoffeeIT** [comment]
Is there already a solution? I have the same issue, both when using 2.48 and 2.48.1, so currently I can't upgrade. I use the same version for the dependancy as for the compiler.

**Comment by bcorso** [comment]
> Is there already a solution?

Yes, the solution is https://github.com/google/dagger/issues/4043#issuecomment-1699765199, i.e. make sure all of your hilt/dagger dependencies are on the same version.

> I use the same version for the dependency as for the compiler.

If you're getting this error then I don't think that can be true. The only way you can get this error is if you're on two different versions, so something must be pulling in a different version.

**Comment by Daphne-CoffeeIT** [comment]
@bcorso I'm 100% sure I'm using the same version, since the version is in a variable that's used in both places.

**Comment by bcorso** [comment]
> I'm 100% sure I'm using the same version

The code that triggers the error only exists in Dagger 2.47 (it was removed in Dagger 2.48), thus something is still calling Dagger 2.47. If it's not your library then maybe it's one of your transitive dependencies.

Can you share the list of your projects dependencies (https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html)? I think you just need to run `gradle -q dependencies` or something similar.
