### ISSUE TITLE
NoSuchMethodError on update from 2.48 to 2.48.1 

### ISSUE THREAD

**Issue by yschimke** [google/dagger#4090]
Failure https://github.com/google/horologist/actions/runs/6400908679/job/17375185682?pr=1727

Change https://github.com/google/horologist/pull/1727/files

```
> Task :media:sync:kspDebugKotlin FAILED
Errors were stored into /home/runner/work/horologist/horologist/.gradle/kotlin/errors/errors-1696387233637.log
e: java.lang.NoSuchMethodError: 'kotlin.sequences.Sequence com.google.devtools.ksp.processing.Resolver.getPackagesWithAnnotation(java.lang.String)'
	at dagger.spi.shaded.androidx.room.compiler.processing.ksp.KspRoundEnv.getElementsAnnotatedWith(KspRoundEnv.kt:107)
	at dagger.spi.shaded.androidx.room.compiler.processing.CommonProcessorDelegate.processRound(XBasicAnnotationProcessor.kt:100)
	at dagger.spi.shaded.androidx.room.compiler.processing.ksp.KspBasicAnnotationProcessor.process(KspBasicAnnotationProcessor.kt:62)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:291)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:289)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:394)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:289)
```

**Comment by bcorso** [comment]
Hmm, which version of KSP are you using?

Dagger KSP requires at least [`1.9.0-1.0.12`](https://dagger.dev/dev-guide/ksp#setup).

The method should be included here: https://github.com/google/ksp/blob/1.9.0-1.0.12/api/src/main/kotlin/com/google/devtools/ksp/processing/Resolver.kt#L320C9-L320C34

**Comment by yschimke** [comment]
Is it worth failing early if that isn't met?

**Comment by bcorso** [comment]
I don't think there's a way for us to fail early since checking dependencies is done at the Gradle level which Dagger's processors don't have access to.

In general though, when you get a `NoSuchMethodError` it typically means the version of the class that was used when compiling the library isn't the same as the version currently being used at runtime:

> public class NoSuchMethodError extends [IncompatibleClassChangeError](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/lang/IncompatibleClassChangeError.html)
>
>Thrown if an application tries to call a specified method of a class (either static or instance), and that class no longer has a definition of that method.
>
>Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.

So the first thing you typically want to try is to find out which version of the dependency added that method then update the version of that dependency to a version where you know the method exists.

**Comment by yschimke** [comment]
Versions all documented here https://dagger.dev/dev-guide/ksp, so closing.  Thanks for the quick help.
