### ISSUE TITLE
[KSP] java.lang.IllegalStateException

### ISSUE THREAD

**Issue by kemaltunc** [google/dagger#4140]
Hi,

#4046 

I'm having a similar problem and I thought it would be fixed in version 2.48.1. But the same problem continues.

hilt version:2.48.1

[ksp] java.lang.IllegalStateException: Don't know how to convert element of type 'class dagger.spi.shaded.androidx.room.compiler.processing.ksp.synthetic.KspSyntheticPropertyMethodElement$Setter$SyntheticExecutableParameterElement' to KSP
	at dagger.spi.shaded.androidx.room.compiler.processing.compat.XConverters.toKS(XConverters.kt:205)
	at dagger.internal.codegen.xprocessing.XElements.isFromJavaSource(XElements.java:393)
	at dagger.internal.codegen.binding.Nullability.isKotlinTypeNullable(Nullability.java:65)
	at dagger.internal.codegen.binding.Nullability.of(Nullability.java:52)
	at dagger.internal.codegen.binding.DependencyRequestFactory.newDependencyRequest(DependencyRequestFactory.java:228)
	at dagger.internal.codegen.binding.DependencyRequestFactory.forRequiredResolvedVariable(DependencyRequestFactory.java:139)
	at dagger.internal.codegen.binding.DependencyRequestFactory.forRequiredResolvedVariables(DependencyRequestFactory.java:76)
	at dagger.internal.codegen.binding.InjectionSiteFactory$InjectionSiteVisitor.visitMethod(InjectionSiteFactory.java:122)
	at dagger.internal.codegen.binding.InjectionSiteFactory$InjectionSiteVisitor.visit(InjectionSiteFactory.java:96)
	at dagger.internal.codegen.binding.InjectionSiteFactory.getInjectionSites(InjectionSiteFactory.java:73)
	at dagger.internal.codegen.binding.BindingFactory.membersInjectionBinding(BindingFactory.java:518)
	at dagger.internal.codegen.validation.InjectBindingRegistryImpl.tryRegisterMembersInjectedType(InjectBindingRegistryImpl.java:366)
	at dagger.internal.codegen.validation.InjectBindingRegistryImpl.tryRegisterInjectField(InjectBindingRegistryImpl.java:322)
	at dagger.internal.codegen.processingstep.InjectProcessingStep.process(InjectProcessingStep.java:75)
	at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:82)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:292)
	at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:70)
	at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:48)
	at dagger.spi.shaded.androidx.room.compiler.processing.XProcessingStep.process(XProcessingStep.kt:59)
	at dagger.spi.shaded.androidx.room.compiler.processing.CommonProcessorDelegate.processRound(XBasicAnnotationProcessor.kt:130)
	at dagger.spi.shaded.androidx.room.compiler.processing.ksp.KspBasicAnnotationProcessor.process(KspBasicAnnotationProcessor.kt:62)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:305)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:303)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:409)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:303)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
	at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by kuanyingchou** [comment]
Hi, @kemaltunc , thanks for reporting. It looks like we didn't fix the bug in XProcessing (we made `XElement.getProcessingEnv()` enhaustive but not `XElement.toKS()`). Could you give [HEAD-SNAPSHOT](https://dagger.dev/dev-guide/versions.html) a try as we already removed `XElements.isFromJavaSource` in master?

**Comment by kemaltunc** [comment]
Hi, @kuanyingchou  I get this error when I try with HEAD-SNAPSHOT. But I'm not sure if it's related to KSP

[ksp] [Hilt] No property named assistedFactory was found in annotation HiltViewModel: java.lang.IllegalStateException: No property named assistedFactory was found in annotation HiltViewModel
	at dagger.spi.internal.shaded.androidx.room.compiler.processing.InternalXAnnotation.getAnnotationValue(InternalXAnnotation.kt:30)
	at dagger.spi.internal.shaded.androidx.room.compiler.processing.XAnnotation.getAsType(XAnnotation.kt:81)
	at dagger.hilt.android.processor.internal.viewmodel.ViewModelMetadata$Companion.create$java_dagger_hilt_android_processor_internal_viewmodel_processor_lib(ViewModelMetadata.kt:80)
	at dagger.hilt.android.processor.internal.viewmodel.ViewModelProcessingStep.processEach(ViewModelProcessingStep.kt:36)
	at dagger.hilt.processor.internal.BaseProcessingStep.process(BaseProcessingStep.java:118)
	at dagger.hilt.processor.internal.BaseProcessingStep.process(BaseProcessingStep.java:49)
	at dagger.spi.internal.shaded.androidx.room.compiler.processing.CommonProcessorDelegate.processRound(XBasicAnnotationProcessor.kt:132)
	at dagger.spi.internal.shaded.androidx.room.compiler.processing.ksp.KspBasicAnnotationProcessor.process(KspBasicAnnotationProcessor.kt:62)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:305)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:303)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:409)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:303)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
	at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

[1;31m[Hilt] Processing did not complete. See error above for details.[0m

**Comment by kuanyingchou** [comment]
Hi, @kemaltunc , this could happen if the dependencies don't match. Could it be that ` com.google.dagger:hilt-android` hasn't been updated to HEAD-SNAPSHOT?

**Comment by kemaltunc** [comment]
Hi, @kuanyingchou This problem continues for me. HEAD-SNAPSHOT did not work for me but I do not have any problems with dagger 2.47 version. Will there be a fix for this in future versions of Dagger?

**Comment by kuanyingchou** [comment]
Hi, @kemaltunc , are you still seeing the "No property named assistedFactory was found in annotation HiltViewModel" error above or are you seeing some other error with HEAD-SNAPSHOT?

**Comment by kemaltunc** [comment]
Yes, I still see the error "No property named assistedFactory was found in annotation HiltViewModel". Thank you for support

**Comment by kuanyingchou** [comment]
Thanks for the version config. Has the Hilt Gradle Plugin also changed to HEAD-SNAPSHOT?
```
plugins {
  ...
  id("com.google.dagger.hilt.android") version "HEAD-SNAPSHOT" apply false
}
``` 
You may also need to ensure nothing is using the old version with the config here: https://github.com/google/dagger/issues/3401#issuecomment-1129224521

**Comment by kemaltunc** [comment]
I am sorry this is my mistake:(. There is more than one module in my project.
 configurations.all { 
    resolutionStrategy.eachDependency {
        if (requested.group == "com.google.dagger") {
            useVersion("HEAD-SNAPSHOT")
        }
    }
}
I forgot to add for some modules. Now I can run it without any problems with the HEAD-SNAPSHOT version. Now I have to wait for the stable version

**Comment by kemaltunc** [comment]
@kuanyingchou Is the release date known?

**Comment by kuanyingchou** [comment]
Hi, @kemaltunc , I think it should happen sometime next week: https://github.com/google/dagger/issues/4096#issuecomment-1823028953
