### ISSUE TITLE
Getting crash `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/collect/ImmutableSet` on Fragment inject

### ISSUE THREAD

**Issue by Ekalips** [google/dagger#4142]
Since recently we've started getting the following crash in our app. The crash is happening on the first Fragment inject. It only happens in a Release build with proguard/r8 obfuscation (full mode or not). 

Libraries used:
```
    implementation("com.google.dagger:hilt-android:2.48.1")
    kapt("com.google.dagger:hilt-android-compiler:2.48.1")
    kapt("androidx.hilt:hilt-compiler:1.1.0")
```
(Note: this is also reproducible on v2.48 and hilt-compile 1.0.0.)

Gradle Version: 8.1
Gradle Plugin: 8.1.3
R8 Version: 8.1.56
Kotlin: 1.9.20

Crash log

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/collect/ImmutableSet;
       at com.[REDACTED].Dagger[REDACTED]_HiltComponents_SingletonC$SingletonCImpl.getDisableFragmentGetContextFix(Dagger[REDACTED]_HiltComponents_SingletonC.java:3156)
       at dagger.hilt.android.flags.FragmentGetContextFix.isFragmentGetContextFixDisabled(FragmentGetContextFix.java:68)
       at com.[REDACTED]..features.welcome.onboarding.Hilt_OnboardingFragment.initializeComponentContext(Hilt_OnboardingFragment.java:64)
       at com.[REDACTED].features.welcome.onboarding.Hilt_OnboardingFragment.onAttach(Hilt_OnboardingFragment.java:56)
       at androidx.fragment.app.Fragment.onAttach(Fragment.java:1883)
       at com.[REDACTED].commons.BaseFragment.onAttach(BaseFragment.kt:74)
       at com.[REDACTED].features.welcome.onboarding.Hilt_OnboardingFragment.onAttach(Hilt_OnboardingFragment.java:44)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:3068)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:490)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:265)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
       at com.[REDACTED].commons.BaseActivity.onStart(BaseActivity.kt:98)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
       at android.app.Activity.performStart(Activity.java:8330)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

The temporary solution seems to be to include the latest `com.google.guava:guava` in the app's build config.

**Comment by bcorso** [comment]
> It only happens in a Release build with proguard/r8 obfuscation (full mode or not).

If it only happens with proguard/r8 it sounds like this is an issue with proguard/r8. In particular, if the code runs fine without the optimization/obfuscation then I'm not sure there's anything Dagger can do to fix something that is broken after the optimization/obfuscation. Thus, I think you should file a bug to the proguard/r8 team.

I'm going to close this for now but feel free to link the bug or add more details if you think it's relevant to Dagger.

**Comment by Ekalips** [comment]
@bcorso thanks for your response. I've filled this bug for Dagger/Hilt because I think that it might be a missing ProGuard config for a thing that is used in Dagger/Hilt internally. ImmutableSet gets obfuscated away when it shouldn't, usually libraries provide their ProGuard configs to prevent it.
