### ISSUE TITLE
Feature request: Add support for K2 compiler.

### ISSUE THREAD

**Issue by lubo-pisk** [google/dagger#4211]
I have following configuration:

K2 Compiler
Kotlin 2.0.0-Beta1
Dagger 2.50

kotlin.experimental.tryK2=true
kapt.use.k2=true

Build failed with error:

```
error: annotation @SuppressLint is missing a default value for the element 'value'
```

Only Dagger uses kapt in my project.

Build is ok when kapt.use.k2=false.

**Comment by bcorso** [comment]
Do you have an example where this `@SuppressLint` usage is coming from?

I don't think Dagger uses `@SuppressLint` anywhere in our API or generated code, so it's unclear what we could do to fix this on our side.

**Comment by dniHze** [comment]
We don't see the same problem in our codebase. However, Dagger uses `kotlinx-metadata` to process Kotlin code in the kapt processor. In our project, compiling it with K2 KAPT enabled will produce NullPointer exception [there](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/room-compiler-processing/src/main/java/androidx/room/compiler/processing/javac/kotlin/KotlinClassMetadataUtils.kt;l=256?q=KotlinClassMetadataUtils). As Kotlin 2.0.0 comes with [a new stable artifact](https://github.com/JetBrains/kotlin/blob/master/libraries/kotlinx-metadata/jvm/Migration.md#migrating-from-090-to-stable-2xx) for metadata processing, which makes it incompatible with the metadata generated with the K2/kapt. Resolving this requires an update to the newer artifact. I'm not so sure if the newer artifact will be backward compatible with K1-produced code though.

**Comment by Tapchicoma** [comment]
FYI: Dagger latest release is failing with Kotlin `2.1.0` pre-releases cause of:
```
Caused by: java.lang.IllegalStateException: Unable to read Kotlin metadata due to unsupported metadata version.
        at dagger.internal.codegen.kotlin.KotlinMetadata.metadataOf(KotlinMetadata.java:180)
        at dagger.internal.codegen.kotlin.KotlinMetadata.from(KotlinMetadata.java:157)
        at dagger.internal.codegen.kotlin.KotlinMetadataFactory.create(KotlinMetadataFactory.java:55)
        at dagger.internal.codegen.kotlin.KotlinMetadataUtil.isMissingSyntheticPropertyForAnnotations(KotlinMetadataUtil.java:75)
        at dagger.internal.codegen.validation.DependencyRequestValidator.missingQualifierMetadata(DependencyRequestValidator.java:108)
        at dagger.internal.codegen.validation.DependencyRequestValidator.validateDependencyRequest(DependencyRequestValidator.java:81)
        at dagger.internal.codegen.validation.InjectValidator.validateDependencyRequest(InjectValidator.java:358)
        at dagger.internal.codegen.validation.InjectValidator.validateField(InjectValidator.java:309)
        at dagger.internal.codegen.validation.InjectValidator.validateForMembersInjectionInternalUncached(InjectValidator.java:382)
        at dagger.internal.codegen.base.Util.reentrantComputeIfAbsent(Util.java:33)
        at dagger.internal.codegen.validation.InjectValidator.validateForMembersInjectionInternal(InjectValidator.java:369)
        at dagger.internal.codegen.validation.InjectValidator.validateUncached(InjectValidator.java:143)
        at dagger.internal.codegen.base.Util.reentrantComputeIfAbsent(Util.java:33)
```

You need to migrate to new stable artifact of Kotlin - it should work with K1 metadata just fine.

**Comment by bcorso** [comment]
@Tapchicoma which version of `kotlin-metadata-jvm` is required?

I can upgrade to `2.0.0-Beta5` immediately, but looks like there are some API changes starting with `2.0.0` that I would need to look into if you needed something more recent.

**Comment by bcorso** [comment]
Dagger's [`HEAD-SNAPSHOT`](https://dagger.dev/dev-guide/versions) should be using `2.0.0-Beta5` now. 

@Tapchicoma, I'm closing this out, but feel free to drop a comment if you need something else.

**Comment by Tapchicoma** [comment]
> I can upgrade to 2.0.0-Beta5 immediately, but looks like there are some API changes starting with 2.0.0 that I would need to look into if you needed something more recent.

2.0.0-Beta5 should be fine as it supports Kotlin language version 2.0 and Kotlin language version 2.1.

Generally given Kotlin release should support +1 Kotlin language version. For example Kotlin 2.1.0 will support language version 2.2.
