### ISSUE TITLE
BadParcelableException in Activity onCreate

### ISSUE THREAD

**Issue by aftabahmadTW** [google/dagger#4223]
Hi team, our project has recently started to get these `BadParcelableException` on the Activity `onCreate`. We use Hilt in our project and it seems like this issue popped up in the 2.50 release.

The stacktrace is:
```
android.os.Parcel.readValue (Parcel.java:4661)
android.os.Parcel.readValue (Parcel.java:4320)
android.os.Parcel.readSparseArrayInternal (Parcel.java:5358)
android.os.Parcel.readValue (Parcel.java:4616)
android.os.Parcel.readValue (Parcel.java:4312)
android.os.Parcel.-$$Nest$mreadValue
android.os.Parcel$LazyValue.apply (Parcel.java:4410)
android.os.Parcel$LazyValue.apply (Parcel.java:4369)
android.os.BaseBundle.getValueAt (BaseBundle.java:394)
android.os.BaseBundle.getValue (BaseBundle.java:374)
android.os.BaseBundle.getValue (BaseBundle.java:357)
android.os.BaseBundle.getValue (BaseBundle.java:350)
android.os.Bundle.getSparseParcelableArray (Bundle.java:1088)
androidx.fragment.app.FragmentStateManager.restoreState (FragmentStateManager.java:408)
androidx.fragment.app.FragmentManager.restoreSaveStateInternal (FragmentManager.java:2503)
androidx.fragment.app.FragmentManager.attachController (FragmentManager.java:2656)
androidx.fragment.app.FragmentController.attachHost (FragmentController.java:117)
androidx.fragment.app.FragmentActivity.lambda$init$3 (FragmentActivity.java:140)
androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable (ContextAwareHelper.kt:84)
androidx.activity.ComponentActivity.onCreate (ComponentActivity.java:378)
androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:217)
Hilt_SignUpActivity.onCreate (Hilt_SignUpActivity.java:62)
SignUpActivity.onCreate (SignUpActivity.kt:124)
android.app.Activity.performCreate (Activity.java:8538)
android.app.Activity.performCreate (Activity.java:8502)
```

Not sure exactly what's causing this but it's happening for a few different activities in our codebase. The majority seem to happen on Android 13 but it isn't exclusive to that version. Some of the screens don't have ViewModels for them. For example `SignUpActivity` just injects a few interfaces.

Any advice or help would be much appreciated!

**Comment by kuanyingchou** [comment]
Hi, @aftabahmadTW , could you share a more complete stacktrace? It seems that the first lines are missing.

**Comment by aftabahmadTW** [comment]
Hi @kuanyingchou Here is the full trace:

```
Caused by android.os.BadParcelableException: Parcel android.os.Parcel@75eed3b: Unmarshalling unknown type code 3473458 at offset 3412
       at android.os.Parcel.readValue(Parcel.java:4750)
       at android.os.Parcel.readValue(Parcel.java:4398)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:5481)
       at android.os.Parcel.readValue(Parcel.java:4705)
       at android.os.Parcel.readValue(Parcel.java:4390)
       at android.os.Parcel.-$$Nest$mreadValue()
       at android.os.Parcel$LazyValue.apply(Parcel.java:4488)
       at android.os.Parcel$LazyValue.apply(Parcel.java:4447)
       at android.os.BaseBundle.unwrapLazyValueFromMapLocked(BaseBundle.java:415)
       at android.os.BaseBundle.getValueAt(BaseBundle.java:401)
       at android.os.BaseBundle.getValue(BaseBundle.java:381)
       at android.os.BaseBundle.getValue(BaseBundle.java:364)
       at android.os.BaseBundle.getValue(BaseBundle.java:357)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:1108)
       at androidx.fragment.app.FragmentStateManager.restoreState(FragmentStateManager.java:408)
       at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2503)
       at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:2656)
       at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:117)
       at androidx.fragment.app.FragmentActivity.lambda$init$3(FragmentActivity.java:140)
       at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.kt:84)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:358)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:217)
       at com.our.package.Hilt_SignUpActivity.onCreate(Hilt_SignUpActivity.java:62)
       at com.our.package.SignUpActivity.onCreate(SignUpActivity.kt:124)
       at android.app.Activity.performCreate(Activity.java:8891)
       at android.app.Activity.performCreate(Activity.java:8856)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3965)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4136)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2581)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:224)
       at android.os.Looper.loop(Looper.java:318)
       at android.app.ActivityThread.main(ActivityThread.java:8727)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

`SignUpActivity` doesn't parcel any complex types into the bundle just a Boolean and a String ID.  It only injects a few navigator interfaces.

**Comment by kuanyingchou** [comment]
Hi, @aftabahmadTW , thanks for the full trace. This is probably not related to Hilt or Dagger as neither reads from or writes to the instance state. From the trace the error happens when `FragmentStateManager ` is trying to restore `VIEW_STATE_KEY` for view hierarchies. Could `SignUpActivity` contain any rogue `Parcelable`s (e.g. incompatible read/write implementations) in its views?
