### ISSUE TITLE
Does Hilt always execute app module during instrumented test?

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/dagger#4354]
I just migrated a project from Dagger to Hilt, everything works fine except when executing `./gradlew connectedAndroidTest` with AVD running in a CI CD pipeline. There is this [bug](https://issuetracker.google.com/issues/242831041) we are experiencing when running such tests in pipeline that we previously solved by modularizing the project so the app module no longer contains any instrumented test. However after migrating to Hilt and using it to inject dependency in each module instrumented test, the bug started to show again. The [instrumented test](https://doc-3mig-4a30-issuetracker.googleusercontent.com/attachments/6ugsl664md3oma7d9qe0i8a8ar3l3hpd/ml4l82nvo4c5err7tv2hsr688af6erl3/1720835100000/326800/115846262492303161025/242831041::57893700::326800?dat=AFNnbnlRGDRtDRG8mcTh0iIXOQIk8fOnh4WtxJMyQi9YL8KwDE57kHYCnIpOkMtWGE10Igog8gz7MkCa4FPPwLcUMnZEV2RdxjcRQJpLqjBxe23b829mxSRiFOn4yQXu50Drjh7GjuE8PixdIkqV_XHVrg9XEx9HLBzBBgBLhuoUHrjNFTbQaLy9RP01D8NU196vixfS-3UxyPWw28oX0R7jVLxO11LOeEc6HsvgelE0tPsZnJ4heisR45rMhb2WsXCbo5A97o3Uel5PprpggEYyFhs8XadEembH_mOIJxTQ9wIu5Y4yAX0fsc1pgBWVSO5fubpUD3O3EXdYNPzHayTehv1M8Zmv_cd_Ar-YPvid6-ho2GOmnxSNUgQ9Uh0UVrEgZuRz_RAYxGfXUUYuxYHacTlSUgWAo5yjXM0ZJReRxo6u5GxtL_egkyJF_BTRWMjlrr1fFeyBVM45-x057exZL_SG2egwGUHKXxm-lwsj07YUuDcYYxZNUqmKS5qO4d0WWMLilEHf6Cv1Zz0UJs6xVDGdmNd9Jo7eh6ubJeTVqZxvVxX58_dAQxzzsmIQlIO6EQwTtISSemLJoAFU6GK7xi7vb-IHYNREOFS9Egie9WdgpY-J1akBJudLnyQs4e9au21mxCeIY4l3494yWlnm-UwqYyRMWOls6OpMWaN5y30JQIbc4LYpmK60jN34YUNtb3qA_o_u6nrdy-HRrWrUe0Lsm66QSfuF7bt5t1OBXBiu1qvoElAYzfxFpOQCbJ1XZ4WbctS_UYAsi4Z8NSnFElzfr3v3TJrGqSdJKsyCniCC53EWReNB_sb_HWniy6_1CM67MwZGpqnfojZa4pz3s8eVKg1d1kMDSv491tEQRJOXArATl4cxPeggndnfR4cejfd4-CqSmDd3adatzOKyIyoBeV9QPqSEM3SwRDbfWOLEOc5h4-7kk6ml3ZFTu46szus4ahgIcDh8sh4WakcwGKNBPUPnNQ&u=0&s=1&q=AN9yeQJK-VCK9gPIiX_fFx0MMxcU5ZIDfV9QWKgpaVuLMx8XYRNpcGSVbT7Fpl7KYWe84jCs2n0i0hmTxQ2eBmTrR_273w&download=false&nonce=rjutn05i99i8o&user=115846262492303161025&hash=hdv7geetut2b87p2cmu208hklh7fv2hi) on each modules are success but for some reason the task `:app:connectedDebugAndroidTest` is also getting executed again despite not having a `androidTest`.

```
> Task :AndroidCommon:connectedDebugAndroidTest

Starting 3 tests on EMU(AVD) - 6.0


Finished 3 tests on EMU(AVD) - 6.0


> Task :AndroidCommon:connectedAndroidTest


> Task :Messari:connectedDebugAndroidTest

additionalTestOutput is not supported on this device running API level 23 because the additional test output directory could not be found

Starting 29 tests on EMU(AVD) - 6.0


EMU(AVD) - 6.0 Tests 8/29 completed. (0 skipped) (0 failed)

EMU(AVD) - 6.0 Tests 16/29 completed. (0 skipped) (0 failed)

Finished 29 tests on EMU(AVD) - 6.0


> Task :Messari:connectedAndroidTest


> Task :WordPress:connectedDebugAndroidTest

additionalTestOutput is not supported on this device running API level 23 because the additional test output directory could not be found

Starting 10 tests on EMU(AVD) - 6.0


EMU(AVD) - 6.0 Tests 10/10 completed. (0 skipped) (0 failed)

Finished 10 tests on EMU(AVD) - 6.0


> Task :WordPress:connectedAndroidTest


> Task :YouTube:connectedDebugAndroidTest

additionalTestOutput is not supported on this device running API level 23 because the additional test output directory could not be found

Starting 10 tests on EMU(AVD) - 6.0


Finished 10 tests on EMU(AVD) - 6.0


> Task :YouTube:connectedAndroidTest


> Task :app:connectedDebugAndroidTest

additionalTestOutput is not supported on this device running API level 23 because the additional test output directory could not be found


Finished 0 tests on EMU(AVD) - 6.0


> Task :app:connectedDebugAndroidTest

There were failing tests. See the report at: file:///opt/atlassian/pipelines/agent/build/app/build/reports/androidTests/connected/debug/index.html


> Task :app:connectedAndroidTest

Exception thrown during onBeforeAll invocation of plugin AndroidTestApkInstallerPlugin: ErrorName: UNKNOWN

NameSpace: DdmlibAndroidDeviceController

ErrorCode: 1

ErrorType: TEST

Message: Failed to install split APK(s): [/opt/atlassian/pipelines/agent/build/app/build/outputs/apk/debug/app-debug.apk]

Failed to install split APK(s): [/opt/atlassian/pipelines/agent/build/app/build/outputs/apk/debug/app-debug.apk]

Unknown platform error occurred when running the UTP test suite. Please check logs for details.

com.android.ddmlib.ShellCommandUnresponsiveException

	at com.android.ddmlib.internal.DeviceImpl.lambda$executeRemoteCommand$18(DeviceImpl.java:891)

	at com.android.ddmlib.internal.DeviceImpl.logRun1(DeviceImpl.java:1801)

	at com.android.ddmlib.internal.DeviceImpl.executeRemoteCommand(DeviceImpl.java:755)

	at com.android.ddmlib.SplitApkInstallerBase.installCommit(SplitApkInstallerBase.java:154)

	at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:85)

	at com.android.ddmlib.IDeviceSharedImpl.installPackages(IDeviceSharedImpl.java:395)

	at com.android.ddmlib.internal.DeviceImpl.lambda$installPackages$34(DeviceImpl.java:1491)

	at com.android.ddmlib.internal.DeviceImpl.logRun3(DeviceImpl.java:1833)

	at com.android.ddmlib.internal.DeviceImpl.installPackages(DeviceImpl.java:1488)

	at com.android.ddmlib.internal.DeviceImpl.lambda$installPackages$35(DeviceImpl.java:1503)

	at com.android.ddmlib.internal.DeviceImpl.logRun3(DeviceImpl.java:1833)

	at com.android.ddmlib.internal.DeviceImpl.installPackages(DeviceImpl.java:1499)

	at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDevice.installPackages(DdmlibAndroidDevice.kt:74)

	at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDeviceController$executeAsync$deferred$1.invokeSuspend(DdmlibAndroidDeviceController.kt:259)

	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)

	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)

	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by bcorso** [comment]
Hmm, I don't know.Since there's nothing in the logs hinting to Hilt or Dagger, I don't think there is anything actionable we can do with this, unfortunately.

**Comment by bcorso** [comment]
>Does Hilt always execute app module during instrumented test?

Do you have a Gradle scan? That should tell you why the task is running

**Comment by ArcherEmiya05** [comment]
> > Does Hilt always execute app module during instrumented test?
> 
> Do you have a Gradle scan? That should tell you why the task is running

May I know how to do this part? Thanks
