### ISSUE TITLE
codegen NullPointerException at dagger.shaded.auto.common.MoreElements.asExecutable(MoreElements.java:173)

### ISSUE THREAD

**Issue by vorburger** [google/dagger#443]
Perhaps you'd like to harden the generator code against this NullPointerException (seen in an IDE) ?

```
!MESSAGE Exception thrown by Java annotation processor dagger.internal.codegen.ComponentProcessor@17bf168e
!STACK 0
java.lang.Exception: java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:110)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:437)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:456)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:368)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:179)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:487)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:399)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$3.run(SetupTaskPerformer.java:3066)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at dagger.shaded.auto.common.MoreElements.asExecutable(MoreElements.java:173)
	at dagger.internal.codegen.DependencyRequestFormatter$1.visitVariableAsParameter(DependencyRequestFormatter.java:130)
	at dagger.internal.codegen.DependencyRequestFormatter$1.visitVariableAsParameter(DependencyRequestFormatter.java:97)
	at javax.lang.model.util.ElementKindVisitor6.visitVariable(ElementKindVisitor6.java:235)
	at org.eclipse.jdt.internal.compiler.apt.model.VariableElementImpl.accept(VariableElementImpl.java:56)
	at dagger.internal.codegen.DependencyRequestFormatter.format(DependencyRequestFormatter.java:96)
	at dagger.internal.codegen.DependencyRequestFormatter.format(DependencyRequestFormatter.java:63)
	at dagger.internal.codegen.Formatter.apply(Formatter.java:50)
	at dagger.internal.codegen.Formatter.apply(Formatter.java:32)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:674)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:692)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209)
	at com.google.common.collect.FluentIterable.toList(FluentIterable.java:484)
	at dagger.internal.codegen.DependencyRequestFormatter.toDependencyTrace(DependencyRequestFormatter.java:86)
	at dagger.internal.codegen.BindingGraphValidator$Validation.reportCycle(BindingGraphValidator.java:1163)
	at dagger.internal.codegen.BindingGraphValidator$Validation.traverseDependencyRequest(BindingGraphValidator.java:341)
	at dagger.internal.codegen.BindingGraphValidator$Validation.traverseDependencyRequest(BindingGraphValidator.java:354)
	at dagger.internal.codegen.BindingGraphValidator$Validation.traverseDependencyRequest(BindingGraphValidator.java:354)
	at dagger.internal.codegen.BindingGraphValidator$Validation.validateSubgraph(BindingGraphValidator.java:278)
	at dagger.internal.codegen.BindingGraphValidator.validate(BindingGraphValidator.java:1209)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:139)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:47)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:171)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	... 26 more
```

**Comment by ronshapiro** [comment]
Have you seen this again?

**Comment by vorburger** [comment]
No but more likely not because it's fixed but because not using Dagger after all for the moment.. ;)

Feel free to close though of course. Re-open if anyone else finds this by web search.
