### ISSUE TITLE
Support Kotlin 2.1.0

### ISSUE THREAD

**Issue by ZacSweers** [google/dagger#4451]
When testing dagger with ~K2~ Kapt on Kotlin 2.1.0-Beta1, it fails with the below trace.

### Repro
- Checkout https://github.com/slackhq/circuit/pull/1677
- Set `kapt.use.k2=true` in `gradle.properties`
- `./gradlew :samples:star:kaptReleaseKotlinAndroid`

### Trace
```
Caused by: java.lang.IllegalStateException: Unable to read Kotlin metadata due to unsupported metadata version.	
	at dagger.internal.codegen.kotlin.KotlinMetadata.metadataOf(KotlinMetadata.java:180)	
	at dagger.internal.codegen.kotlin.KotlinMetadata.from(KotlinMetadata.java:157)	
	at dagger.internal.codegen.kotlin.KotlinMetadataFactory.create(KotlinMetadataFactory.java:55)	
	at dagger.internal.codegen.kotlin.KotlinMetadataUtil.getAllMethodNamesBySignature(KotlinMetadataUtil.java:89)	
	at dagger.internal.codegen.validation.ComponentValidator$ElementValidator.validateClassMethodName(ComponentValidator.java:256)	
	at dagger.internal.codegen.validation.ComponentValidator$ElementValidator.validateComponentMethods(ComponentValidator.java:247)	
	at dagger.internal.codegen.validation.ComponentValidator$ElementValidator.validateElement(ComponentValidator.java:176)	
	at dagger.internal.codegen.validation.ComponentValidator.validateUncached(ComponentValidator.java:136)	
	at dagger.internal.codegen.base.Util.reentrantComputeIfAbsent(Util.java:33)	
	at dagger.internal.codegen.validation.ComponentValidator.validate(ComponentValidator.java:132)	
	at dagger.internal.codegen.processingstep.ComponentProcessingStep.isComponentValid(ComponentProcessingStep.java:149)	
	at dagger.internal.codegen.processingstep.ComponentProcessingStep.processRootComponent(ComponentProcessingStep.java:98)	
	at dagger.internal.codegen.processingstep.ComponentProcessingStep.process(ComponentProcessingStep.java:87)	
	at dagger.internal.codegen.processingstep.ComponentProcessingStep.process(ComponentProcessingStep.java:49)	
	at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:94)	
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:297)	
	at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:72)	
	at dagger.internal.codegen.processingstep.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:49)	
	at dagger.spi.internal.shaded.androidx.room.compiler.processing.XProcessingStep.process(XProcessingStep.kt:57)	
	at dagger.spi.internal.shaded.androidx.room.compiler.processing.CommonProcessorDelegate.processRound(XBasicAnnotationProcessor.kt:134)	
	at dagger.spi.internal.shaded.androidx.room.compiler.processing.javac.JavacBasicAnnotationProcessor.process(JavacBasicAnnotationProcessor.kt:75)	
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
```

**Comment by bcorso** [comment]
I think this should have been fixed by https://github.com/google/dagger/issues/4211#issuecomment-2356602496 but you'll need to use the `HEAD-SNAPSHOTS` until the next official release.

**Comment by ZacSweers** [comment]
quick edit - not specific to K2 kapt, this is just a general need for an updated release with newer kotlin-metadata

**Comment by TWiStErRob** [comment]
This became very relevant suddenly as [Kotlin 2.1.0](https://kotlinlang.org/docs/whatsnew21.html) is released.

We're on latest release (`dagger = "2.52"`) and the error showed up.
Using `dagger = "HEAD-SNAPSHOT"` with
```gradle
repositories {
    google()
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven("https://oss.sonatype.org/content/repositories/snapshots") {
                name = "Sonatype SNAPSHOTs"
            }
        }
        filter {
            includeVersionByRegex("com\\.google\\.dagger.*", ".*", "HEAD-SNAPSHOT")
        }
    }
}
```
solves this issue, so this confirms Brad's claim above.

**Comment by bcorso** [comment]
@TWiStErRob thanks for confirming. I'll be out the next few days, but I can do a release early next week.

**Comment by bcorso** [comment]
Closing. This should be fixed in Dagger 2.53.

**Comment by hgftrdw45ud67is8o89** [comment]
I tried to update the version
`    implementation("com.google.dagger:hilt-android:2.53.0")
    kapt("com.google.dagger:hilt-android-compiler:2.53.0")`

But it says>Failed to resolve: com.google.dagger:hilt-android:2.53.0

**Comment by bcorso** [comment]
@hgftrdw45ud67is8o89 it's just `2.53` not `2.53.0`.

**Comment by hgftrdw45ud67is8o89** [comment]
ahhh huge thanks.
