### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by Baberu** [google/dagger#4514]
```
Process: com.example.unsplashclient, PID: 6048
java.lang.RuntimeException: Unable to instantiate application com.example.unsplashclient.App package com.example.unsplashclient: java.lang.ClassNotFoundException: Didn't find class "com.example.unsplashclient.App" on path: DexPathList[[zip file "/data/app/~~u7AWCwzKB5ar_fx2exdy2w==/com.example.unsplashclient-WlLJNUEqC59n18N2G05pUw==/base.apk"],nativeLibraryDirectories=[/data/app/~~u7AWCwzKB5ar_fx2exdy2w==/com.example.unsplashclient-WlLJNUEqC59n18N2G05pUw==/lib/arm64, /data/app/~~u7AWCwzKB5ar_fx2exdy2w==/com.example.unsplashclient-WlLJNUEqC59n18N2G05pUw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
  at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)
  at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6772)
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loopOnce(Looper.java:201)
  at android.os.Looper.loop(Looper.java:288)
  at android.app.ActivityThread.main(ActivityThread.java:7924)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.unsplashclient.App" on path: DexPathList[[zip file "/data/app/~~u7AWCwzKB5ar_fx2exdy2w==/com.example.unsplashclient-WlLJNUEqC59n18N2G05pUw==/base.apk"],nativeLibraryDirectories=[/data/app/~~u7AWCwzKB5ar_fx2exdy2w==/com.example.unsplashclient-WlLJNUEqC59n18N2G05pUw==/lib/arm64, /data/app/~~u7AWCwzKB5ar_fx2exdy2w==/com.example.unsplashclient-WlLJNUEqC59n18N2G05pUw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
  at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:51)
  at android.app.Instrumentation.newApplication(Instrumentation.java:1243)
  at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
  at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395) 
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6772) 
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133) 
  at android.os.Handler.dispatchMessage(Handler.java:106) 
  at android.os.Looper.loopOnce(Looper.java:201) 
  at android.os.Looper.loop(Looper.java:288) 
  at android.app.ActivityThread.main(ActivityThread.java:7924) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
  Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/example/unsplashclient/Hilt_App;
    at java.lang.VMClassLoader.findLoadedClass(Native Method)
    at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
    ... 16 more
  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.unsplashclient.Hilt_App" on path: DexPathList[[zip file "/data/app/~~u7AWCwzKB5ar_fx2exdy2w==/com.example.unsplashclient-WlLJNUEqC59n18N2G05pUw==/base.apk"],nativeLibraryDirectories=[/data/app/~~u7AWCwzKB5ar_fx2exdy2w==/com.example.unsplashclient-WlLJNUEqC59n18N2G05pUw==/lib/arm64, /data/app/~~u7AWCwzKB5ar_fx2exdy2w==/com.example.unsplashclient-WlLJNUEqC59n18N2G05pUw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    ... 19 more
```

**Comment by bcorso** [comment]
Closing as dupe of #4139

**Comment by Baberu** [comment]
@bcorso how to fix?

**Comment by Baberu** [comment]
https://stackoverflow.com/questions/67650422/hilt-java-lang-classnotfoundexception-didnt-find-class-com-kotlin20test-hilt

above i do it

**Comment by yatoooon** [comment]
Similar issues
