### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid relative name: META-INF\proguard\com_example_ui_backupBackupViewModel_HiltModules_BindsModule_LazyClassKeys.pro

### ISSUE THREAD

**Issue by HyakYegoryaln** [google/dagger#4533]
I am encountering an issue when building my project on Windows devices. The build process fails due to problems related to META-INF files, specifically during KAPT or while processing dependencies like com.google.dagger:hilt-compiler.

This issue only occurs on Windows systems, and the project builds without issues on macOS and Linux.

```
Caused by: java.lang.IllegalArgumentException: Invalid relative name: META-INF\proguard\[com_example_ui_backupBackupViewModel_HiltModules_BindsModule_LazyClassKeys.pro](http://com_example_ui_backupbackupviewmodel_hiltmodules_bindsmodule_lazyclasskeys.pro/)
    at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getFileForOutput(Unknown Source)
    at org.jetbrains.kotlin.kapt3.base.javac.KaptJavaFileManager.getFileForOutput(KaptJavaFileManager.kt:82)
    at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createResource(Unknown Source)
    at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalFiler.createResource(incrementalProcessors.kt:121)
    at dagger.spi.internal.shaded.androidx.room.compiler.processing.javac.JavacFiler.writeResource(JavacFiler.kt:94)
    at dagger.internal.codegen.processingstep.LazyClassKeyProcessingStep.writeProguardFile(LazyClassKeyProcessingStep.java:112)
    at dagger.internal.codegen.processingstep.LazyClassKeyProcessingStep.processOver(LazyClassKeyProcessingStep.java:106)
    at dagger.spi.internal.shaded.androidx.room.compiler.processing.XProcessingStep.process(XProcessingStep.kt:54)
    at dagger.spi.internal.shaded.androidx.room.compiler.processing.CommonProcessorDelegate.processLastRound(XBasicAnnotationProcessor.kt:168)
    at dagger.spi.internal.shaded.androidx.room.compiler.processing.javac.JavacBasicAnnotationProcessor.process(JavacBasicAnnotationProcessor.kt:65)
    at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
    at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:216)
```

I use:
implementation "com.google.dagger:hilt-android:2.53"
kapt "com.google.dagger:hilt-compiler:2.53"

id 'com.android.application' version '8.7.2' apply false
id 'org.jetbrains.kotlin.android' version '2.0.21' apply false
gradle-8.9

**Comment by cemtufekci** [comment]
happens on my project too.

kotlin: 2.0.21
agp: 8.7.3
dagger: 2.53

**Comment by cemtufekci** [comment]
This error also happens in 2.53.1

**Comment by HyakYegoryaln** [comment]
I tried using KSP instead of KAPT, and the problem was resolved. I used KSP version "2.0.21-1.0.28"

**Comment by cemtufekci** [comment]
I can't remove kapt because I'm using databinding.

**Comment by bcorso** [comment]
I took a brief look at this and my guess this is due to Java's [`Path.of()`](https://javadoc.scijava.org/Java11/java.base/java/nio/file/Path.html#of(java.lang.String,java.lang.String...)) automatically converting the path separators in the original string to OS-specifc path separators. In particular, we use `/` to create the file [here](https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/processingstep/LazyClassKeyProcessingStep.java#L113) but the path in the error message uses `\` (i.e. `META-INF\proguard\...`).

Typically, choosing the OS-specific path separators would be the behavior we would want; however, in this case the resource file is being stored in a JAR file, and the defined path separator in a JAR is `/`. Thus, I think we'll need to make an API change in XProcessing, since [XFiler#createResource()](https://github.com/androidx/androidx/blob/androidx-main/room/room-compiler-processing/src/main/java/androidx/room/compiler/processing/XFiler.kt#L58) only takes in a `Path`.

I'll file a bug to XProcessing and link it here.

**Comment by ctufekci** [comment]
Should we wait for a new release ?

**Comment by cemtufekci** [comment]
Should we wait for a new release ?

**Comment by bcorso** [comment]
Yes, however I'm still waiting on the XProcessing fix (https://issuetracker.google.com/383578358) to be available to Dagger. I should be able to do a release in the next day or two.

**Comment by bcorso** [comment]
I'll plan on doing a release tomorrow, but if anyone wants to try it out and verify the fix beforehand you can use Dagger's [HEAD-SNAPSHOT](https://dagger.dev/dev-guide/versions) artifact. 

While we're pretty confident the XProcessing change should fix this issue, we also don't have any test coverage on Window so we'll be relying on your feedback to verify the fix.

**Comment by cemtufekci** [comment]
Sure thing, I'm gonna test as soon as possible when it's live.

**Comment by cemtufekci** [comment]
It's working now. Thank you so much !

**Comment by JimVanG** [comment]
> I can't remove kapt because I'm using databinding.

That's fine because you don't need to remove the `kapt`. What you would've done is only replace the `kapt` with the newer `ksp` annotation-processor for only the `Hilt`/`Dagger` dependency. 

Replacing the `kapt` with the `ksp` in `Hilt`/ `Dagger`  fixed the issue that was being faced on windows machines with the `META-INF` errors.
