### ISSUE TITLE
Error hilt/drager when use in module java.lang.ClassCastException

### ISSUE THREAD

**Issue by xuandieudev** [google/dagger#4548]
This is my config hilt/drager. i tried change implement to api is the same https://github.com/google/dagger/issues/1991 but it not working.
Please help me. Thank U

build.gradle(app)

```
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.hilt.android)
    id("kotlin-kapt")
}

hilt {
    //  enableAggregatingTask = true
    enableExperimentalClasspathAggregation = true
}

dependencies {
    api(project(":library:base"))
    api(libs.hilt.android)
    kapt(libs.hilt.compiler)
}
```

build.gradle(module library)

```
plugins {
    alias(libs.plugins.android.dynamic.feature)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.hilt.android)
    id("kotlin-kapt")
}

hilt {
    enableAggregatingTask = true
}

dependencies {
    implementation(project(":app"))
    // Hilt for Dependency Injection
    api(libs.hilt.android)
    kapt(libs.hilt.compiler)
}
```

Error:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{vn.cooldev.dashcam/vn.cooldev.library.presentation.view.LibraryActivity}: java.lang.ClassCastException: vn.cooldev.dashcam.DaggerAppApplication_HiltComponents_SingletonC$ActivityCImpl cannot be cast to vn.cooldev.library.presentation.view.LibraryActivity_GeneratedInjector
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3991)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:224)
    at android.os.Looper.loop(Looper.java:318)
    at android.app.ActivityThread.main(ActivityThread.java:8777)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
  Caused by: java.lang.ClassCastException: vn.cooldev.dashcam.DaggerAppApplication_HiltComponents_SingletonC$ActivityCImpl cannot be cast to vn.cooldev.library.presentation.view.LibraryActivity_GeneratedInjector
    at vn.cooldev.library.presentation.view.Hilt_LibraryActivity.inject(Hilt_LibraryActivity.java:93)
    at vn.cooldev.library.presentation.view.Hilt_LibraryActivity$1.onContextAvailable(Hilt_LibraryActivity.java:40)
    at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.kt:84)
    at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:358)
    at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:216)
    at vn.cooldev.base.BaseActivity.onCreate(BaseActivity.kt:40)
    at vn.cooldev.library.presentation.view.Hilt_LibraryActivity.onCreate(Hilt_LibraryActivity.java:57)
    at android.app.Activity.performCreate(Activity.java:8891)
    at android.app.Activity.performCreate(Activity.java:8856)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144) 
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loopOnce(Looper.java:224) 
    at android.os.Looper.loop(Looper.java:318) 
    at android.app.ActivityThread.main(ActivityThread.java:8777) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) 
```

**Comment by bcorso** [comment]
Looks like you are using dynamic features. See https://github.com/google/dagger/issues/2758
