### ISSUE TITLE
IllegalArgumentException for array dependency without provider

### ISSUE THREAD

**Issue by marwinxxii** [google/dagger#630]
Hi everyone,

I've noticed a strange not very informative error, when I forgot to add provider method for depedency of array type.

```
Execution failed for task ':app:compileJava'.
> java.lang.IllegalArgumentException: com.daggertest.DependencyWithoutProvider[] cannot be converted to an Element
```

And here's a sample:
```
@Component(modules = MyTestModule.class)
public interface MyComponent {
  DependencyWithoutProvider[] getTestDependencies();
}

@Module
public class MyTestModule {
  //provider method should be here
}
```

This happens only when depency is an array, in other cases, e.g. when method returns `DependencyWithoutProvider` or `Set<DependencyWithoutProvider>` there is a detailed error message:

```
MyComponent.java:9: error: java.util.Set<com.daggertest.DependencyWithoutProvider> cannot be provided without an @Provides-annotated method.
  Set<DependencyWithoutProvider> getTestDependencies();
                                 ^
      java.util.Set<com.daggertest.DependencyWithoutProvider> is provided at
          com.daggertest.MyComponent.getTestDependencies()
1 error
```

Good thing that it's still possible to find dependency producing this error, but it would be nice to have such detailed message for arrays too.

**Comment by ronshapiro** [comment]
I think I know what this is, but can you run gradle with the full stack trace printed and copy that here?

**Comment by marwinxxii** [comment]
```
Caused by: java.lang.IllegalArgumentException: com.daggertest.DependencyWithoutProvider[] cannot be converted to an Element
  at dagger.shaded.auto.common.MoreTypes$AsElementVisitor.defaultAction(MoreTypes.java:532)
  at dagger.shaded.auto.common.MoreTypes$AsElementVisitor.defaultAction(MoreTypes.java:527)
  at com.sun.tools.javac.code.Type$ArrayType.accept(Type.java:1135)
  at dagger.shaded.auto.common.MoreTypes.asElement(MoreTypes.java:524)
  at dagger.shaded.auto.common.MoreTypes.asTypeElement(MoreTypes.java:553)
  at dagger.internal.codegen.InjectBindingRegistry.getOrFindMembersInjectionBinding(InjectBindingRegistry.java:320)
  at dagger.internal.codegen.BindingGraphValidator$Validation.requiresErrorMessageBase(BindingGraphValidator.java:1021)
  at dagger.internal.codegen.BindingGraphValidator$Validation.reportMissingBinding(BindingGraphValidator.java:1033)
  at dagger.internal.codegen.BindingGraphValidator$Validation.validateResolvedBindings(BindingGraphValidator.java:392)
  at dagger.internal.codegen.BindingGraphValidator$Validation.traverseDependencyRequest(BindingGraphValidator.java:347)
  at dagger.internal.codegen.BindingGraphValidator$Validation.validateSubgraph(BindingGraphValidator.java:283)
  at dagger.internal.codegen.BindingGraphValidator.validate(BindingGraphValidator.java:1247)
  at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:139)
  at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:47)
  at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:329)
  at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:182)
  at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
  at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
  at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  at com.sun.tools.javac.main.Main.compile(Main.java:523)
  ... 88 more
```
[full stacktrace](https://github.com/google/dagger/files/842713/log.txt)

**Comment by ronshapiro** [comment]
Thanks, I'll take a look when I get some time.
