### ISSUE TITLE
IllegalStateException that just breaks compilation without reporting the offending class

### ISSUE THREAD

**Issue by hrgdavor** [google/dagger#690]
A simple leftover from migration with raw Map in @Inject constructor.
(background: TapestryIOC marks metohds contributing to a Map with marker that points to class where it will be injected later. So it was not required to have a typed Map as long as the contributions don't put incompattible objects inside)
```java
public BuilderImpl(DepA a, Map builders){
        this.builders = builders;
}
```
causes the exception that can be only seen after runing maven with -e switch (or debug checkbox in eclipse).

This should be an error that is reported by the compiler, and not make it fail silently.

```
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at dagger.internal.codegen.MapType.valueType(MapType.java:70)
	at dagger.internal.codegen.MapType.valuesAreTypeOf(MapType.java:80)
	at dagger.internal.codegen.Key$Factory.rewrapMapKey(Key.java:619)
	at dagger.internal.codegen.BindingGraph$Factory$Resolver.keysMatchingRequest(BindingGraph.java:532)
	at dagger.internal.codegen.BindingGraph$Factory$Resolver.lookUpBindings(BindingGraph.java:443)
	at dagger.internal.codegen.BindingGraph$Factory$Resolver.resolve(BindingGraph.java:970)
	at dagger.internal.codegen.BindingGraph$Factory$Resolver.resolve(BindingGraph.java:973)
    ...
```

**Comment by ronshapiro** [comment]
Are you using Kotlin?

**Comment by hrgdavor** [comment]
No, this is normal Java project. Just that the previous DI allowed Constructor to declare raw Map. I was able to find the cause and fix it. Just saying it would be good to get error saying what is the offending class in question.

I took me some time and looking into stack trace and Dagger cause to find out that a Raw map was causing it to break. Then I had to search the codebase to find a raw Map in a constructor.

Dagger throwing error with the offending class name would make it trivial to correct in code. Currently it took some digging.

**Comment by ronshapiro** [comment]
Ah - this is totally a dagger bug. We just need to check to see if the type is a raw type there.

**Comment by vovkab** [comment]
Just got the same crash, it doesn't show what is wrong, have no idea what to fix :(

**Comment by ronshapiro** [comment]
@vovkab that's a totally different issue. Feel free to file a different ticket (with the version of Dagger you're using please!)
