### ISSUE TITLE
Dagger with Bazel issues with 2.10 (not previous versions)

### ISSUE THREAD

**Issue by shaeberling** [google/dagger#710]
I am using Bazel with a basic simple Dagger project not many dependencies.

In the WORKSPACE file I define:

```
maven_jar(
    name = "google_guava",
    artifact = "com.google.guava:guava:21.0",
)
maven_jar(
    name = "dagger_api",
    artifact = "com.google.dagger:dagger:2.10",
)
maven_jar(
    name = "dagger_compiler",
    artifact = "com.google.dagger:dagger-compiler:2.10",
)
maven_jar(
    name = "dagger_producers",
    artifact = "com.google.dagger:dagger-producers:2.10",
)
maven_jar(
    name = "jsr330_inject",
    artifact = "javax.inject:javax.inject:1",
)
```

And my third_party/BUILD looks like this:
```
java_library(
    name = "dagger",
    exported_plugins = [":dagger_plugin"],
    exports = [
        "@dagger_api//jar",
        "@jsr330_inject//jar",
    ],
)

java_plugin(
    name = "dagger_plugin",
    processor_class = "dagger.internal.codegen.ComponentProcessor",
    deps = [
        "@dagger_api//jar",
        "@dagger_compiler//jar",
        "@dagger_producers//jar",
        "@google_guava//jar",
        "@jsr330_inject//jar",
    ],
)
```

And finally my code's BUILD file looks like this:
```
java_binary(
    name = "Main",
    srcs = 
        glob(["src/**/*.java"]),
    deps = [
        "@google_guava//jar",
        "@org_json//jar",
        "//third_party:dagger",
    ]
)
```

This all works, if I set the dagger versions above to 2.5,2.6,2.7,2.8 or 2.9. But with 2.10, there seems to be a dependency missing and I get this issue:

```
java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/google/googlejavaformat/java/filer/FormattingFiler
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:144)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:104)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:163)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:52)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:166)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:178)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:90)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:44)
Caused by: java.lang.NoClassDefFoundError: com/google/googlejavaformat/java/filer/FormattingFiler
	at dagger.internal.codegen.ComponentProcessor.initSteps(ComponentProcessor.java:66)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.init(BasicAnnotationProcessor.java:119)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:539)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:636)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:727)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2000(JavacProcessingEnvironment.java:100)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1046)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1153)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1120)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:814)
	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:97)
	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:93)
	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:128)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.google.googlejavaformat.java.filer.FormattingFiler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
Target //:Main failed to build
```

If I add a dependency for googlejavaformat and now it misses an openJDK class.... so this seems like the wrong way to go.

Any idea what's missing with 2.10 and above?

**Comment by ronshapiro** [comment]
You're missing a dep for GoogleJavaFormat. I don't see why this wouldn't fail with just 2.10, because the other versions also needed GoogleJavaFormat.

Because we also use bazel, you should probably use: [`http_archive`](https://bazel.build/versions/master/docs/be/workspace.html#http_archive) (see the comment on `git_repository`. That will make sure you don't have an dependency collisions with any other library that uses the same deps+versions that we do.

**Comment by shaeberling** [comment]
Thanks for the fast response, Ron. This is looking better. I used:

```
http_archive(
    name = "dagger",
    url = "https://github.com/google/dagger/archive/dagger-2.10.zip",
    strip_prefix = "dagger-dagger-2.10",
)
```

And then in my binary I use "**@dagger//:dagger_with_compiler**" like so:
```
java_binary(
    name = "Main",
    srcs = 
        glob(["src/**/*.java"]),
    deps = [
        "@com_google_guava_guava//jar",
        "@org_json//jar",
        "@dagger//:dagger_with_compiler",
    ]
)
```

But one issue remains, and that might just be me not knowing what I am doing: If I don't replicate the dependencies dagger has within its WORKSPACE file, it fails to resolve them:

```
ERROR: /Users/[...]/BUILD:1:1: no such package '@com_google_guava_guava//jar': error loading package 'external': The repository named 'com_google_guava_guava' could not be resolved and referenced by '//:Main'.
```

If I copy-paste all the dependencies you have in your WORKSPACE file, things work. But I would  assume, these dependencies would be taken automatically, especially since the documentation for [http_archive](https://bazel.build/versions/master/docs/be/workspace.html#http_archive) mentions having a WORKSPACE file in the top-level directory.

**Comment by ronshapiro** [comment]
You have to declare all of them explicitly. That's how bazel ensures that you only ever have one version of a dependency on the classpath. Some libraries define a bzl file to make this easier, but the sense I get is that those are convenient in the beginning but then present issues when different libraries conflict.

**Comment by ronshapiro** [comment]
I'm going to close this issue for project maintenance, but feel free to continue commenting and we can discuss what's the best approach for getting your bazel deps set up

**Comment by shaeberling** [comment]
Ok, thanks, Ron, then this is now WAI and all working! Appreciate the feedback!

**Comment by ronshapiro** [comment]
There may be java_library targets that aren't exposed, definitely comment
if you see any friction with that.
