### ISSUE TITLE
NoClassDefFoundError, NoSuchMethodError & ExceptionInInitializerError

### ISSUE THREAD

**Issue by vikramkakkar** [google/dagger#736]
Hi,

We're seeing a few incidents with `NoClassDefFoundError`, `NoSuchMethodError` & `ExceptionInInitializerError` being thrown in our generated Dagger component's initialize() method. The # of crashes is low, but I would like to understand why these errors are being thrown at all. 

Our android app is _multidex_ enabled.

Some stacktraces:

```
Fatal Exception: java.lang.NoClassDefFoundError: --------.ui.activities.ahl
       at ----------.di.DaggerAlaskaComponent.initialize(SourceFile:1135)
       at ----------.di.DaggerAlaskaComponent.(SourceFile:49)
       at ----------.di.DaggerAlaskaComponent$Builder.build(SourceFile:23431)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:973)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3971)
       at android.app.ActivityThread.access$1300(ActivityThread.java:128)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4517)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method desiredAssertionStatus()Z in class Ljava/lang/Class; or its super classes (declaration of 'java.lang.Class' appears in /system/framework/core-libart.jar)
       at ----------.di.DaggerAlaskaComponent.(SourceFile)
       at ----------.di.DaggerAlaskaComponent.builder(SourceFile:58)
       at ----------.Alaska.createAlaskaComponent(SourceFile:13652)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4959)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

```
Fatal Exception: java.lang.NoSuchMethodError: java.lang.Class.dAsir%dAbyertion[dmtu;
       at ----------.di.DaggerAlaskaComponent.(SourceFile:45)
       at ----------.Alaska.createAlaskaComponent(SourceFile:23658)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4443)
       at android.app.ActivityThread.access$1500(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5120)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at ----------.di.DaggerBaliActivityComponent.initialize(SourceFile:1595)
       at ----------.di.DaggerBaliActivityComponent.(SourceFile:126)
       at ----------.di.DaggerBaliActivityComponent$Builder.build(SourceFile:32065)
       at ----------.ui.main.base.BaliWatchedActivity.getBaliActivityComponent(SourceFile:440)
       at ----------.ui.activities.MainActivity.onCreate(SourceFile:966)
       at android.app.Activity.performCreate(Activity.java:5020)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2211)
       at android.app.ActivityThread.access$600(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1300)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:4987)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.StackOverflowError
       at ----------.di.DaggerBaliActivityComponent.initialize(SourceFile:1595)
       at ----------.di.DaggerBaliActivityComponent.(SourceFile:126)
       at ----------.di.DaggerBaliActivityComponent$Builder.build(SourceFile:32065)
       at ----------.ui.main.base.BaliWatchedActivity.getBaliActivityComponent(SourceFile:440)
       at ----------.ui.activities.MainActivity.onCreate(SourceFile:966)
       at android.app.Activity.performCreate(Activity.java:5020)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2211)
       at android.app.ActivityThread.access$600(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1300)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:4987)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Devices distribution doesn't show a trend either. 

Any help with these would be much appreciated. Thanks!

**Comment by Zhuinden** [comment]
You did the whole `MultiDex.install(baseContext)` shenanigan to support API < 21, right?

**Comment by vikramkakkar** [comment]
Yes, we do have that in our `Application` class:

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

**Comment by vikramkakkar** [comment]
We have a theory regarding these crashes. Our released APKs are often _modded_ and released through unofficial channels. Since the number of crashes is really small (in most cases < 100), could these be caused while the APK modifier is experimenting with obfuscated classes?

**Comment by ronshapiro** [comment]
This is a build issue, not a Dagger issue. Try forums for the gradle plugin? Dagger only focuses on things compiling in `javac`.
