### ISSUE TITLE
Two different exceptions with versions 7 and 11 in same project

### ISSUE THREAD

**Issue by cheskos** [google/dagger#770]
Hello. A project is refusing to build and throws the following exceptions:

#### First issue
```
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
        at com.google.googlejavaformat.java.filer.FormattingFiler.<init>(FormattingFiler.java:37)
        at com.google.googlejavaformat.java.filer.FormattingFiler.<init>(FormattingFiler.java:42)
        at dagger.internal.codegen.ComponentProcessor.initSteps(ComponentProcessor.java:66)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.init(BasicAnnotationProcessor.java:119)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
```
***Version***
dagger: 2.11

#### Second issue
```
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Multimaps.filterKeys(Lcom/google/common/collect/SetMultimap;Lcom/google/common/base/Predicate;)Lcom/google/common/collect/SetMultimap;
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:321)
        at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:182)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
```
***Version***
dagger: 2.7

***Setup***
Android Studio: 2.3.3
Build tools: 25.0.3
Autodagger2: 1.1
Gradle: 2.3.3

Let me know if you need any further info.

Thanks.

**Comment by tbroyer** [comment]
Both errors point to dependency conflicts. The first one has been covered in https://github.com/google/dagger/issues/638, the second suggests you're using a version of Guava older than 14 (where that `filterKeys(SetMultimap,Predicate)` overload was added, according to the javadocs).

Those aren't Dagger issues, but Gradle configuration issues. Use [`./gradlew dependencies`](https://docs.gradle.org/2.3/userguide/tutorial_gradle_command_line.html#sec:listing_dependencies) and [`./gradlew dependencyInsight`](https://docs.gradle.org/2.3/userguide/tutorial_gradle_command_line.html#sec:dependency_insight) to debug them, and if needed ask for help on StackOverflow.

**Comment by cheskos** [comment]
Hi @tbroyer thank you for your reply. I ran both commands and the smallest guava version used is 18. `./gradlew app:dependencyInsight --dependency guava --configuration compile` shows

```
com.google.guava:guava-jdk5:13.0
\--- com.google.api-client:google-api-client:1.20.0
     \--- com.google.api-client:google-api-client-android:1.20.0
          \--- project :backend
               \--- compile
```
The :backend project doesn't use Dagger at all though

**Comment by tbroyer** [comment]
It doesn't matter whether the :backend project uses Dagger or not, it's a dependency of the :app project and it brings guava-jdk5 13.0. See #651

**Comment by ronshapiro** [comment]
First, you probably need `annotationProcessor 'com.google.guava:guava:22.0'`. That won't conflict with the google api client since the scope is just for the annotationProcessorPath.

You may also need `annotationProcessor 'com.google.googlejavaformat:googlejavaformat:1.3'` (i think that's the version. Feel free to reopen if adding those doesn't solve the issue
