### ISSUE TITLE
Dagger 2 doesn't support @Nullable type annotations.

### ISSUE THREAD

**Issue by jameslyon** [google/dagger#861]
In Java 8 annotations can be attached to types as well as methods/parameters/etc. The checker framework  (https://checkerframework.org/) uses this to provide type-safety for null/non-null values. The annotations it uses for this must annotate types rather than methods/parameters/variables, so must be fetched from TypeMirror.getAnnotationMirror.

The following example fails with:

```
Exception in thread "main" java.lang.NullPointerException: Cannot return null from a non-@Nullable @Provides method
	at dagger.internal.Preconditions.checkNotNull(Preconditions.java:48)
	at DaggerDaggerTypeNullable_MyComponent.makeMyType(DaggerDaggerTypeNullable_MyComponent.java:18)
	at DaggerTypeNullable.main(DaggerTypeNullable.java:9)
```

```java
import dagger.Component;
import dagger.Module;
import dagger.Provides;
import org.checkerframework.checker.nullness.qual.Nullable;

public class DaggerTypeNullable {
  public static void main(String[] args) {
    System.out.println(DaggerDaggerTypeNullable_MyComponent.builder().build().makeMyType());
  }

  @Component(modules = MyModule.class)
  interface MyComponent {
    @Nullable MyType makeMyType();
  }

  @Module
  static abstract class MyModule {
    @Provides @Nullable static MyType provideMyType() {
      return null;
    }
  }

  interface MyType {}
}
```

It works when using javax.annotation.Nullable instead.

**Comment by ronshapiro** [comment]
I think the fix to this would probably be something like appending something like the following diff [here](https://github.com/google/dagger/blob/23e6df7e052ab8c355a348e6a0986a2460c48690/java/dagger/internal/codegen/ConfigurationAnnotations.java#L164)

```diff
+  FluentIterable<AnnotationMirror> mirrors =
+        FluentIterable.from((List<AnnotationMirror>) (List) element.getAnnotationMirrors())
+           .append(element.asType().getAnnotationMirrors());
-   List<? extends AnnotationMirror> mirrors = element.getAnnotationMirrors();
```

But i'm not sure the full ramifications of that. Would be good to check all of the places where we might need to do the same - we shouldn't be inconsistent with how we use type annotations. We have disabled type annotations for qualifiers in Google for Guice+Dagger for this issue - we haven't been able to fully evaluate it yet.

**Comment by octylFractal** [comment]
Any update on this?
