### ISSUE TITLE
app crash on device below 4.4 with dagger2 for NoClassDefFoundError:dagger.internal.Preconditions

### ISSUE THREAD

**Issue by yupuxilong** [google/dagger#873]
the error log is as below,and it is ok on device just like M and N ,can anybody help me.
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.pvirtech.police.ch, PID: 1785
                                                                      java.lang.NoClassDefFoundError: dagger.internal.Preconditions
                                                                          at com.pvirtech.police.ch.di.component.DaggerApplicationComponent$Builder.applicationModule(DaggerApplicationComponent.java:213)
                                                                          at com.pvirtech.police.ch.PvirtechApplication.onCreate(PvirtechApplication.java:97)
                                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
                                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by ronshapiro** [comment]
This appears to be a question - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.
