### ISSUE TITLE
Latest Eclipse Oxygen failing with NoSuchFieldError: MODULE

### ISSUE THREAD

**Issue by rkapsi** [google/dagger#898]
Eclipse Oxygen.1a (4.7.1a). Older versions or lets say the most recent M2 build of Photon don't have that problem.

```java
!ENTRY org.eclipse.jdt.apt.pluggable.core 4 1 2017-10-11 14:52:56.540
!MESSAGE Exception thrown by Java annotation processor dagger.internal.codegen.ComponentProcessor@1463c50b
!STACK 0
java.lang.Exception: java.lang.NoSuchFieldError: MODULE
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:933)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:443)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:187)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NoSuchFieldError: MODULE
	at org.eclipse.jdt.internal.compiler.apt.model.ModuleElementImpl.getKind(ModuleElementImpl.java:64)
	at dagger.shaded.auto.common.Visibility.ofElement(Visibility.java:49)
	at dagger.shaded.auto.common.Visibility.effectiveVisibilityOfElement(Visibility.java:74)
	at dagger.internal.codegen.ModuleValidator.validateModuleVisibility(ModuleValidator.java:454)
	at dagger.internal.codegen.ModuleValidator.validateUncached(ModuleValidator.java:201)
	at dagger.internal.codegen.Util.reentrantComputeIfAbsent(Util.java:115)
	at dagger.internal.codegen.ModuleValidator.validate(ModuleValidator.java:147)
	at dagger.internal.codegen.ModuleProcessingStep.processModule(ModuleProcessingStep.java:124)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:117)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:329)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:182)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	... 24 more
```

**Comment by Jotschi** [comment]
I was able to resolve / workaround that issue by starting my eclipse with Java 9 - that somehow only happens if you start the IDE with Java 8.

**Comment by ronshapiro** [comment]
https://github.com/google/auto/commit/2c035ce5172a6c4d21d859e2609b57358db02f6f fixes this. We need an auto-common release and then we can start using that.

**Comment by eamonnmcmanus** [comment]
@ronshapiro I don't think you are right that this is fixed in auto-common. The bug is in Eclipse and has been [reported](https://bugs.eclipse.org/bugs/show_bug.cgi?id=526288) there.

**Comment by ronshapiro** [comment]
Ah, thanks for clarifying @eamonnmcmanus.
