### ISSUE TITLE
Guava collections are leaked into the generated code

### ISSUE THREAD

**Issue by ArazAbishov** [google/dagger#903]
First of all, the question is if it is expected to have guava collections in the generated code? If yes, then the scope of the problem is probably different. 

Version of dagger and included artifacts:
```groovy
implementation "com.google.dagger:dagger:2.12"
implementation "com.google.dagger:dagger-android-support:2.12"
annotationProcessor "com.google.dagger:dagger-compiler:2.12"
annotationProcessor "com.google.dagger:dagger-android-processor:2.12"
```

Application crashes during start-up because of Guava not being on the classpath. Android gradle plugin version is `3.0.0-rc1` (so it might be an issue related to the new plugin). 

```
java.lang.NoClassDefFoundError: 
   Failed resolution of: Lcom/google/common/collect/ImmutableMap;
   at com.abishov.hexocat.DaggerAppComponent.injectHexocat(DaggerAppComponent.java:110)
   at com.abishov.hexocat.DaggerAppComponent.inject(DaggerAppComponent.java:95)
   at com.abishov.hexocat.Hexocat.setupAppComponent(Hexocat.java:78)
   at com.abishov.hexocat.Hexocat.onCreate(Hexocat.java:47)
   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
   at android.app.ActivityThread.-wrap1(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
   at android.os.Handler.dispatchMessage(Handler.java:105)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6541)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.collect.ImmutableMap" on path: DexPathList[[zip file "/data/app/com.abishov.hexocat.debug-YLCwmoGpVZ6cQfhMyPGprA==/base.apk", zip file "/data/app/com.abishov.hexocat.debug-YLCwmoGpVZ6cQfhMyPGprA==/split_lib_dependencies_apk.apk"
   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
   at com.abishov.hexocat.DaggerAppComponent.injectHexocat(DaggerAppComponent.java:110) 
   at com.abishov.hexocat.DaggerAppComponent.inject(DaggerAppComponent.java:95) 
   at com.abishov.hexocat.Hexocat.setupAppComponent(Hexocat.java:78) 
   at com.abishov.hexocat.Hexocat.onCreate(Hexocat.java:47) 
   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118) 
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791) 
   at android.app.ActivityThread.-wrap1(Unknown Source:0) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
   at android.os.Handler.dispatchMessage(Handler.java:105) 
   at android.os.Looper.loop(Looper.java:164) 
   at android.app.ActivityThread.main(ActivityThread.java:6541) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

P.S. cleaning and building doesn't help, as well as cleaning IDE cashes.

**Comment by gabrielittner** [comment]
Do you have any `compileOnly` or `provided` dependencies? See #897

**Comment by ArazAbishov** [comment]
@gabrielittner Thanks. The problem was in the `compileOnly` autovalue dependency, which has "confused" dagger on existence of guava on the classpath. Thanks to the almighty @jakewharton for publishing standalone autovalue-annotations artifact: https://github.com/JakeWharton/AutoValueAnnotations
