### ISSUE TITLE
Internal Eclipse error on MissingBinding

### ISSUE THREAD

**Issue by foal** [google/dagger#925]
Try to use Dagger 2.12 in Eclipse and gets the tens internal errors like this
`java.lang.Exception: java.lang.IndexOutOfBoundsException: index (-1) must not be negative
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:933)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:443)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:331)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:136)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:267)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:195)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.IndexOutOfBoundsException: index (-1) must not be negative
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1159)
	at dagger.internal.codegen.Formatter.formatArgumentInList(Formatter.java:91)
	at dagger.internal.codegen.DependencyRequestFormatter$1.visitVariableAsParameter(DependencyRequestFormatter.java:153)
	at dagger.internal.codegen.DependencyRequestFormatter$1.visitVariableAsParameter(DependencyRequestFormatter.java:113)
	at java.compiler@9/javax.lang.model.util.ElementKindVisitor6.visitVariable(ElementKindVisitor6.java:233)
	at org.eclipse.jdt.internal.compiler.apt.model.VariableElementImpl.accept(VariableElementImpl.java:56)
	at dagger.internal.codegen.DependencyRequestFormatter.format(DependencyRequestFormatter.java:112)
	at dagger.internal.codegen.DependencyRequestFormatter.lambda$format$0(DependencyRequestFormatter.java:94)
	at dagger.internal.codegen.ComponentTreeTraverser$DependencyTrace$1.tryAdvance(ComponentTreeTraverser.java:642)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:511)
	at dagger.internal.codegen.DependencyRequestFormatter.format(DependencyRequestFormatter.java:98)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation$BindingGraphValidation.formatDependencyTrace(BindingGraphValidator.java:589)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation$BindingGraphValidation.reportMissingBinding(BindingGraphValidator.java:909)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation$BindingGraphValidation.visitResolvedBindings(BindingGraphValidator.java:603)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitDependencyRequest(ComponentTreeTraverser.java:238)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation$BindingGraphValidation.visitDependencyRequest(BindingGraphValidator.java:597)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.nextDependencyRequest(ComponentTreeTraverser.java:388)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitBinding(ComponentTreeTraverser.java:372)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitContributionBinding(ComponentTreeTraverser.java:351)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation$BindingGraphValidation.visitContributionBinding(BindingGraphValidator.java:646)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.lambda$visitContributionBindings$0(ComponentTreeTraverser.java:332)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.lambda$visitContributionBindings$1(ComponentTreeTraverser.java:332)
	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:65)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitContributionBindings(ComponentTreeTraverser.java:330)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitResolvedBindings(ComponentTreeTraverser.java:261)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation$BindingGraphValidation.visitResolvedBindings(BindingGraphValidator.java:607)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitDependencyRequest(ComponentTreeTraverser.java:238)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation$BindingGraphValidation.visitDependencyRequest(BindingGraphValidator.java:597)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.nextDependencyRequest(ComponentTreeTraverser.java:388)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitBinding(ComponentTreeTraverser.java:372)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitContributionBinding(ComponentTreeTraverser.java:351)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation$BindingGraphValidation.visitContributionBinding(BindingGraphValidator.java:646)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.lambda$visitContributionBindings$0(ComponentTreeTraverser.java:332)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.lambda$visitContributionBindings$1(ComponentTreeTraverser.java:332)
	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:65)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitContributionBindings(ComponentTreeTraverser.java:330)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitResolvedBindings(ComponentTreeTraverser.java:261)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation$BindingGraphValidation.visitResolvedBindings(BindingGraphValidator.java:607)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.visitDependencyRequest(ComponentTreeTraverser.java:238)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation$BindingGraphValidation.visitDependencyRequest(BindingGraphValidator.java:597)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.nextDependencyRequest(ComponentTreeTraverser.java:388)
	at dagger.internal.codegen.ComponentTreeTraverser$BindingGraphTraverser.traverseDependencies(ComponentTreeTraverser.java:221)
	at dagger.internal.codegen.ComponentTreeTraverser.visitEntryPoint(ComponentTreeTraverser.java:162)
	at dagger.internal.codegen.ComponentTreeTraverser.visitComponent(ComponentTreeTraverser.java:122)
	at dagger.internal.codegen.BindingGraphValidator$ComponentValidation.visitComponent(BindingGraphValidator.java:204)
	at dagger.internal.codegen.ComponentTreeTraverser.traverseComponents(ComponentTreeTraverser.java:84)
	at dagger.internal.codegen.BindingGraphValidator.validate(BindingGraphValidator.java:1192)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:139)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:47)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:329)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:182)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	... 24 more
`

**Env:**

`eclipse.buildId=3.9.1.201710111105-RELEASE-e47
java.version=9
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.springsource.sts.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springsource.sts.ide
`

**Comment by ronshapiro** [comment]
I think this a bug with eclipse. We have a parameter for a constructor, from which we obtain the actual constructor, and then call `indexOf` on the constructor's parameter list. Maybe there's an equality bug on their end?

**Comment by foal** [comment]
Unfortunately, I can't debug it easy, but this bug makes the using the Dagger very harder because it can't regenerate the code and silently crash. So I need to have opened the error view and monitor this error in the eclipse log. Then comment the problem method from Component and then add one by one injected objects from the underlying graph to find the problem injection.

As I understand the code above tries to generate and provide this information automatically. And it will be great if it will work, but in case if it crashes maybe show at least some information?

Anyway STS 3.9.1 based on Eclipse 4.7.1a.

I can't find any similar bugs on Eclipse side. There is only one with very similar stack trace: #443

**Comment by ronshapiro** [comment]
Can you run your code with javac instead of with Eclipse? That should uncover the issue.

**Comment by foal** [comment]
Yes, you are right. It is eclipse issue. Command line is Ok. An even Eclipse after javac shows the correct error.

**Comment by foal** [comment]
Place new bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=253915
